export enum DonationStatus {
  RAISED = 'RAISED',
  PAID = 'PAID',
  PENDING = 'PENDING',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAY_LATER = 'PAY_LATER',
  CANCELLED = 'CANCELLED',
  UPDATE_MISTAKE = 'UPDATE_MISTAKE',
}
