export enum ActivityScale {
  TASK = 'TASK',
  ACTIVITY = 'ACTIVITY',
  EVENT = 'EVENT',
}
export enum ActivityType {
  TRAINING = 'TRAINING',
  AWARENESS = 'AWARENESS',
  DISTRIBUTION = 'DISTRIBUTION',
  SURVEY = 'SURVEY',
  MEETING = 'MEETING',
  FIELD_VISIT = 'FIELD_VISIT',
  DOCUMENTATION = 'DOCUMENTATION',
  WORKSHOP = 'WORKSHOP',
  SEMINAR = 'SEMINAR',
  FUNDRAISING = 'FUNDRAISING',
  VOLUNTEER_ACTIVITY = 'VOLUNTEER_ACTIVITY',
  CONFERENCE = 'CONFERENCE',
  EXHIBITION = 'EXHIBITION',
  OTHER = 'OTHER',
}
export enum ActivityStatus {
  PLANNED = 'PLANNED',
  CONFIRMED = 'CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  ON_HOLD = 'ON_HOLD',
}
export enum ActivityPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}
