export enum ProjectCategory {
  EDUCATION = 'EDUCATION',
  HEALTH = 'HEALTH',
  ENVIRONMENT = 'ENVIRONMENT',
  RURAL_DEVELOPMENT = 'RURAL_DEVELOPMENT',
  WOMEN_EMPOWERMENT = 'WOMEN_EMPOWERMENT',
  CHILD_WELFARE = 'CHILD_WELFARE',
  DISASTER_RELIEF = 'DISASTER_RELIEF',
  OTHER = 'OTHER',
}
export enum ProjectStatus {
  PLANNING = 'PLANNING',
  ACTIVE = 'ACTIVE',
  ON_HOLD = 'ON_HOLD',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
export enum ProjectPhase {
  INITIATION = 'INITIATION',
  PLANNING = 'PLANNING',
  EXECUTION = 'EXECUTION',
  MONITORING = 'MONITORING',
  CLOSURE = 'CLOSURE',
}
