export enum TeamMemberRole {
  PROJECT_MANAGER = 'PROJECT_MANAGER',
  TEAM_LEAD = 'TEAM_LEAD',
  COORDINATOR = 'COORDINATOR',
  VOLUNTEER = 'VOLUNTEER',
  CONSULTANT = 'CONSULTANT',
  OTHER = 'OTHER',
}
