export enum Configkey {
  ENVIRONMENT = 'ENVIRONMENT',
  APP_NAME = 'APP_NAME',
  APP_SECRET = 'APP_SECRET',

  // Auth0
  AUTH0_DOMAIN = 'AUTH0_DOMAIN',
  AUTH0_MANAGEMENT_CLIENT_ID = 'AUTH0_MANAGEMENT_CLIENT_ID',
  AUTH0_MANAGEMENT_CLIENT_SECRET = 'AUTH0_MANAGEMENT_CLIENT_SECRET',

  // Jwks
  JWT_JWKS_URI = 'JWT_JWKS_URI',
  JWT_ISSUER = 'JWT_ISSUER',
  JWT_AUDIENCE = 'JWT_AUDIENCE',

  // Databases
  MONGODB_URL = 'MONGODB_URL',
  DATABASE_URL = 'DATABASE_URL',
  REDIS_URL = 'REDIS_URL',

  // CORS
  CORS_ALLOWED_ORIGIN = 'CORS_ALLOWED_ORIGIN',
  CORS_ALLOWED_METHODS = 'CORS_ALLOWED_METHODS',

  // Google reCAPTCHA
  GOOGLE_RECAPTCHA_SECURITY_KEY = 'GOOGLE_RECAPTCHA_SECURITY_KEY',

  // Google OAuth
  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
  //GOOGLE_REDIRECT_URI = 'GOOGLE_REDIRECT_URI',

  // Firebase
  FIREBASE_FILESTORAGE_BUCKET = 'FIREBASE_FILESTORAGE_BUCKET',
  FIREBASE_CREDENTIAL = 'FIREBASE_CREDENTIAL',

  // Email
  ENABLE_EMAIL_MOCKING = 'ENABLE_EMAIL_MOCKING',
  MOCKED_EMAIL_ADDRESS = 'MOCKED_EMAIL_ADDRESS',
  ENABLE_PROD_MODE = 'ENABLE_PROD_MODE',
  EMAIL_SENDER = 'EMAIL_SENDER',

  // URLs
  APP_BE_URL = 'APP_BE_URL',
  APP_FE_URL = 'APP_FE_URL',
  APP_PUBLIC_URL = 'APP_PUBLIC_URL',

  // Runtime
  NODE_ENV = 'NODE_ENV',
  LOG_LEVEL = 'LOG_LEVEL',

  // Observability
  SLACK_WEBHOOK_URL = 'SLACK_WEBHOOK_URL',

  // Business properties
  // PROP_DONATION_AMOUNT = 'PROP_DONATION_AMOUNT',
  // PROP_NOTIFICATION_KEEP_DAYS = 'PROP_NOTIFICATION_KEEP_DAYS',
  // PROP_FCMT_KEEP_DAYS = 'PROP_FCMT_KEEP_DAYS',
  // PROP_COMPLETED_JOB_RETENTION_DAYS = 'PROP_COMPLETED_JOB_RETENTION_DAYS',
  // PROP_FAILED_JOB_RETENTION_DAYS = 'PROP_FAILED_JOB_RETENTION_DAYS',

  // Push notifications
  ONESIGNAL_APP_ID = 'ONESIGNAL_APP_ID',
  ONESIGNAL_REST_API_KEY = 'ONESIGNAL_REST_API_KEY',

  // Integrations
  ENABLE_DB_AUDIT = "ENABLE_DB_AUDIT",
  DB_AUDIT_MODELS = "DB_AUDIT_MODELS",
  REDIS_CACHE_TTL = "REDIS_CACHE_TTL",
  FAIL_ON_AUDIT_ERROR = "FAIL_ON_AUDIT_ERROR",
  RECAPTCHA_MIN_SCORE = "RECAPTCHA_MIN_SCORE",
  MAX_FILE_SIZE_MB = "MAX_FILE_SIZE_MB",
}
