
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AuthUserRole` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model AuthUserRole
 * 
 */
export type AuthUserRoleModel = runtime.Types.Result.DefaultSelection<Prisma.$AuthUserRolePayload>

export type AggregateAuthUserRole = {
  _count: AuthUserRoleCountAggregateOutputType | null
  _min: AuthUserRoleMinAggregateOutputType | null
  _max: AuthUserRoleMaxAggregateOutputType | null
}

export type AuthUserRoleMinAggregateOutputType = {
  id: string | null
  idpSub: string | null
  ownerId: string | null
  entityId: string | null
  entityType: string | null
  roleId: string | null
  sourceGroupId: string | null
  grantedAt: Date | null
  revokedAt: Date | null
  grantedBy: string | null
  revokedBy: string | null
  note: string | null
}

export type AuthUserRoleMaxAggregateOutputType = {
  id: string | null
  idpSub: string | null
  ownerId: string | null
  entityId: string | null
  entityType: string | null
  roleId: string | null
  sourceGroupId: string | null
  grantedAt: Date | null
  revokedAt: Date | null
  grantedBy: string | null
  revokedBy: string | null
  note: string | null
}

export type AuthUserRoleCountAggregateOutputType = {
  id: number
  idpSub: number
  ownerId: number
  entityId: number
  entityType: number
  roleId: number
  sourceGroupId: number
  grantedAt: number
  revokedAt: number
  grantedBy: number
  revokedBy: number
  note: number
  _all: number
}


export type AuthUserRoleMinAggregateInputType = {
  id?: true
  idpSub?: true
  ownerId?: true
  entityId?: true
  entityType?: true
  roleId?: true
  sourceGroupId?: true
  grantedAt?: true
  revokedAt?: true
  grantedBy?: true
  revokedBy?: true
  note?: true
}

export type AuthUserRoleMaxAggregateInputType = {
  id?: true
  idpSub?: true
  ownerId?: true
  entityId?: true
  entityType?: true
  roleId?: true
  sourceGroupId?: true
  grantedAt?: true
  revokedAt?: true
  grantedBy?: true
  revokedBy?: true
  note?: true
}

export type AuthUserRoleCountAggregateInputType = {
  id?: true
  idpSub?: true
  ownerId?: true
  entityId?: true
  entityType?: true
  roleId?: true
  sourceGroupId?: true
  grantedAt?: true
  revokedAt?: true
  grantedBy?: true
  revokedBy?: true
  note?: true
  _all?: true
}

export type AuthUserRoleAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AuthUserRole to aggregate.
   */
  where?: Prisma.AuthUserRoleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuthUserRoles to fetch.
   */
  orderBy?: Prisma.AuthUserRoleOrderByWithRelationInput | Prisma.AuthUserRoleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AuthUserRoleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuthUserRoles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuthUserRoles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AuthUserRoles
  **/
  _count?: true | AuthUserRoleCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AuthUserRoleMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AuthUserRoleMaxAggregateInputType
}

export type GetAuthUserRoleAggregateType<T extends AuthUserRoleAggregateArgs> = {
      [P in keyof T & keyof AggregateAuthUserRole]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAuthUserRole[P]>
    : Prisma.GetScalarType<T[P], AggregateAuthUserRole[P]>
}




export type AuthUserRoleGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AuthUserRoleWhereInput
  orderBy?: Prisma.AuthUserRoleOrderByWithAggregationInput | Prisma.AuthUserRoleOrderByWithAggregationInput[]
  by: Prisma.AuthUserRoleScalarFieldEnum[] | Prisma.AuthUserRoleScalarFieldEnum
  having?: Prisma.AuthUserRoleScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AuthUserRoleCountAggregateInputType | true
  _min?: AuthUserRoleMinAggregateInputType
  _max?: AuthUserRoleMaxAggregateInputType
}

export type AuthUserRoleGroupByOutputType = {
  id: string
  idpSub: string
  ownerId: string | null
  entityId: string | null
  entityType: string | null
  roleId: string
  sourceGroupId: string | null
  grantedAt: Date
  revokedAt: Date | null
  grantedBy: string | null
  revokedBy: string | null
  note: string | null
  _count: AuthUserRoleCountAggregateOutputType | null
  _min: AuthUserRoleMinAggregateOutputType | null
  _max: AuthUserRoleMaxAggregateOutputType | null
}

export type GetAuthUserRoleGroupByPayload<T extends AuthUserRoleGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AuthUserRoleGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AuthUserRoleGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AuthUserRoleGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AuthUserRoleGroupByOutputType[P]>
      }
    >
  >



export type AuthUserRoleWhereInput = {
  AND?: Prisma.AuthUserRoleWhereInput | Prisma.AuthUserRoleWhereInput[]
  OR?: Prisma.AuthUserRoleWhereInput[]
  NOT?: Prisma.AuthUserRoleWhereInput | Prisma.AuthUserRoleWhereInput[]
  id?: Prisma.StringFilter<"AuthUserRole"> | string
  idpSub?: Prisma.StringFilter<"AuthUserRole"> | string
  ownerId?: Prisma.StringNullableFilter<"AuthUserRole"> | string | null
  entityId?: Prisma.StringNullableFilter<"AuthUserRole"> | string | null
  entityType?: Prisma.StringNullableFilter<"AuthUserRole"> | string | null
  roleId?: Prisma.StringFilter<"AuthUserRole"> | string
  sourceGroupId?: Prisma.StringNullableFilter<"AuthUserRole"> | string | null
  grantedAt?: Prisma.DateTimeFilter<"AuthUserRole"> | Date | string
  revokedAt?: Prisma.DateTimeNullableFilter<"AuthUserRole"> | Date | string | null
  grantedBy?: Prisma.StringNullableFilter<"AuthUserRole"> | string | null
  revokedBy?: Prisma.StringNullableFilter<"AuthUserRole"> | string | null
  note?: Prisma.StringNullableFilter<"AuthUserRole"> | string | null
  role?: Prisma.XOR<Prisma.AuthRoleScalarRelationFilter, Prisma.AuthRoleWhereInput>
  sourceGroup?: Prisma.XOR<Prisma.AuthRoleGroupNullableScalarRelationFilter, Prisma.AuthRoleGroupWhereInput> | null
}

export type AuthUserRoleOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  idpSub?: Prisma.SortOrder
  ownerId?: Prisma.SortOrderInput | Prisma.SortOrder
  entityId?: Prisma.SortOrderInput | Prisma.SortOrder
  entityType?: Prisma.SortOrderInput | Prisma.SortOrder
  roleId?: Prisma.SortOrder
  sourceGroupId?: Prisma.SortOrderInput | Prisma.SortOrder
  grantedAt?: Prisma.SortOrder
  revokedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  grantedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  revokedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  role?: Prisma.AuthRoleOrderByWithRelationInput
  sourceGroup?: Prisma.AuthRoleGroupOrderByWithRelationInput
}

export type AuthUserRoleWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AuthUserRoleWhereInput | Prisma.AuthUserRoleWhereInput[]
  OR?: Prisma.AuthUserRoleWhereInput[]
  NOT?: Prisma.AuthUserRoleWhereInput | Prisma.AuthUserRoleWhereInput[]
  idpSub?: Prisma.StringFilter<"AuthUserRole"> | string
  ownerId?: Prisma.StringNullableFilter<"AuthUserRole"> | string | null
  entityId?: Prisma.StringNullableFilter<"AuthUserRole"> | string | null
  entityType?: Prisma.StringNullableFilter<"AuthUserRole"> | string | null
  roleId?: Prisma.StringFilter<"AuthUserRole"> | string
  sourceGroupId?: Prisma.StringNullableFilter<"AuthUserRole"> | string | null
  grantedAt?: Prisma.DateTimeFilter<"AuthUserRole"> | Date | string
  revokedAt?: Prisma.DateTimeNullableFilter<"AuthUserRole"> | Date | string | null
  grantedBy?: Prisma.StringNullableFilter<"AuthUserRole"> | string | null
  revokedBy?: Prisma.StringNullableFilter<"AuthUserRole"> | string | null
  note?: Prisma.StringNullableFilter<"AuthUserRole"> | string | null
  role?: Prisma.XOR<Prisma.AuthRoleScalarRelationFilter, Prisma.AuthRoleWhereInput>
  sourceGroup?: Prisma.XOR<Prisma.AuthRoleGroupNullableScalarRelationFilter, Prisma.AuthRoleGroupWhereInput> | null
}, "id">

export type AuthUserRoleOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  idpSub?: Prisma.SortOrder
  ownerId?: Prisma.SortOrderInput | Prisma.SortOrder
  entityId?: Prisma.SortOrderInput | Prisma.SortOrder
  entityType?: Prisma.SortOrderInput | Prisma.SortOrder
  roleId?: Prisma.SortOrder
  sourceGroupId?: Prisma.SortOrderInput | Prisma.SortOrder
  grantedAt?: Prisma.SortOrder
  revokedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  grantedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  revokedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  note?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.AuthUserRoleCountOrderByAggregateInput
  _max?: Prisma.AuthUserRoleMaxOrderByAggregateInput
  _min?: Prisma.AuthUserRoleMinOrderByAggregateInput
}

export type AuthUserRoleScalarWhereWithAggregatesInput = {
  AND?: Prisma.AuthUserRoleScalarWhereWithAggregatesInput | Prisma.AuthUserRoleScalarWhereWithAggregatesInput[]
  OR?: Prisma.AuthUserRoleScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AuthUserRoleScalarWhereWithAggregatesInput | Prisma.AuthUserRoleScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AuthUserRole"> | string
  idpSub?: Prisma.StringWithAggregatesFilter<"AuthUserRole"> | string
  ownerId?: Prisma.StringNullableWithAggregatesFilter<"AuthUserRole"> | string | null
  entityId?: Prisma.StringNullableWithAggregatesFilter<"AuthUserRole"> | string | null
  entityType?: Prisma.StringNullableWithAggregatesFilter<"AuthUserRole"> | string | null
  roleId?: Prisma.StringWithAggregatesFilter<"AuthUserRole"> | string
  sourceGroupId?: Prisma.StringNullableWithAggregatesFilter<"AuthUserRole"> | string | null
  grantedAt?: Prisma.DateTimeWithAggregatesFilter<"AuthUserRole"> | Date | string
  revokedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"AuthUserRole"> | Date | string | null
  grantedBy?: Prisma.StringNullableWithAggregatesFilter<"AuthUserRole"> | string | null
  revokedBy?: Prisma.StringNullableWithAggregatesFilter<"AuthUserRole"> | string | null
  note?: Prisma.StringNullableWithAggregatesFilter<"AuthUserRole"> | string | null
}

export type AuthUserRoleCreateInput = {
  id?: string
  idpSub: string
  ownerId?: string | null
  entityId?: string | null
  entityType?: string | null
  grantedAt?: Date | string
  revokedAt?: Date | string | null
  grantedBy?: string | null
  revokedBy?: string | null
  note?: string | null
  role: Prisma.AuthRoleCreateNestedOneWithoutUserRolesInput
  sourceGroup?: Prisma.AuthRoleGroupCreateNestedOneWithoutUserRoleGroupsInput
}

export type AuthUserRoleUncheckedCreateInput = {
  id?: string
  idpSub: string
  ownerId?: string | null
  entityId?: string | null
  entityType?: string | null
  roleId: string
  sourceGroupId?: string | null
  grantedAt?: Date | string
  revokedAt?: Date | string | null
  grantedBy?: string | null
  revokedBy?: string | null
  note?: string | null
}

export type AuthUserRoleUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  idpSub?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  entityId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  entityType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  grantedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  revokedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  grantedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  revokedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.AuthRoleUpdateOneRequiredWithoutUserRolesNestedInput
  sourceGroup?: Prisma.AuthRoleGroupUpdateOneWithoutUserRoleGroupsNestedInput
}

export type AuthUserRoleUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  idpSub?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  entityId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  entityType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  sourceGroupId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  grantedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  revokedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  grantedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  revokedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AuthUserRoleCreateManyInput = {
  id?: string
  idpSub: string
  ownerId?: string | null
  entityId?: string | null
  entityType?: string | null
  roleId: string
  sourceGroupId?: string | null
  grantedAt?: Date | string
  revokedAt?: Date | string | null
  grantedBy?: string | null
  revokedBy?: string | null
  note?: string | null
}

export type AuthUserRoleUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  idpSub?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  entityId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  entityType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  grantedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  revokedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  grantedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  revokedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AuthUserRoleUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  idpSub?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  entityId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  entityType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  sourceGroupId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  grantedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  revokedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  grantedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  revokedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AuthUserRoleListRelationFilter = {
  every?: Prisma.AuthUserRoleWhereInput
  some?: Prisma.AuthUserRoleWhereInput
  none?: Prisma.AuthUserRoleWhereInput
}

export type AuthUserRoleOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AuthUserRoleCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  idpSub?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  entityType?: Prisma.SortOrder
  roleId?: Prisma.SortOrder
  sourceGroupId?: Prisma.SortOrder
  grantedAt?: Prisma.SortOrder
  revokedAt?: Prisma.SortOrder
  grantedBy?: Prisma.SortOrder
  revokedBy?: Prisma.SortOrder
  note?: Prisma.SortOrder
}

export type AuthUserRoleMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  idpSub?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  entityType?: Prisma.SortOrder
  roleId?: Prisma.SortOrder
  sourceGroupId?: Prisma.SortOrder
  grantedAt?: Prisma.SortOrder
  revokedAt?: Prisma.SortOrder
  grantedBy?: Prisma.SortOrder
  revokedBy?: Prisma.SortOrder
  note?: Prisma.SortOrder
}

export type AuthUserRoleMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  idpSub?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  entityType?: Prisma.SortOrder
  roleId?: Prisma.SortOrder
  sourceGroupId?: Prisma.SortOrder
  grantedAt?: Prisma.SortOrder
  revokedAt?: Prisma.SortOrder
  grantedBy?: Prisma.SortOrder
  revokedBy?: Prisma.SortOrder
  note?: Prisma.SortOrder
}

export type AuthUserRoleCreateNestedManyWithoutRoleInput = {
  create?: Prisma.XOR<Prisma.AuthUserRoleCreateWithoutRoleInput, Prisma.AuthUserRoleUncheckedCreateWithoutRoleInput> | Prisma.AuthUserRoleCreateWithoutRoleInput[] | Prisma.AuthUserRoleUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.AuthUserRoleCreateOrConnectWithoutRoleInput | Prisma.AuthUserRoleCreateOrConnectWithoutRoleInput[]
  createMany?: Prisma.AuthUserRoleCreateManyRoleInputEnvelope
  connect?: Prisma.AuthUserRoleWhereUniqueInput | Prisma.AuthUserRoleWhereUniqueInput[]
}

export type AuthUserRoleUncheckedCreateNestedManyWithoutRoleInput = {
  create?: Prisma.XOR<Prisma.AuthUserRoleCreateWithoutRoleInput, Prisma.AuthUserRoleUncheckedCreateWithoutRoleInput> | Prisma.AuthUserRoleCreateWithoutRoleInput[] | Prisma.AuthUserRoleUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.AuthUserRoleCreateOrConnectWithoutRoleInput | Prisma.AuthUserRoleCreateOrConnectWithoutRoleInput[]
  createMany?: Prisma.AuthUserRoleCreateManyRoleInputEnvelope
  connect?: Prisma.AuthUserRoleWhereUniqueInput | Prisma.AuthUserRoleWhereUniqueInput[]
}

export type AuthUserRoleUpdateManyWithoutRoleNestedInput = {
  create?: Prisma.XOR<Prisma.AuthUserRoleCreateWithoutRoleInput, Prisma.AuthUserRoleUncheckedCreateWithoutRoleInput> | Prisma.AuthUserRoleCreateWithoutRoleInput[] | Prisma.AuthUserRoleUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.AuthUserRoleCreateOrConnectWithoutRoleInput | Prisma.AuthUserRoleCreateOrConnectWithoutRoleInput[]
  upsert?: Prisma.AuthUserRoleUpsertWithWhereUniqueWithoutRoleInput | Prisma.AuthUserRoleUpsertWithWhereUniqueWithoutRoleInput[]
  createMany?: Prisma.AuthUserRoleCreateManyRoleInputEnvelope
  set?: Prisma.AuthUserRoleWhereUniqueInput | Prisma.AuthUserRoleWhereUniqueInput[]
  disconnect?: Prisma.AuthUserRoleWhereUniqueInput | Prisma.AuthUserRoleWhereUniqueInput[]
  delete?: Prisma.AuthUserRoleWhereUniqueInput | Prisma.AuthUserRoleWhereUniqueInput[]
  connect?: Prisma.AuthUserRoleWhereUniqueInput | Prisma.AuthUserRoleWhereUniqueInput[]
  update?: Prisma.AuthUserRoleUpdateWithWhereUniqueWithoutRoleInput | Prisma.AuthUserRoleUpdateWithWhereUniqueWithoutRoleInput[]
  updateMany?: Prisma.AuthUserRoleUpdateManyWithWhereWithoutRoleInput | Prisma.AuthUserRoleUpdateManyWithWhereWithoutRoleInput[]
  deleteMany?: Prisma.AuthUserRoleScalarWhereInput | Prisma.AuthUserRoleScalarWhereInput[]
}

export type AuthUserRoleUncheckedUpdateManyWithoutRoleNestedInput = {
  create?: Prisma.XOR<Prisma.AuthUserRoleCreateWithoutRoleInput, Prisma.AuthUserRoleUncheckedCreateWithoutRoleInput> | Prisma.AuthUserRoleCreateWithoutRoleInput[] | Prisma.AuthUserRoleUncheckedCreateWithoutRoleInput[]
  connectOrCreate?: Prisma.AuthUserRoleCreateOrConnectWithoutRoleInput | Prisma.AuthUserRoleCreateOrConnectWithoutRoleInput[]
  upsert?: Prisma.AuthUserRoleUpsertWithWhereUniqueWithoutRoleInput | Prisma.AuthUserRoleUpsertWithWhereUniqueWithoutRoleInput[]
  createMany?: Prisma.AuthUserRoleCreateManyRoleInputEnvelope
  set?: Prisma.AuthUserRoleWhereUniqueInput | Prisma.AuthUserRoleWhereUniqueInput[]
  disconnect?: Prisma.AuthUserRoleWhereUniqueInput | Prisma.AuthUserRoleWhereUniqueInput[]
  delete?: Prisma.AuthUserRoleWhereUniqueInput | Prisma.AuthUserRoleWhereUniqueInput[]
  connect?: Prisma.AuthUserRoleWhereUniqueInput | Prisma.AuthUserRoleWhereUniqueInput[]
  update?: Prisma.AuthUserRoleUpdateWithWhereUniqueWithoutRoleInput | Prisma.AuthUserRoleUpdateWithWhereUniqueWithoutRoleInput[]
  updateMany?: Prisma.AuthUserRoleUpdateManyWithWhereWithoutRoleInput | Prisma.AuthUserRoleUpdateManyWithWhereWithoutRoleInput[]
  deleteMany?: Prisma.AuthUserRoleScalarWhereInput | Prisma.AuthUserRoleScalarWhereInput[]
}

export type AuthUserRoleCreateNestedManyWithoutSourceGroupInput = {
  create?: Prisma.XOR<Prisma.AuthUserRoleCreateWithoutSourceGroupInput, Prisma.AuthUserRoleUncheckedCreateWithoutSourceGroupInput> | Prisma.AuthUserRoleCreateWithoutSourceGroupInput[] | Prisma.AuthUserRoleUncheckedCreateWithoutSourceGroupInput[]
  connectOrCreate?: Prisma.AuthUserRoleCreateOrConnectWithoutSourceGroupInput | Prisma.AuthUserRoleCreateOrConnectWithoutSourceGroupInput[]
  createMany?: Prisma.AuthUserRoleCreateManySourceGroupInputEnvelope
  connect?: Prisma.AuthUserRoleWhereUniqueInput | Prisma.AuthUserRoleWhereUniqueInput[]
}

export type AuthUserRoleUncheckedCreateNestedManyWithoutSourceGroupInput = {
  create?: Prisma.XOR<Prisma.AuthUserRoleCreateWithoutSourceGroupInput, Prisma.AuthUserRoleUncheckedCreateWithoutSourceGroupInput> | Prisma.AuthUserRoleCreateWithoutSourceGroupInput[] | Prisma.AuthUserRoleUncheckedCreateWithoutSourceGroupInput[]
  connectOrCreate?: Prisma.AuthUserRoleCreateOrConnectWithoutSourceGroupInput | Prisma.AuthUserRoleCreateOrConnectWithoutSourceGroupInput[]
  createMany?: Prisma.AuthUserRoleCreateManySourceGroupInputEnvelope
  connect?: Prisma.AuthUserRoleWhereUniqueInput | Prisma.AuthUserRoleWhereUniqueInput[]
}

export type AuthUserRoleUpdateManyWithoutSourceGroupNestedInput = {
  create?: Prisma.XOR<Prisma.AuthUserRoleCreateWithoutSourceGroupInput, Prisma.AuthUserRoleUncheckedCreateWithoutSourceGroupInput> | Prisma.AuthUserRoleCreateWithoutSourceGroupInput[] | Prisma.AuthUserRoleUncheckedCreateWithoutSourceGroupInput[]
  connectOrCreate?: Prisma.AuthUserRoleCreateOrConnectWithoutSourceGroupInput | Prisma.AuthUserRoleCreateOrConnectWithoutSourceGroupInput[]
  upsert?: Prisma.AuthUserRoleUpsertWithWhereUniqueWithoutSourceGroupInput | Prisma.AuthUserRoleUpsertWithWhereUniqueWithoutSourceGroupInput[]
  createMany?: Prisma.AuthUserRoleCreateManySourceGroupInputEnvelope
  set?: Prisma.AuthUserRoleWhereUniqueInput | Prisma.AuthUserRoleWhereUniqueInput[]
  disconnect?: Prisma.AuthUserRoleWhereUniqueInput | Prisma.AuthUserRoleWhereUniqueInput[]
  delete?: Prisma.AuthUserRoleWhereUniqueInput | Prisma.AuthUserRoleWhereUniqueInput[]
  connect?: Prisma.AuthUserRoleWhereUniqueInput | Prisma.AuthUserRoleWhereUniqueInput[]
  update?: Prisma.AuthUserRoleUpdateWithWhereUniqueWithoutSourceGroupInput | Prisma.AuthUserRoleUpdateWithWhereUniqueWithoutSourceGroupInput[]
  updateMany?: Prisma.AuthUserRoleUpdateManyWithWhereWithoutSourceGroupInput | Prisma.AuthUserRoleUpdateManyWithWhereWithoutSourceGroupInput[]
  deleteMany?: Prisma.AuthUserRoleScalarWhereInput | Prisma.AuthUserRoleScalarWhereInput[]
}

export type AuthUserRoleUncheckedUpdateManyWithoutSourceGroupNestedInput = {
  create?: Prisma.XOR<Prisma.AuthUserRoleCreateWithoutSourceGroupInput, Prisma.AuthUserRoleUncheckedCreateWithoutSourceGroupInput> | Prisma.AuthUserRoleCreateWithoutSourceGroupInput[] | Prisma.AuthUserRoleUncheckedCreateWithoutSourceGroupInput[]
  connectOrCreate?: Prisma.AuthUserRoleCreateOrConnectWithoutSourceGroupInput | Prisma.AuthUserRoleCreateOrConnectWithoutSourceGroupInput[]
  upsert?: Prisma.AuthUserRoleUpsertWithWhereUniqueWithoutSourceGroupInput | Prisma.AuthUserRoleUpsertWithWhereUniqueWithoutSourceGroupInput[]
  createMany?: Prisma.AuthUserRoleCreateManySourceGroupInputEnvelope
  set?: Prisma.AuthUserRoleWhereUniqueInput | Prisma.AuthUserRoleWhereUniqueInput[]
  disconnect?: Prisma.AuthUserRoleWhereUniqueInput | Prisma.AuthUserRoleWhereUniqueInput[]
  delete?: Prisma.AuthUserRoleWhereUniqueInput | Prisma.AuthUserRoleWhereUniqueInput[]
  connect?: Prisma.AuthUserRoleWhereUniqueInput | Prisma.AuthUserRoleWhereUniqueInput[]
  update?: Prisma.AuthUserRoleUpdateWithWhereUniqueWithoutSourceGroupInput | Prisma.AuthUserRoleUpdateWithWhereUniqueWithoutSourceGroupInput[]
  updateMany?: Prisma.AuthUserRoleUpdateManyWithWhereWithoutSourceGroupInput | Prisma.AuthUserRoleUpdateManyWithWhereWithoutSourceGroupInput[]
  deleteMany?: Prisma.AuthUserRoleScalarWhereInput | Prisma.AuthUserRoleScalarWhereInput[]
}

export type AuthUserRoleCreateWithoutRoleInput = {
  id?: string
  idpSub: string
  ownerId?: string | null
  entityId?: string | null
  entityType?: string | null
  grantedAt?: Date | string
  revokedAt?: Date | string | null
  grantedBy?: string | null
  revokedBy?: string | null
  note?: string | null
  sourceGroup?: Prisma.AuthRoleGroupCreateNestedOneWithoutUserRoleGroupsInput
}

export type AuthUserRoleUncheckedCreateWithoutRoleInput = {
  id?: string
  idpSub: string
  ownerId?: string | null
  entityId?: string | null
  entityType?: string | null
  sourceGroupId?: string | null
  grantedAt?: Date | string
  revokedAt?: Date | string | null
  grantedBy?: string | null
  revokedBy?: string | null
  note?: string | null
}

export type AuthUserRoleCreateOrConnectWithoutRoleInput = {
  where: Prisma.AuthUserRoleWhereUniqueInput
  create: Prisma.XOR<Prisma.AuthUserRoleCreateWithoutRoleInput, Prisma.AuthUserRoleUncheckedCreateWithoutRoleInput>
}

export type AuthUserRoleCreateManyRoleInputEnvelope = {
  data: Prisma.AuthUserRoleCreateManyRoleInput | Prisma.AuthUserRoleCreateManyRoleInput[]
  skipDuplicates?: boolean
}

export type AuthUserRoleUpsertWithWhereUniqueWithoutRoleInput = {
  where: Prisma.AuthUserRoleWhereUniqueInput
  update: Prisma.XOR<Prisma.AuthUserRoleUpdateWithoutRoleInput, Prisma.AuthUserRoleUncheckedUpdateWithoutRoleInput>
  create: Prisma.XOR<Prisma.AuthUserRoleCreateWithoutRoleInput, Prisma.AuthUserRoleUncheckedCreateWithoutRoleInput>
}

export type AuthUserRoleUpdateWithWhereUniqueWithoutRoleInput = {
  where: Prisma.AuthUserRoleWhereUniqueInput
  data: Prisma.XOR<Prisma.AuthUserRoleUpdateWithoutRoleInput, Prisma.AuthUserRoleUncheckedUpdateWithoutRoleInput>
}

export type AuthUserRoleUpdateManyWithWhereWithoutRoleInput = {
  where: Prisma.AuthUserRoleScalarWhereInput
  data: Prisma.XOR<Prisma.AuthUserRoleUpdateManyMutationInput, Prisma.AuthUserRoleUncheckedUpdateManyWithoutRoleInput>
}

export type AuthUserRoleScalarWhereInput = {
  AND?: Prisma.AuthUserRoleScalarWhereInput | Prisma.AuthUserRoleScalarWhereInput[]
  OR?: Prisma.AuthUserRoleScalarWhereInput[]
  NOT?: Prisma.AuthUserRoleScalarWhereInput | Prisma.AuthUserRoleScalarWhereInput[]
  id?: Prisma.StringFilter<"AuthUserRole"> | string
  idpSub?: Prisma.StringFilter<"AuthUserRole"> | string
  ownerId?: Prisma.StringNullableFilter<"AuthUserRole"> | string | null
  entityId?: Prisma.StringNullableFilter<"AuthUserRole"> | string | null
  entityType?: Prisma.StringNullableFilter<"AuthUserRole"> | string | null
  roleId?: Prisma.StringFilter<"AuthUserRole"> | string
  sourceGroupId?: Prisma.StringNullableFilter<"AuthUserRole"> | string | null
  grantedAt?: Prisma.DateTimeFilter<"AuthUserRole"> | Date | string
  revokedAt?: Prisma.DateTimeNullableFilter<"AuthUserRole"> | Date | string | null
  grantedBy?: Prisma.StringNullableFilter<"AuthUserRole"> | string | null
  revokedBy?: Prisma.StringNullableFilter<"AuthUserRole"> | string | null
  note?: Prisma.StringNullableFilter<"AuthUserRole"> | string | null
}

export type AuthUserRoleCreateWithoutSourceGroupInput = {
  id?: string
  idpSub: string
  ownerId?: string | null
  entityId?: string | null
  entityType?: string | null
  grantedAt?: Date | string
  revokedAt?: Date | string | null
  grantedBy?: string | null
  revokedBy?: string | null
  note?: string | null
  role: Prisma.AuthRoleCreateNestedOneWithoutUserRolesInput
}

export type AuthUserRoleUncheckedCreateWithoutSourceGroupInput = {
  id?: string
  idpSub: string
  ownerId?: string | null
  entityId?: string | null
  entityType?: string | null
  roleId: string
  grantedAt?: Date | string
  revokedAt?: Date | string | null
  grantedBy?: string | null
  revokedBy?: string | null
  note?: string | null
}

export type AuthUserRoleCreateOrConnectWithoutSourceGroupInput = {
  where: Prisma.AuthUserRoleWhereUniqueInput
  create: Prisma.XOR<Prisma.AuthUserRoleCreateWithoutSourceGroupInput, Prisma.AuthUserRoleUncheckedCreateWithoutSourceGroupInput>
}

export type AuthUserRoleCreateManySourceGroupInputEnvelope = {
  data: Prisma.AuthUserRoleCreateManySourceGroupInput | Prisma.AuthUserRoleCreateManySourceGroupInput[]
  skipDuplicates?: boolean
}

export type AuthUserRoleUpsertWithWhereUniqueWithoutSourceGroupInput = {
  where: Prisma.AuthUserRoleWhereUniqueInput
  update: Prisma.XOR<Prisma.AuthUserRoleUpdateWithoutSourceGroupInput, Prisma.AuthUserRoleUncheckedUpdateWithoutSourceGroupInput>
  create: Prisma.XOR<Prisma.AuthUserRoleCreateWithoutSourceGroupInput, Prisma.AuthUserRoleUncheckedCreateWithoutSourceGroupInput>
}

export type AuthUserRoleUpdateWithWhereUniqueWithoutSourceGroupInput = {
  where: Prisma.AuthUserRoleWhereUniqueInput
  data: Prisma.XOR<Prisma.AuthUserRoleUpdateWithoutSourceGroupInput, Prisma.AuthUserRoleUncheckedUpdateWithoutSourceGroupInput>
}

export type AuthUserRoleUpdateManyWithWhereWithoutSourceGroupInput = {
  where: Prisma.AuthUserRoleScalarWhereInput
  data: Prisma.XOR<Prisma.AuthUserRoleUpdateManyMutationInput, Prisma.AuthUserRoleUncheckedUpdateManyWithoutSourceGroupInput>
}

export type AuthUserRoleCreateManyRoleInput = {
  id?: string
  idpSub: string
  ownerId?: string | null
  entityId?: string | null
  entityType?: string | null
  sourceGroupId?: string | null
  grantedAt?: Date | string
  revokedAt?: Date | string | null
  grantedBy?: string | null
  revokedBy?: string | null
  note?: string | null
}

export type AuthUserRoleUpdateWithoutRoleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  idpSub?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  entityId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  entityType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  grantedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  revokedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  grantedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  revokedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sourceGroup?: Prisma.AuthRoleGroupUpdateOneWithoutUserRoleGroupsNestedInput
}

export type AuthUserRoleUncheckedUpdateWithoutRoleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  idpSub?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  entityId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  entityType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sourceGroupId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  grantedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  revokedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  grantedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  revokedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AuthUserRoleUncheckedUpdateManyWithoutRoleInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  idpSub?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  entityId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  entityType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sourceGroupId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  grantedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  revokedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  grantedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  revokedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AuthUserRoleCreateManySourceGroupInput = {
  id?: string
  idpSub: string
  ownerId?: string | null
  entityId?: string | null
  entityType?: string | null
  roleId: string
  grantedAt?: Date | string
  revokedAt?: Date | string | null
  grantedBy?: string | null
  revokedBy?: string | null
  note?: string | null
}

export type AuthUserRoleUpdateWithoutSourceGroupInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  idpSub?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  entityId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  entityType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  grantedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  revokedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  grantedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  revokedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  role?: Prisma.AuthRoleUpdateOneRequiredWithoutUserRolesNestedInput
}

export type AuthUserRoleUncheckedUpdateWithoutSourceGroupInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  idpSub?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  entityId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  entityType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  grantedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  revokedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  grantedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  revokedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type AuthUserRoleUncheckedUpdateManyWithoutSourceGroupInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  idpSub?: Prisma.StringFieldUpdateOperationsInput | string
  ownerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  entityId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  entityType?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  roleId?: Prisma.StringFieldUpdateOperationsInput | string
  grantedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  revokedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  grantedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  revokedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  note?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type AuthUserRoleSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  idpSub?: boolean
  ownerId?: boolean
  entityId?: boolean
  entityType?: boolean
  roleId?: boolean
  sourceGroupId?: boolean
  grantedAt?: boolean
  revokedAt?: boolean
  grantedBy?: boolean
  revokedBy?: boolean
  note?: boolean
  role?: boolean | Prisma.AuthRoleDefaultArgs<ExtArgs>
  sourceGroup?: boolean | Prisma.AuthUserRole$sourceGroupArgs<ExtArgs>
}, ExtArgs["result"]["authUserRole"]>

export type AuthUserRoleSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  idpSub?: boolean
  ownerId?: boolean
  entityId?: boolean
  entityType?: boolean
  roleId?: boolean
  sourceGroupId?: boolean
  grantedAt?: boolean
  revokedAt?: boolean
  grantedBy?: boolean
  revokedBy?: boolean
  note?: boolean
  role?: boolean | Prisma.AuthRoleDefaultArgs<ExtArgs>
  sourceGroup?: boolean | Prisma.AuthUserRole$sourceGroupArgs<ExtArgs>
}, ExtArgs["result"]["authUserRole"]>

export type AuthUserRoleSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  idpSub?: boolean
  ownerId?: boolean
  entityId?: boolean
  entityType?: boolean
  roleId?: boolean
  sourceGroupId?: boolean
  grantedAt?: boolean
  revokedAt?: boolean
  grantedBy?: boolean
  revokedBy?: boolean
  note?: boolean
  role?: boolean | Prisma.AuthRoleDefaultArgs<ExtArgs>
  sourceGroup?: boolean | Prisma.AuthUserRole$sourceGroupArgs<ExtArgs>
}, ExtArgs["result"]["authUserRole"]>

export type AuthUserRoleSelectScalar = {
  id?: boolean
  idpSub?: boolean
  ownerId?: boolean
  entityId?: boolean
  entityType?: boolean
  roleId?: boolean
  sourceGroupId?: boolean
  grantedAt?: boolean
  revokedAt?: boolean
  grantedBy?: boolean
  revokedBy?: boolean
  note?: boolean
}

export type AuthUserRoleOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "idpSub" | "ownerId" | "entityId" | "entityType" | "roleId" | "sourceGroupId" | "grantedAt" | "revokedAt" | "grantedBy" | "revokedBy" | "note", ExtArgs["result"]["authUserRole"]>
export type AuthUserRoleInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  role?: boolean | Prisma.AuthRoleDefaultArgs<ExtArgs>
  sourceGroup?: boolean | Prisma.AuthUserRole$sourceGroupArgs<ExtArgs>
}
export type AuthUserRoleIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  role?: boolean | Prisma.AuthRoleDefaultArgs<ExtArgs>
  sourceGroup?: boolean | Prisma.AuthUserRole$sourceGroupArgs<ExtArgs>
}
export type AuthUserRoleIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  role?: boolean | Prisma.AuthRoleDefaultArgs<ExtArgs>
  sourceGroup?: boolean | Prisma.AuthUserRole$sourceGroupArgs<ExtArgs>
}

export type $AuthUserRolePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AuthUserRole"
  objects: {
    role: Prisma.$AuthRolePayload<ExtArgs>
    sourceGroup: Prisma.$AuthRoleGroupPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    idpSub: string
    ownerId: string | null
    entityId: string | null
    entityType: string | null
    roleId: string
    sourceGroupId: string | null
    grantedAt: Date
    revokedAt: Date | null
    grantedBy: string | null
    revokedBy: string | null
    note: string | null
  }, ExtArgs["result"]["authUserRole"]>
  composites: {}
}

export type AuthUserRoleGetPayload<S extends boolean | null | undefined | AuthUserRoleDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AuthUserRolePayload, S>

export type AuthUserRoleCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AuthUserRoleFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AuthUserRoleCountAggregateInputType | true
  }

export interface AuthUserRoleDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AuthUserRole'], meta: { name: 'AuthUserRole' } }
  /**
   * Find zero or one AuthUserRole that matches the filter.
   * @param {AuthUserRoleFindUniqueArgs} args - Arguments to find a AuthUserRole
   * @example
   * // Get one AuthUserRole
   * const authUserRole = await prisma.authUserRole.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AuthUserRoleFindUniqueArgs>(args: Prisma.SelectSubset<T, AuthUserRoleFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AuthUserRoleClient<runtime.Types.Result.GetResult<Prisma.$AuthUserRolePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AuthUserRole that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AuthUserRoleFindUniqueOrThrowArgs} args - Arguments to find a AuthUserRole
   * @example
   * // Get one AuthUserRole
   * const authUserRole = await prisma.authUserRole.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AuthUserRoleFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AuthUserRoleFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AuthUserRoleClient<runtime.Types.Result.GetResult<Prisma.$AuthUserRolePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AuthUserRole that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthUserRoleFindFirstArgs} args - Arguments to find a AuthUserRole
   * @example
   * // Get one AuthUserRole
   * const authUserRole = await prisma.authUserRole.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AuthUserRoleFindFirstArgs>(args?: Prisma.SelectSubset<T, AuthUserRoleFindFirstArgs<ExtArgs>>): Prisma.Prisma__AuthUserRoleClient<runtime.Types.Result.GetResult<Prisma.$AuthUserRolePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AuthUserRole that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthUserRoleFindFirstOrThrowArgs} args - Arguments to find a AuthUserRole
   * @example
   * // Get one AuthUserRole
   * const authUserRole = await prisma.authUserRole.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AuthUserRoleFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AuthUserRoleFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AuthUserRoleClient<runtime.Types.Result.GetResult<Prisma.$AuthUserRolePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AuthUserRoles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthUserRoleFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AuthUserRoles
   * const authUserRoles = await prisma.authUserRole.findMany()
   * 
   * // Get first 10 AuthUserRoles
   * const authUserRoles = await prisma.authUserRole.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const authUserRoleWithIdOnly = await prisma.authUserRole.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AuthUserRoleFindManyArgs>(args?: Prisma.SelectSubset<T, AuthUserRoleFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuthUserRolePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AuthUserRole.
   * @param {AuthUserRoleCreateArgs} args - Arguments to create a AuthUserRole.
   * @example
   * // Create one AuthUserRole
   * const AuthUserRole = await prisma.authUserRole.create({
   *   data: {
   *     // ... data to create a AuthUserRole
   *   }
   * })
   * 
   */
  create<T extends AuthUserRoleCreateArgs>(args: Prisma.SelectSubset<T, AuthUserRoleCreateArgs<ExtArgs>>): Prisma.Prisma__AuthUserRoleClient<runtime.Types.Result.GetResult<Prisma.$AuthUserRolePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AuthUserRoles.
   * @param {AuthUserRoleCreateManyArgs} args - Arguments to create many AuthUserRoles.
   * @example
   * // Create many AuthUserRoles
   * const authUserRole = await prisma.authUserRole.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AuthUserRoleCreateManyArgs>(args?: Prisma.SelectSubset<T, AuthUserRoleCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AuthUserRoles and returns the data saved in the database.
   * @param {AuthUserRoleCreateManyAndReturnArgs} args - Arguments to create many AuthUserRoles.
   * @example
   * // Create many AuthUserRoles
   * const authUserRole = await prisma.authUserRole.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AuthUserRoles and only return the `id`
   * const authUserRoleWithIdOnly = await prisma.authUserRole.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AuthUserRoleCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AuthUserRoleCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuthUserRolePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AuthUserRole.
   * @param {AuthUserRoleDeleteArgs} args - Arguments to delete one AuthUserRole.
   * @example
   * // Delete one AuthUserRole
   * const AuthUserRole = await prisma.authUserRole.delete({
   *   where: {
   *     // ... filter to delete one AuthUserRole
   *   }
   * })
   * 
   */
  delete<T extends AuthUserRoleDeleteArgs>(args: Prisma.SelectSubset<T, AuthUserRoleDeleteArgs<ExtArgs>>): Prisma.Prisma__AuthUserRoleClient<runtime.Types.Result.GetResult<Prisma.$AuthUserRolePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AuthUserRole.
   * @param {AuthUserRoleUpdateArgs} args - Arguments to update one AuthUserRole.
   * @example
   * // Update one AuthUserRole
   * const authUserRole = await prisma.authUserRole.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AuthUserRoleUpdateArgs>(args: Prisma.SelectSubset<T, AuthUserRoleUpdateArgs<ExtArgs>>): Prisma.Prisma__AuthUserRoleClient<runtime.Types.Result.GetResult<Prisma.$AuthUserRolePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AuthUserRoles.
   * @param {AuthUserRoleDeleteManyArgs} args - Arguments to filter AuthUserRoles to delete.
   * @example
   * // Delete a few AuthUserRoles
   * const { count } = await prisma.authUserRole.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AuthUserRoleDeleteManyArgs>(args?: Prisma.SelectSubset<T, AuthUserRoleDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AuthUserRoles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthUserRoleUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AuthUserRoles
   * const authUserRole = await prisma.authUserRole.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AuthUserRoleUpdateManyArgs>(args: Prisma.SelectSubset<T, AuthUserRoleUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AuthUserRoles and returns the data updated in the database.
   * @param {AuthUserRoleUpdateManyAndReturnArgs} args - Arguments to update many AuthUserRoles.
   * @example
   * // Update many AuthUserRoles
   * const authUserRole = await prisma.authUserRole.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AuthUserRoles and only return the `id`
   * const authUserRoleWithIdOnly = await prisma.authUserRole.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AuthUserRoleUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AuthUserRoleUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuthUserRolePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AuthUserRole.
   * @param {AuthUserRoleUpsertArgs} args - Arguments to update or create a AuthUserRole.
   * @example
   * // Update or create a AuthUserRole
   * const authUserRole = await prisma.authUserRole.upsert({
   *   create: {
   *     // ... data to create a AuthUserRole
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AuthUserRole we want to update
   *   }
   * })
   */
  upsert<T extends AuthUserRoleUpsertArgs>(args: Prisma.SelectSubset<T, AuthUserRoleUpsertArgs<ExtArgs>>): Prisma.Prisma__AuthUserRoleClient<runtime.Types.Result.GetResult<Prisma.$AuthUserRolePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AuthUserRoles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthUserRoleCountArgs} args - Arguments to filter AuthUserRoles to count.
   * @example
   * // Count the number of AuthUserRoles
   * const count = await prisma.authUserRole.count({
   *   where: {
   *     // ... the filter for the AuthUserRoles we want to count
   *   }
   * })
  **/
  count<T extends AuthUserRoleCountArgs>(
    args?: Prisma.Subset<T, AuthUserRoleCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AuthUserRoleCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AuthUserRole.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthUserRoleAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AuthUserRoleAggregateArgs>(args: Prisma.Subset<T, AuthUserRoleAggregateArgs>): Prisma.PrismaPromise<GetAuthUserRoleAggregateType<T>>

  /**
   * Group by AuthUserRole.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthUserRoleGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AuthUserRoleGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AuthUserRoleGroupByArgs['orderBy'] }
      : { orderBy?: AuthUserRoleGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AuthUserRoleGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAuthUserRoleGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AuthUserRole model
 */
readonly fields: AuthUserRoleFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AuthUserRole.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AuthUserRoleClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  role<T extends Prisma.AuthRoleDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AuthRoleDefaultArgs<ExtArgs>>): Prisma.Prisma__AuthRoleClient<runtime.Types.Result.GetResult<Prisma.$AuthRolePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  sourceGroup<T extends Prisma.AuthUserRole$sourceGroupArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AuthUserRole$sourceGroupArgs<ExtArgs>>): Prisma.Prisma__AuthRoleGroupClient<runtime.Types.Result.GetResult<Prisma.$AuthRoleGroupPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AuthUserRole model
 */
export interface AuthUserRoleFieldRefs {
  readonly id: Prisma.FieldRef<"AuthUserRole", 'String'>
  readonly idpSub: Prisma.FieldRef<"AuthUserRole", 'String'>
  readonly ownerId: Prisma.FieldRef<"AuthUserRole", 'String'>
  readonly entityId: Prisma.FieldRef<"AuthUserRole", 'String'>
  readonly entityType: Prisma.FieldRef<"AuthUserRole", 'String'>
  readonly roleId: Prisma.FieldRef<"AuthUserRole", 'String'>
  readonly sourceGroupId: Prisma.FieldRef<"AuthUserRole", 'String'>
  readonly grantedAt: Prisma.FieldRef<"AuthUserRole", 'DateTime'>
  readonly revokedAt: Prisma.FieldRef<"AuthUserRole", 'DateTime'>
  readonly grantedBy: Prisma.FieldRef<"AuthUserRole", 'String'>
  readonly revokedBy: Prisma.FieldRef<"AuthUserRole", 'String'>
  readonly note: Prisma.FieldRef<"AuthUserRole", 'String'>
}
    

// Custom InputTypes
/**
 * AuthUserRole findUnique
 */
export type AuthUserRoleFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthUserRole
   */
  select?: Prisma.AuthUserRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthUserRole
   */
  omit?: Prisma.AuthUserRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthUserRoleInclude<ExtArgs> | null
  /**
   * Filter, which AuthUserRole to fetch.
   */
  where: Prisma.AuthUserRoleWhereUniqueInput
}

/**
 * AuthUserRole findUniqueOrThrow
 */
export type AuthUserRoleFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthUserRole
   */
  select?: Prisma.AuthUserRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthUserRole
   */
  omit?: Prisma.AuthUserRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthUserRoleInclude<ExtArgs> | null
  /**
   * Filter, which AuthUserRole to fetch.
   */
  where: Prisma.AuthUserRoleWhereUniqueInput
}

/**
 * AuthUserRole findFirst
 */
export type AuthUserRoleFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthUserRole
   */
  select?: Prisma.AuthUserRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthUserRole
   */
  omit?: Prisma.AuthUserRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthUserRoleInclude<ExtArgs> | null
  /**
   * Filter, which AuthUserRole to fetch.
   */
  where?: Prisma.AuthUserRoleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuthUserRoles to fetch.
   */
  orderBy?: Prisma.AuthUserRoleOrderByWithRelationInput | Prisma.AuthUserRoleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AuthUserRoles.
   */
  cursor?: Prisma.AuthUserRoleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuthUserRoles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuthUserRoles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AuthUserRoles.
   */
  distinct?: Prisma.AuthUserRoleScalarFieldEnum | Prisma.AuthUserRoleScalarFieldEnum[]
}

/**
 * AuthUserRole findFirstOrThrow
 */
export type AuthUserRoleFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthUserRole
   */
  select?: Prisma.AuthUserRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthUserRole
   */
  omit?: Prisma.AuthUserRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthUserRoleInclude<ExtArgs> | null
  /**
   * Filter, which AuthUserRole to fetch.
   */
  where?: Prisma.AuthUserRoleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuthUserRoles to fetch.
   */
  orderBy?: Prisma.AuthUserRoleOrderByWithRelationInput | Prisma.AuthUserRoleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AuthUserRoles.
   */
  cursor?: Prisma.AuthUserRoleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuthUserRoles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuthUserRoles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AuthUserRoles.
   */
  distinct?: Prisma.AuthUserRoleScalarFieldEnum | Prisma.AuthUserRoleScalarFieldEnum[]
}

/**
 * AuthUserRole findMany
 */
export type AuthUserRoleFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthUserRole
   */
  select?: Prisma.AuthUserRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthUserRole
   */
  omit?: Prisma.AuthUserRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthUserRoleInclude<ExtArgs> | null
  /**
   * Filter, which AuthUserRoles to fetch.
   */
  where?: Prisma.AuthUserRoleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuthUserRoles to fetch.
   */
  orderBy?: Prisma.AuthUserRoleOrderByWithRelationInput | Prisma.AuthUserRoleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AuthUserRoles.
   */
  cursor?: Prisma.AuthUserRoleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuthUserRoles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuthUserRoles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AuthUserRoles.
   */
  distinct?: Prisma.AuthUserRoleScalarFieldEnum | Prisma.AuthUserRoleScalarFieldEnum[]
}

/**
 * AuthUserRole create
 */
export type AuthUserRoleCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthUserRole
   */
  select?: Prisma.AuthUserRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthUserRole
   */
  omit?: Prisma.AuthUserRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthUserRoleInclude<ExtArgs> | null
  /**
   * The data needed to create a AuthUserRole.
   */
  data: Prisma.XOR<Prisma.AuthUserRoleCreateInput, Prisma.AuthUserRoleUncheckedCreateInput>
}

/**
 * AuthUserRole createMany
 */
export type AuthUserRoleCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AuthUserRoles.
   */
  data: Prisma.AuthUserRoleCreateManyInput | Prisma.AuthUserRoleCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AuthUserRole createManyAndReturn
 */
export type AuthUserRoleCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthUserRole
   */
  select?: Prisma.AuthUserRoleSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AuthUserRole
   */
  omit?: Prisma.AuthUserRoleOmit<ExtArgs> | null
  /**
   * The data used to create many AuthUserRoles.
   */
  data: Prisma.AuthUserRoleCreateManyInput | Prisma.AuthUserRoleCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthUserRoleIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AuthUserRole update
 */
export type AuthUserRoleUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthUserRole
   */
  select?: Prisma.AuthUserRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthUserRole
   */
  omit?: Prisma.AuthUserRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthUserRoleInclude<ExtArgs> | null
  /**
   * The data needed to update a AuthUserRole.
   */
  data: Prisma.XOR<Prisma.AuthUserRoleUpdateInput, Prisma.AuthUserRoleUncheckedUpdateInput>
  /**
   * Choose, which AuthUserRole to update.
   */
  where: Prisma.AuthUserRoleWhereUniqueInput
}

/**
 * AuthUserRole updateMany
 */
export type AuthUserRoleUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AuthUserRoles.
   */
  data: Prisma.XOR<Prisma.AuthUserRoleUpdateManyMutationInput, Prisma.AuthUserRoleUncheckedUpdateManyInput>
  /**
   * Filter which AuthUserRoles to update
   */
  where?: Prisma.AuthUserRoleWhereInput
  /**
   * Limit how many AuthUserRoles to update.
   */
  limit?: number
}

/**
 * AuthUserRole updateManyAndReturn
 */
export type AuthUserRoleUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthUserRole
   */
  select?: Prisma.AuthUserRoleSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AuthUserRole
   */
  omit?: Prisma.AuthUserRoleOmit<ExtArgs> | null
  /**
   * The data used to update AuthUserRoles.
   */
  data: Prisma.XOR<Prisma.AuthUserRoleUpdateManyMutationInput, Prisma.AuthUserRoleUncheckedUpdateManyInput>
  /**
   * Filter which AuthUserRoles to update
   */
  where?: Prisma.AuthUserRoleWhereInput
  /**
   * Limit how many AuthUserRoles to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthUserRoleIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AuthUserRole upsert
 */
export type AuthUserRoleUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthUserRole
   */
  select?: Prisma.AuthUserRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthUserRole
   */
  omit?: Prisma.AuthUserRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthUserRoleInclude<ExtArgs> | null
  /**
   * The filter to search for the AuthUserRole to update in case it exists.
   */
  where: Prisma.AuthUserRoleWhereUniqueInput
  /**
   * In case the AuthUserRole found by the `where` argument doesn't exist, create a new AuthUserRole with this data.
   */
  create: Prisma.XOR<Prisma.AuthUserRoleCreateInput, Prisma.AuthUserRoleUncheckedCreateInput>
  /**
   * In case the AuthUserRole was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AuthUserRoleUpdateInput, Prisma.AuthUserRoleUncheckedUpdateInput>
}

/**
 * AuthUserRole delete
 */
export type AuthUserRoleDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthUserRole
   */
  select?: Prisma.AuthUserRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthUserRole
   */
  omit?: Prisma.AuthUserRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthUserRoleInclude<ExtArgs> | null
  /**
   * Filter which AuthUserRole to delete.
   */
  where: Prisma.AuthUserRoleWhereUniqueInput
}

/**
 * AuthUserRole deleteMany
 */
export type AuthUserRoleDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AuthUserRoles to delete
   */
  where?: Prisma.AuthUserRoleWhereInput
  /**
   * Limit how many AuthUserRoles to delete.
   */
  limit?: number
}

/**
 * AuthUserRole.sourceGroup
 */
export type AuthUserRole$sourceGroupArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthRoleGroup
   */
  select?: Prisma.AuthRoleGroupSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthRoleGroup
   */
  omit?: Prisma.AuthRoleGroupOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthRoleGroupInclude<ExtArgs> | null
  where?: Prisma.AuthRoleGroupWhereInput
}

/**
 * AuthUserRole without action
 */
export type AuthUserRoleDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthUserRole
   */
  select?: Prisma.AuthUserRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthUserRole
   */
  omit?: Prisma.AuthUserRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthUserRoleInclude<ExtArgs> | null
}
