
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AuthRole` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model AuthRole
 * 
 */
export type AuthRoleModel = runtime.Types.Result.DefaultSelection<Prisma.$AuthRolePayload>

export type AggregateAuthRole = {
  _count: AuthRoleCountAggregateOutputType | null
  _min: AuthRoleMinAggregateOutputType | null
  _max: AuthRoleMaxAggregateOutputType | null
}

export type AuthRoleMinAggregateOutputType = {
  id: string | null
  key: string | null
  description: string | null
  deletedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AuthRoleMaxAggregateOutputType = {
  id: string | null
  key: string | null
  description: string | null
  deletedAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AuthRoleCountAggregateOutputType = {
  id: number
  key: number
  description: number
  deletedAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AuthRoleMinAggregateInputType = {
  id?: true
  key?: true
  description?: true
  deletedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type AuthRoleMaxAggregateInputType = {
  id?: true
  key?: true
  description?: true
  deletedAt?: true
  createdAt?: true
  updatedAt?: true
}

export type AuthRoleCountAggregateInputType = {
  id?: true
  key?: true
  description?: true
  deletedAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AuthRoleAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AuthRole to aggregate.
   */
  where?: Prisma.AuthRoleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuthRoles to fetch.
   */
  orderBy?: Prisma.AuthRoleOrderByWithRelationInput | Prisma.AuthRoleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AuthRoleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuthRoles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuthRoles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AuthRoles
  **/
  _count?: true | AuthRoleCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AuthRoleMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AuthRoleMaxAggregateInputType
}

export type GetAuthRoleAggregateType<T extends AuthRoleAggregateArgs> = {
      [P in keyof T & keyof AggregateAuthRole]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAuthRole[P]>
    : Prisma.GetScalarType<T[P], AggregateAuthRole[P]>
}




export type AuthRoleGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AuthRoleWhereInput
  orderBy?: Prisma.AuthRoleOrderByWithAggregationInput | Prisma.AuthRoleOrderByWithAggregationInput[]
  by: Prisma.AuthRoleScalarFieldEnum[] | Prisma.AuthRoleScalarFieldEnum
  having?: Prisma.AuthRoleScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AuthRoleCountAggregateInputType | true
  _min?: AuthRoleMinAggregateInputType
  _max?: AuthRoleMaxAggregateInputType
}

export type AuthRoleGroupByOutputType = {
  id: string
  key: string
  description: string | null
  deletedAt: Date | null
  createdAt: Date
  updatedAt: Date
  _count: AuthRoleCountAggregateOutputType | null
  _min: AuthRoleMinAggregateOutputType | null
  _max: AuthRoleMaxAggregateOutputType | null
}

export type GetAuthRoleGroupByPayload<T extends AuthRoleGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AuthRoleGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AuthRoleGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AuthRoleGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AuthRoleGroupByOutputType[P]>
      }
    >
  >



export type AuthRoleWhereInput = {
  AND?: Prisma.AuthRoleWhereInput | Prisma.AuthRoleWhereInput[]
  OR?: Prisma.AuthRoleWhereInput[]
  NOT?: Prisma.AuthRoleWhereInput | Prisma.AuthRoleWhereInput[]
  id?: Prisma.StringFilter<"AuthRole"> | string
  key?: Prisma.StringFilter<"AuthRole"> | string
  description?: Prisma.StringNullableFilter<"AuthRole"> | string | null
  deletedAt?: Prisma.DateTimeNullableFilter<"AuthRole"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"AuthRole"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AuthRole"> | Date | string
  permissions?: Prisma.AuthRolePermissionListRelationFilter
  userRoles?: Prisma.AuthUserRoleListRelationFilter
  roleGroupRoles?: Prisma.AuthRoleGroupRoleListRelationFilter
}

export type AuthRoleOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  permissions?: Prisma.AuthRolePermissionOrderByRelationAggregateInput
  userRoles?: Prisma.AuthUserRoleOrderByRelationAggregateInput
  roleGroupRoles?: Prisma.AuthRoleGroupRoleOrderByRelationAggregateInput
}

export type AuthRoleWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  key?: string
  AND?: Prisma.AuthRoleWhereInput | Prisma.AuthRoleWhereInput[]
  OR?: Prisma.AuthRoleWhereInput[]
  NOT?: Prisma.AuthRoleWhereInput | Prisma.AuthRoleWhereInput[]
  description?: Prisma.StringNullableFilter<"AuthRole"> | string | null
  deletedAt?: Prisma.DateTimeNullableFilter<"AuthRole"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"AuthRole"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"AuthRole"> | Date | string
  permissions?: Prisma.AuthRolePermissionListRelationFilter
  userRoles?: Prisma.AuthUserRoleListRelationFilter
  roleGroupRoles?: Prisma.AuthRoleGroupRoleListRelationFilter
}, "id" | "key">

export type AuthRoleOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AuthRoleCountOrderByAggregateInput
  _max?: Prisma.AuthRoleMaxOrderByAggregateInput
  _min?: Prisma.AuthRoleMinOrderByAggregateInput
}

export type AuthRoleScalarWhereWithAggregatesInput = {
  AND?: Prisma.AuthRoleScalarWhereWithAggregatesInput | Prisma.AuthRoleScalarWhereWithAggregatesInput[]
  OR?: Prisma.AuthRoleScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AuthRoleScalarWhereWithAggregatesInput | Prisma.AuthRoleScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AuthRole"> | string
  key?: Prisma.StringWithAggregatesFilter<"AuthRole"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"AuthRole"> | string | null
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"AuthRole"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AuthRole"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"AuthRole"> | Date | string
}

export type AuthRoleCreateInput = {
  id?: string
  key: string
  description?: string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  permissions?: Prisma.AuthRolePermissionCreateNestedManyWithoutRoleInput
  userRoles?: Prisma.AuthUserRoleCreateNestedManyWithoutRoleInput
  roleGroupRoles?: Prisma.AuthRoleGroupRoleCreateNestedManyWithoutRoleInput
}

export type AuthRoleUncheckedCreateInput = {
  id?: string
  key: string
  description?: string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  permissions?: Prisma.AuthRolePermissionUncheckedCreateNestedManyWithoutRoleInput
  userRoles?: Prisma.AuthUserRoleUncheckedCreateNestedManyWithoutRoleInput
  roleGroupRoles?: Prisma.AuthRoleGroupRoleUncheckedCreateNestedManyWithoutRoleInput
}

export type AuthRoleUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  permissions?: Prisma.AuthRolePermissionUpdateManyWithoutRoleNestedInput
  userRoles?: Prisma.AuthUserRoleUpdateManyWithoutRoleNestedInput
  roleGroupRoles?: Prisma.AuthRoleGroupRoleUpdateManyWithoutRoleNestedInput
}

export type AuthRoleUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  permissions?: Prisma.AuthRolePermissionUncheckedUpdateManyWithoutRoleNestedInput
  userRoles?: Prisma.AuthUserRoleUncheckedUpdateManyWithoutRoleNestedInput
  roleGroupRoles?: Prisma.AuthRoleGroupRoleUncheckedUpdateManyWithoutRoleNestedInput
}

export type AuthRoleCreateManyInput = {
  id?: string
  key: string
  description?: string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AuthRoleUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuthRoleUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuthRoleCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  description?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AuthRoleMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  description?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AuthRoleMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  description?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AuthRoleScalarRelationFilter = {
  is?: Prisma.AuthRoleWhereInput
  isNot?: Prisma.AuthRoleWhereInput
}

export type AuthRoleCreateNestedOneWithoutPermissionsInput = {
  create?: Prisma.XOR<Prisma.AuthRoleCreateWithoutPermissionsInput, Prisma.AuthRoleUncheckedCreateWithoutPermissionsInput>
  connectOrCreate?: Prisma.AuthRoleCreateOrConnectWithoutPermissionsInput
  connect?: Prisma.AuthRoleWhereUniqueInput
}

export type AuthRoleUpdateOneRequiredWithoutPermissionsNestedInput = {
  create?: Prisma.XOR<Prisma.AuthRoleCreateWithoutPermissionsInput, Prisma.AuthRoleUncheckedCreateWithoutPermissionsInput>
  connectOrCreate?: Prisma.AuthRoleCreateOrConnectWithoutPermissionsInput
  upsert?: Prisma.AuthRoleUpsertWithoutPermissionsInput
  connect?: Prisma.AuthRoleWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AuthRoleUpdateToOneWithWhereWithoutPermissionsInput, Prisma.AuthRoleUpdateWithoutPermissionsInput>, Prisma.AuthRoleUncheckedUpdateWithoutPermissionsInput>
}

export type AuthRoleCreateNestedOneWithoutRoleGroupRolesInput = {
  create?: Prisma.XOR<Prisma.AuthRoleCreateWithoutRoleGroupRolesInput, Prisma.AuthRoleUncheckedCreateWithoutRoleGroupRolesInput>
  connectOrCreate?: Prisma.AuthRoleCreateOrConnectWithoutRoleGroupRolesInput
  connect?: Prisma.AuthRoleWhereUniqueInput
}

export type AuthRoleUpdateOneRequiredWithoutRoleGroupRolesNestedInput = {
  create?: Prisma.XOR<Prisma.AuthRoleCreateWithoutRoleGroupRolesInput, Prisma.AuthRoleUncheckedCreateWithoutRoleGroupRolesInput>
  connectOrCreate?: Prisma.AuthRoleCreateOrConnectWithoutRoleGroupRolesInput
  upsert?: Prisma.AuthRoleUpsertWithoutRoleGroupRolesInput
  connect?: Prisma.AuthRoleWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AuthRoleUpdateToOneWithWhereWithoutRoleGroupRolesInput, Prisma.AuthRoleUpdateWithoutRoleGroupRolesInput>, Prisma.AuthRoleUncheckedUpdateWithoutRoleGroupRolesInput>
}

export type AuthRoleCreateNestedOneWithoutUserRolesInput = {
  create?: Prisma.XOR<Prisma.AuthRoleCreateWithoutUserRolesInput, Prisma.AuthRoleUncheckedCreateWithoutUserRolesInput>
  connectOrCreate?: Prisma.AuthRoleCreateOrConnectWithoutUserRolesInput
  connect?: Prisma.AuthRoleWhereUniqueInput
}

export type AuthRoleUpdateOneRequiredWithoutUserRolesNestedInput = {
  create?: Prisma.XOR<Prisma.AuthRoleCreateWithoutUserRolesInput, Prisma.AuthRoleUncheckedCreateWithoutUserRolesInput>
  connectOrCreate?: Prisma.AuthRoleCreateOrConnectWithoutUserRolesInput
  upsert?: Prisma.AuthRoleUpsertWithoutUserRolesInput
  connect?: Prisma.AuthRoleWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AuthRoleUpdateToOneWithWhereWithoutUserRolesInput, Prisma.AuthRoleUpdateWithoutUserRolesInput>, Prisma.AuthRoleUncheckedUpdateWithoutUserRolesInput>
}

export type AuthRoleCreateWithoutPermissionsInput = {
  id?: string
  key: string
  description?: string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  userRoles?: Prisma.AuthUserRoleCreateNestedManyWithoutRoleInput
  roleGroupRoles?: Prisma.AuthRoleGroupRoleCreateNestedManyWithoutRoleInput
}

export type AuthRoleUncheckedCreateWithoutPermissionsInput = {
  id?: string
  key: string
  description?: string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  userRoles?: Prisma.AuthUserRoleUncheckedCreateNestedManyWithoutRoleInput
  roleGroupRoles?: Prisma.AuthRoleGroupRoleUncheckedCreateNestedManyWithoutRoleInput
}

export type AuthRoleCreateOrConnectWithoutPermissionsInput = {
  where: Prisma.AuthRoleWhereUniqueInput
  create: Prisma.XOR<Prisma.AuthRoleCreateWithoutPermissionsInput, Prisma.AuthRoleUncheckedCreateWithoutPermissionsInput>
}

export type AuthRoleUpsertWithoutPermissionsInput = {
  update: Prisma.XOR<Prisma.AuthRoleUpdateWithoutPermissionsInput, Prisma.AuthRoleUncheckedUpdateWithoutPermissionsInput>
  create: Prisma.XOR<Prisma.AuthRoleCreateWithoutPermissionsInput, Prisma.AuthRoleUncheckedCreateWithoutPermissionsInput>
  where?: Prisma.AuthRoleWhereInput
}

export type AuthRoleUpdateToOneWithWhereWithoutPermissionsInput = {
  where?: Prisma.AuthRoleWhereInput
  data: Prisma.XOR<Prisma.AuthRoleUpdateWithoutPermissionsInput, Prisma.AuthRoleUncheckedUpdateWithoutPermissionsInput>
}

export type AuthRoleUpdateWithoutPermissionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userRoles?: Prisma.AuthUserRoleUpdateManyWithoutRoleNestedInput
  roleGroupRoles?: Prisma.AuthRoleGroupRoleUpdateManyWithoutRoleNestedInput
}

export type AuthRoleUncheckedUpdateWithoutPermissionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userRoles?: Prisma.AuthUserRoleUncheckedUpdateManyWithoutRoleNestedInput
  roleGroupRoles?: Prisma.AuthRoleGroupRoleUncheckedUpdateManyWithoutRoleNestedInput
}

export type AuthRoleCreateWithoutRoleGroupRolesInput = {
  id?: string
  key: string
  description?: string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  permissions?: Prisma.AuthRolePermissionCreateNestedManyWithoutRoleInput
  userRoles?: Prisma.AuthUserRoleCreateNestedManyWithoutRoleInput
}

export type AuthRoleUncheckedCreateWithoutRoleGroupRolesInput = {
  id?: string
  key: string
  description?: string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  permissions?: Prisma.AuthRolePermissionUncheckedCreateNestedManyWithoutRoleInput
  userRoles?: Prisma.AuthUserRoleUncheckedCreateNestedManyWithoutRoleInput
}

export type AuthRoleCreateOrConnectWithoutRoleGroupRolesInput = {
  where: Prisma.AuthRoleWhereUniqueInput
  create: Prisma.XOR<Prisma.AuthRoleCreateWithoutRoleGroupRolesInput, Prisma.AuthRoleUncheckedCreateWithoutRoleGroupRolesInput>
}

export type AuthRoleUpsertWithoutRoleGroupRolesInput = {
  update: Prisma.XOR<Prisma.AuthRoleUpdateWithoutRoleGroupRolesInput, Prisma.AuthRoleUncheckedUpdateWithoutRoleGroupRolesInput>
  create: Prisma.XOR<Prisma.AuthRoleCreateWithoutRoleGroupRolesInput, Prisma.AuthRoleUncheckedCreateWithoutRoleGroupRolesInput>
  where?: Prisma.AuthRoleWhereInput
}

export type AuthRoleUpdateToOneWithWhereWithoutRoleGroupRolesInput = {
  where?: Prisma.AuthRoleWhereInput
  data: Prisma.XOR<Prisma.AuthRoleUpdateWithoutRoleGroupRolesInput, Prisma.AuthRoleUncheckedUpdateWithoutRoleGroupRolesInput>
}

export type AuthRoleUpdateWithoutRoleGroupRolesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  permissions?: Prisma.AuthRolePermissionUpdateManyWithoutRoleNestedInput
  userRoles?: Prisma.AuthUserRoleUpdateManyWithoutRoleNestedInput
}

export type AuthRoleUncheckedUpdateWithoutRoleGroupRolesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  permissions?: Prisma.AuthRolePermissionUncheckedUpdateManyWithoutRoleNestedInput
  userRoles?: Prisma.AuthUserRoleUncheckedUpdateManyWithoutRoleNestedInput
}

export type AuthRoleCreateWithoutUserRolesInput = {
  id?: string
  key: string
  description?: string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  permissions?: Prisma.AuthRolePermissionCreateNestedManyWithoutRoleInput
  roleGroupRoles?: Prisma.AuthRoleGroupRoleCreateNestedManyWithoutRoleInput
}

export type AuthRoleUncheckedCreateWithoutUserRolesInput = {
  id?: string
  key: string
  description?: string | null
  deletedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  permissions?: Prisma.AuthRolePermissionUncheckedCreateNestedManyWithoutRoleInput
  roleGroupRoles?: Prisma.AuthRoleGroupRoleUncheckedCreateNestedManyWithoutRoleInput
}

export type AuthRoleCreateOrConnectWithoutUserRolesInput = {
  where: Prisma.AuthRoleWhereUniqueInput
  create: Prisma.XOR<Prisma.AuthRoleCreateWithoutUserRolesInput, Prisma.AuthRoleUncheckedCreateWithoutUserRolesInput>
}

export type AuthRoleUpsertWithoutUserRolesInput = {
  update: Prisma.XOR<Prisma.AuthRoleUpdateWithoutUserRolesInput, Prisma.AuthRoleUncheckedUpdateWithoutUserRolesInput>
  create: Prisma.XOR<Prisma.AuthRoleCreateWithoutUserRolesInput, Prisma.AuthRoleUncheckedCreateWithoutUserRolesInput>
  where?: Prisma.AuthRoleWhereInput
}

export type AuthRoleUpdateToOneWithWhereWithoutUserRolesInput = {
  where?: Prisma.AuthRoleWhereInput
  data: Prisma.XOR<Prisma.AuthRoleUpdateWithoutUserRolesInput, Prisma.AuthRoleUncheckedUpdateWithoutUserRolesInput>
}

export type AuthRoleUpdateWithoutUserRolesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  permissions?: Prisma.AuthRolePermissionUpdateManyWithoutRoleNestedInput
  roleGroupRoles?: Prisma.AuthRoleGroupRoleUpdateManyWithoutRoleNestedInput
}

export type AuthRoleUncheckedUpdateWithoutUserRolesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  permissions?: Prisma.AuthRolePermissionUncheckedUpdateManyWithoutRoleNestedInput
  roleGroupRoles?: Prisma.AuthRoleGroupRoleUncheckedUpdateManyWithoutRoleNestedInput
}


/**
 * Count Type AuthRoleCountOutputType
 */

export type AuthRoleCountOutputType = {
  permissions: number
  userRoles: number
  roleGroupRoles: number
}

export type AuthRoleCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  permissions?: boolean | AuthRoleCountOutputTypeCountPermissionsArgs
  userRoles?: boolean | AuthRoleCountOutputTypeCountUserRolesArgs
  roleGroupRoles?: boolean | AuthRoleCountOutputTypeCountRoleGroupRolesArgs
}

/**
 * AuthRoleCountOutputType without action
 */
export type AuthRoleCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthRoleCountOutputType
   */
  select?: Prisma.AuthRoleCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AuthRoleCountOutputType without action
 */
export type AuthRoleCountOutputTypeCountPermissionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AuthRolePermissionWhereInput
}

/**
 * AuthRoleCountOutputType without action
 */
export type AuthRoleCountOutputTypeCountUserRolesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AuthUserRoleWhereInput
}

/**
 * AuthRoleCountOutputType without action
 */
export type AuthRoleCountOutputTypeCountRoleGroupRolesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AuthRoleGroupRoleWhereInput
}


export type AuthRoleSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  key?: boolean
  description?: boolean
  deletedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  permissions?: boolean | Prisma.AuthRole$permissionsArgs<ExtArgs>
  userRoles?: boolean | Prisma.AuthRole$userRolesArgs<ExtArgs>
  roleGroupRoles?: boolean | Prisma.AuthRole$roleGroupRolesArgs<ExtArgs>
  _count?: boolean | Prisma.AuthRoleCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["authRole"]>

export type AuthRoleSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  key?: boolean
  description?: boolean
  deletedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["authRole"]>

export type AuthRoleSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  key?: boolean
  description?: boolean
  deletedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["authRole"]>

export type AuthRoleSelectScalar = {
  id?: boolean
  key?: boolean
  description?: boolean
  deletedAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AuthRoleOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "key" | "description" | "deletedAt" | "createdAt" | "updatedAt", ExtArgs["result"]["authRole"]>
export type AuthRoleInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  permissions?: boolean | Prisma.AuthRole$permissionsArgs<ExtArgs>
  userRoles?: boolean | Prisma.AuthRole$userRolesArgs<ExtArgs>
  roleGroupRoles?: boolean | Prisma.AuthRole$roleGroupRolesArgs<ExtArgs>
  _count?: boolean | Prisma.AuthRoleCountOutputTypeDefaultArgs<ExtArgs>
}
export type AuthRoleIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type AuthRoleIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $AuthRolePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AuthRole"
  objects: {
    permissions: Prisma.$AuthRolePermissionPayload<ExtArgs>[]
    userRoles: Prisma.$AuthUserRolePayload<ExtArgs>[]
    roleGroupRoles: Prisma.$AuthRoleGroupRolePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    key: string
    description: string | null
    deletedAt: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["authRole"]>
  composites: {}
}

export type AuthRoleGetPayload<S extends boolean | null | undefined | AuthRoleDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AuthRolePayload, S>

export type AuthRoleCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AuthRoleFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AuthRoleCountAggregateInputType | true
  }

export interface AuthRoleDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AuthRole'], meta: { name: 'AuthRole' } }
  /**
   * Find zero or one AuthRole that matches the filter.
   * @param {AuthRoleFindUniqueArgs} args - Arguments to find a AuthRole
   * @example
   * // Get one AuthRole
   * const authRole = await prisma.authRole.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AuthRoleFindUniqueArgs>(args: Prisma.SelectSubset<T, AuthRoleFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AuthRoleClient<runtime.Types.Result.GetResult<Prisma.$AuthRolePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AuthRole that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AuthRoleFindUniqueOrThrowArgs} args - Arguments to find a AuthRole
   * @example
   * // Get one AuthRole
   * const authRole = await prisma.authRole.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AuthRoleFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AuthRoleFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AuthRoleClient<runtime.Types.Result.GetResult<Prisma.$AuthRolePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AuthRole that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthRoleFindFirstArgs} args - Arguments to find a AuthRole
   * @example
   * // Get one AuthRole
   * const authRole = await prisma.authRole.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AuthRoleFindFirstArgs>(args?: Prisma.SelectSubset<T, AuthRoleFindFirstArgs<ExtArgs>>): Prisma.Prisma__AuthRoleClient<runtime.Types.Result.GetResult<Prisma.$AuthRolePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AuthRole that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthRoleFindFirstOrThrowArgs} args - Arguments to find a AuthRole
   * @example
   * // Get one AuthRole
   * const authRole = await prisma.authRole.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AuthRoleFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AuthRoleFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AuthRoleClient<runtime.Types.Result.GetResult<Prisma.$AuthRolePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AuthRoles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthRoleFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AuthRoles
   * const authRoles = await prisma.authRole.findMany()
   * 
   * // Get first 10 AuthRoles
   * const authRoles = await prisma.authRole.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const authRoleWithIdOnly = await prisma.authRole.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AuthRoleFindManyArgs>(args?: Prisma.SelectSubset<T, AuthRoleFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuthRolePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AuthRole.
   * @param {AuthRoleCreateArgs} args - Arguments to create a AuthRole.
   * @example
   * // Create one AuthRole
   * const AuthRole = await prisma.authRole.create({
   *   data: {
   *     // ... data to create a AuthRole
   *   }
   * })
   * 
   */
  create<T extends AuthRoleCreateArgs>(args: Prisma.SelectSubset<T, AuthRoleCreateArgs<ExtArgs>>): Prisma.Prisma__AuthRoleClient<runtime.Types.Result.GetResult<Prisma.$AuthRolePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AuthRoles.
   * @param {AuthRoleCreateManyArgs} args - Arguments to create many AuthRoles.
   * @example
   * // Create many AuthRoles
   * const authRole = await prisma.authRole.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AuthRoleCreateManyArgs>(args?: Prisma.SelectSubset<T, AuthRoleCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AuthRoles and returns the data saved in the database.
   * @param {AuthRoleCreateManyAndReturnArgs} args - Arguments to create many AuthRoles.
   * @example
   * // Create many AuthRoles
   * const authRole = await prisma.authRole.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AuthRoles and only return the `id`
   * const authRoleWithIdOnly = await prisma.authRole.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AuthRoleCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AuthRoleCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuthRolePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AuthRole.
   * @param {AuthRoleDeleteArgs} args - Arguments to delete one AuthRole.
   * @example
   * // Delete one AuthRole
   * const AuthRole = await prisma.authRole.delete({
   *   where: {
   *     // ... filter to delete one AuthRole
   *   }
   * })
   * 
   */
  delete<T extends AuthRoleDeleteArgs>(args: Prisma.SelectSubset<T, AuthRoleDeleteArgs<ExtArgs>>): Prisma.Prisma__AuthRoleClient<runtime.Types.Result.GetResult<Prisma.$AuthRolePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AuthRole.
   * @param {AuthRoleUpdateArgs} args - Arguments to update one AuthRole.
   * @example
   * // Update one AuthRole
   * const authRole = await prisma.authRole.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AuthRoleUpdateArgs>(args: Prisma.SelectSubset<T, AuthRoleUpdateArgs<ExtArgs>>): Prisma.Prisma__AuthRoleClient<runtime.Types.Result.GetResult<Prisma.$AuthRolePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AuthRoles.
   * @param {AuthRoleDeleteManyArgs} args - Arguments to filter AuthRoles to delete.
   * @example
   * // Delete a few AuthRoles
   * const { count } = await prisma.authRole.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AuthRoleDeleteManyArgs>(args?: Prisma.SelectSubset<T, AuthRoleDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AuthRoles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthRoleUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AuthRoles
   * const authRole = await prisma.authRole.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AuthRoleUpdateManyArgs>(args: Prisma.SelectSubset<T, AuthRoleUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AuthRoles and returns the data updated in the database.
   * @param {AuthRoleUpdateManyAndReturnArgs} args - Arguments to update many AuthRoles.
   * @example
   * // Update many AuthRoles
   * const authRole = await prisma.authRole.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AuthRoles and only return the `id`
   * const authRoleWithIdOnly = await prisma.authRole.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AuthRoleUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AuthRoleUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuthRolePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AuthRole.
   * @param {AuthRoleUpsertArgs} args - Arguments to update or create a AuthRole.
   * @example
   * // Update or create a AuthRole
   * const authRole = await prisma.authRole.upsert({
   *   create: {
   *     // ... data to create a AuthRole
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AuthRole we want to update
   *   }
   * })
   */
  upsert<T extends AuthRoleUpsertArgs>(args: Prisma.SelectSubset<T, AuthRoleUpsertArgs<ExtArgs>>): Prisma.Prisma__AuthRoleClient<runtime.Types.Result.GetResult<Prisma.$AuthRolePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AuthRoles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthRoleCountArgs} args - Arguments to filter AuthRoles to count.
   * @example
   * // Count the number of AuthRoles
   * const count = await prisma.authRole.count({
   *   where: {
   *     // ... the filter for the AuthRoles we want to count
   *   }
   * })
  **/
  count<T extends AuthRoleCountArgs>(
    args?: Prisma.Subset<T, AuthRoleCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AuthRoleCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AuthRole.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthRoleAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AuthRoleAggregateArgs>(args: Prisma.Subset<T, AuthRoleAggregateArgs>): Prisma.PrismaPromise<GetAuthRoleAggregateType<T>>

  /**
   * Group by AuthRole.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuthRoleGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AuthRoleGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AuthRoleGroupByArgs['orderBy'] }
      : { orderBy?: AuthRoleGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AuthRoleGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAuthRoleGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AuthRole model
 */
readonly fields: AuthRoleFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AuthRole.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AuthRoleClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  permissions<T extends Prisma.AuthRole$permissionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AuthRole$permissionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuthRolePermissionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  userRoles<T extends Prisma.AuthRole$userRolesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AuthRole$userRolesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuthUserRolePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  roleGroupRoles<T extends Prisma.AuthRole$roleGroupRolesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AuthRole$roleGroupRolesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuthRoleGroupRolePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AuthRole model
 */
export interface AuthRoleFieldRefs {
  readonly id: Prisma.FieldRef<"AuthRole", 'String'>
  readonly key: Prisma.FieldRef<"AuthRole", 'String'>
  readonly description: Prisma.FieldRef<"AuthRole", 'String'>
  readonly deletedAt: Prisma.FieldRef<"AuthRole", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"AuthRole", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"AuthRole", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AuthRole findUnique
 */
export type AuthRoleFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthRole
   */
  select?: Prisma.AuthRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthRole
   */
  omit?: Prisma.AuthRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthRoleInclude<ExtArgs> | null
  /**
   * Filter, which AuthRole to fetch.
   */
  where: Prisma.AuthRoleWhereUniqueInput
}

/**
 * AuthRole findUniqueOrThrow
 */
export type AuthRoleFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthRole
   */
  select?: Prisma.AuthRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthRole
   */
  omit?: Prisma.AuthRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthRoleInclude<ExtArgs> | null
  /**
   * Filter, which AuthRole to fetch.
   */
  where: Prisma.AuthRoleWhereUniqueInput
}

/**
 * AuthRole findFirst
 */
export type AuthRoleFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthRole
   */
  select?: Prisma.AuthRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthRole
   */
  omit?: Prisma.AuthRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthRoleInclude<ExtArgs> | null
  /**
   * Filter, which AuthRole to fetch.
   */
  where?: Prisma.AuthRoleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuthRoles to fetch.
   */
  orderBy?: Prisma.AuthRoleOrderByWithRelationInput | Prisma.AuthRoleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AuthRoles.
   */
  cursor?: Prisma.AuthRoleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuthRoles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuthRoles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AuthRoles.
   */
  distinct?: Prisma.AuthRoleScalarFieldEnum | Prisma.AuthRoleScalarFieldEnum[]
}

/**
 * AuthRole findFirstOrThrow
 */
export type AuthRoleFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthRole
   */
  select?: Prisma.AuthRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthRole
   */
  omit?: Prisma.AuthRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthRoleInclude<ExtArgs> | null
  /**
   * Filter, which AuthRole to fetch.
   */
  where?: Prisma.AuthRoleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuthRoles to fetch.
   */
  orderBy?: Prisma.AuthRoleOrderByWithRelationInput | Prisma.AuthRoleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AuthRoles.
   */
  cursor?: Prisma.AuthRoleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuthRoles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuthRoles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AuthRoles.
   */
  distinct?: Prisma.AuthRoleScalarFieldEnum | Prisma.AuthRoleScalarFieldEnum[]
}

/**
 * AuthRole findMany
 */
export type AuthRoleFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthRole
   */
  select?: Prisma.AuthRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthRole
   */
  omit?: Prisma.AuthRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthRoleInclude<ExtArgs> | null
  /**
   * Filter, which AuthRoles to fetch.
   */
  where?: Prisma.AuthRoleWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuthRoles to fetch.
   */
  orderBy?: Prisma.AuthRoleOrderByWithRelationInput | Prisma.AuthRoleOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AuthRoles.
   */
  cursor?: Prisma.AuthRoleWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuthRoles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuthRoles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AuthRoles.
   */
  distinct?: Prisma.AuthRoleScalarFieldEnum | Prisma.AuthRoleScalarFieldEnum[]
}

/**
 * AuthRole create
 */
export type AuthRoleCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthRole
   */
  select?: Prisma.AuthRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthRole
   */
  omit?: Prisma.AuthRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthRoleInclude<ExtArgs> | null
  /**
   * The data needed to create a AuthRole.
   */
  data: Prisma.XOR<Prisma.AuthRoleCreateInput, Prisma.AuthRoleUncheckedCreateInput>
}

/**
 * AuthRole createMany
 */
export type AuthRoleCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AuthRoles.
   */
  data: Prisma.AuthRoleCreateManyInput | Prisma.AuthRoleCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AuthRole createManyAndReturn
 */
export type AuthRoleCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthRole
   */
  select?: Prisma.AuthRoleSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AuthRole
   */
  omit?: Prisma.AuthRoleOmit<ExtArgs> | null
  /**
   * The data used to create many AuthRoles.
   */
  data: Prisma.AuthRoleCreateManyInput | Prisma.AuthRoleCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AuthRole update
 */
export type AuthRoleUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthRole
   */
  select?: Prisma.AuthRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthRole
   */
  omit?: Prisma.AuthRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthRoleInclude<ExtArgs> | null
  /**
   * The data needed to update a AuthRole.
   */
  data: Prisma.XOR<Prisma.AuthRoleUpdateInput, Prisma.AuthRoleUncheckedUpdateInput>
  /**
   * Choose, which AuthRole to update.
   */
  where: Prisma.AuthRoleWhereUniqueInput
}

/**
 * AuthRole updateMany
 */
export type AuthRoleUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AuthRoles.
   */
  data: Prisma.XOR<Prisma.AuthRoleUpdateManyMutationInput, Prisma.AuthRoleUncheckedUpdateManyInput>
  /**
   * Filter which AuthRoles to update
   */
  where?: Prisma.AuthRoleWhereInput
  /**
   * Limit how many AuthRoles to update.
   */
  limit?: number
}

/**
 * AuthRole updateManyAndReturn
 */
export type AuthRoleUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthRole
   */
  select?: Prisma.AuthRoleSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AuthRole
   */
  omit?: Prisma.AuthRoleOmit<ExtArgs> | null
  /**
   * The data used to update AuthRoles.
   */
  data: Prisma.XOR<Prisma.AuthRoleUpdateManyMutationInput, Prisma.AuthRoleUncheckedUpdateManyInput>
  /**
   * Filter which AuthRoles to update
   */
  where?: Prisma.AuthRoleWhereInput
  /**
   * Limit how many AuthRoles to update.
   */
  limit?: number
}

/**
 * AuthRole upsert
 */
export type AuthRoleUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthRole
   */
  select?: Prisma.AuthRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthRole
   */
  omit?: Prisma.AuthRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthRoleInclude<ExtArgs> | null
  /**
   * The filter to search for the AuthRole to update in case it exists.
   */
  where: Prisma.AuthRoleWhereUniqueInput
  /**
   * In case the AuthRole found by the `where` argument doesn't exist, create a new AuthRole with this data.
   */
  create: Prisma.XOR<Prisma.AuthRoleCreateInput, Prisma.AuthRoleUncheckedCreateInput>
  /**
   * In case the AuthRole was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AuthRoleUpdateInput, Prisma.AuthRoleUncheckedUpdateInput>
}

/**
 * AuthRole delete
 */
export type AuthRoleDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthRole
   */
  select?: Prisma.AuthRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthRole
   */
  omit?: Prisma.AuthRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthRoleInclude<ExtArgs> | null
  /**
   * Filter which AuthRole to delete.
   */
  where: Prisma.AuthRoleWhereUniqueInput
}

/**
 * AuthRole deleteMany
 */
export type AuthRoleDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AuthRoles to delete
   */
  where?: Prisma.AuthRoleWhereInput
  /**
   * Limit how many AuthRoles to delete.
   */
  limit?: number
}

/**
 * AuthRole.permissions
 */
export type AuthRole$permissionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthRolePermission
   */
  select?: Prisma.AuthRolePermissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthRolePermission
   */
  omit?: Prisma.AuthRolePermissionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthRolePermissionInclude<ExtArgs> | null
  where?: Prisma.AuthRolePermissionWhereInput
  orderBy?: Prisma.AuthRolePermissionOrderByWithRelationInput | Prisma.AuthRolePermissionOrderByWithRelationInput[]
  cursor?: Prisma.AuthRolePermissionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AuthRolePermissionScalarFieldEnum | Prisma.AuthRolePermissionScalarFieldEnum[]
}

/**
 * AuthRole.userRoles
 */
export type AuthRole$userRolesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthUserRole
   */
  select?: Prisma.AuthUserRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthUserRole
   */
  omit?: Prisma.AuthUserRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthUserRoleInclude<ExtArgs> | null
  where?: Prisma.AuthUserRoleWhereInput
  orderBy?: Prisma.AuthUserRoleOrderByWithRelationInput | Prisma.AuthUserRoleOrderByWithRelationInput[]
  cursor?: Prisma.AuthUserRoleWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AuthUserRoleScalarFieldEnum | Prisma.AuthUserRoleScalarFieldEnum[]
}

/**
 * AuthRole.roleGroupRoles
 */
export type AuthRole$roleGroupRolesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthRoleGroupRole
   */
  select?: Prisma.AuthRoleGroupRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthRoleGroupRole
   */
  omit?: Prisma.AuthRoleGroupRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthRoleGroupRoleInclude<ExtArgs> | null
  where?: Prisma.AuthRoleGroupRoleWhereInput
  orderBy?: Prisma.AuthRoleGroupRoleOrderByWithRelationInput | Prisma.AuthRoleGroupRoleOrderByWithRelationInput[]
  cursor?: Prisma.AuthRoleGroupRoleWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AuthRoleGroupRoleScalarFieldEnum | Prisma.AuthRoleGroupRoleScalarFieldEnum[]
}

/**
 * AuthRole without action
 */
export type AuthRoleDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuthRole
   */
  select?: Prisma.AuthRoleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuthRole
   */
  omit?: Prisma.AuthRoleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuthRoleInclude<ExtArgs> | null
}
