
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Beneficiary` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Beneficiary
 * 
 */
export type BeneficiaryModel = runtime.Types.Result.DefaultSelection<Prisma.$BeneficiaryPayload>

export type AggregateBeneficiary = {
  _count: BeneficiaryCountAggregateOutputType | null
  _avg: BeneficiaryAvgAggregateOutputType | null
  _sum: BeneficiarySumAggregateOutputType | null
  _min: BeneficiaryMinAggregateOutputType | null
  _max: BeneficiaryMaxAggregateOutputType | null
}

export type BeneficiaryAvgAggregateOutputType = {
  age: number | null
}

export type BeneficiarySumAggregateOutputType = {
  age: number | null
}

export type BeneficiaryMinAggregateOutputType = {
  id: string | null
  projectId: string | null
  name: string | null
  type: string | null
  gender: string | null
  age: number | null
  dateOfBirth: Date | null
  contactNumber: string | null
  email: string | null
  address: string | null
  location: string | null
  category: string | null
  enrollmentDate: Date | null
  exitDate: Date | null
  status: string | null
  notes: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type BeneficiaryMaxAggregateOutputType = {
  id: string | null
  projectId: string | null
  name: string | null
  type: string | null
  gender: string | null
  age: number | null
  dateOfBirth: Date | null
  contactNumber: string | null
  email: string | null
  address: string | null
  location: string | null
  category: string | null
  enrollmentDate: Date | null
  exitDate: Date | null
  status: string | null
  notes: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type BeneficiaryCountAggregateOutputType = {
  id: number
  projectId: number
  name: number
  type: number
  gender: number
  age: number
  dateOfBirth: number
  contactNumber: number
  email: number
  address: number
  location: number
  category: number
  enrollmentDate: number
  exitDate: number
  status: number
  benefitsReceived: number
  notes: number
  metadata: number
  createdAt: number
  updatedAt: number
  deletedAt: number
  _all: number
}


export type BeneficiaryAvgAggregateInputType = {
  age?: true
}

export type BeneficiarySumAggregateInputType = {
  age?: true
}

export type BeneficiaryMinAggregateInputType = {
  id?: true
  projectId?: true
  name?: true
  type?: true
  gender?: true
  age?: true
  dateOfBirth?: true
  contactNumber?: true
  email?: true
  address?: true
  location?: true
  category?: true
  enrollmentDate?: true
  exitDate?: true
  status?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type BeneficiaryMaxAggregateInputType = {
  id?: true
  projectId?: true
  name?: true
  type?: true
  gender?: true
  age?: true
  dateOfBirth?: true
  contactNumber?: true
  email?: true
  address?: true
  location?: true
  category?: true
  enrollmentDate?: true
  exitDate?: true
  status?: true
  notes?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type BeneficiaryCountAggregateInputType = {
  id?: true
  projectId?: true
  name?: true
  type?: true
  gender?: true
  age?: true
  dateOfBirth?: true
  contactNumber?: true
  email?: true
  address?: true
  location?: true
  category?: true
  enrollmentDate?: true
  exitDate?: true
  status?: true
  benefitsReceived?: true
  notes?: true
  metadata?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  _all?: true
}

export type BeneficiaryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Beneficiary to aggregate.
   */
  where?: Prisma.BeneficiaryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Beneficiaries to fetch.
   */
  orderBy?: Prisma.BeneficiaryOrderByWithRelationInput | Prisma.BeneficiaryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BeneficiaryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Beneficiaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Beneficiaries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Beneficiaries
  **/
  _count?: true | BeneficiaryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: BeneficiaryAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: BeneficiarySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BeneficiaryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BeneficiaryMaxAggregateInputType
}

export type GetBeneficiaryAggregateType<T extends BeneficiaryAggregateArgs> = {
      [P in keyof T & keyof AggregateBeneficiary]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBeneficiary[P]>
    : Prisma.GetScalarType<T[P], AggregateBeneficiary[P]>
}




export type BeneficiaryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BeneficiaryWhereInput
  orderBy?: Prisma.BeneficiaryOrderByWithAggregationInput | Prisma.BeneficiaryOrderByWithAggregationInput[]
  by: Prisma.BeneficiaryScalarFieldEnum[] | Prisma.BeneficiaryScalarFieldEnum
  having?: Prisma.BeneficiaryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BeneficiaryCountAggregateInputType | true
  _avg?: BeneficiaryAvgAggregateInputType
  _sum?: BeneficiarySumAggregateInputType
  _min?: BeneficiaryMinAggregateInputType
  _max?: BeneficiaryMaxAggregateInputType
}

export type BeneficiaryGroupByOutputType = {
  id: string
  projectId: string
  name: string
  type: string
  gender: string | null
  age: number | null
  dateOfBirth: Date | null
  contactNumber: string | null
  email: string | null
  address: string | null
  location: string | null
  category: string | null
  enrollmentDate: Date
  exitDate: Date | null
  status: string
  benefitsReceived: string[]
  notes: string | null
  metadata: runtime.JsonValue | null
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  _count: BeneficiaryCountAggregateOutputType | null
  _avg: BeneficiaryAvgAggregateOutputType | null
  _sum: BeneficiarySumAggregateOutputType | null
  _min: BeneficiaryMinAggregateOutputType | null
  _max: BeneficiaryMaxAggregateOutputType | null
}

export type GetBeneficiaryGroupByPayload<T extends BeneficiaryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BeneficiaryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BeneficiaryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BeneficiaryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BeneficiaryGroupByOutputType[P]>
      }
    >
  >



export type BeneficiaryWhereInput = {
  AND?: Prisma.BeneficiaryWhereInput | Prisma.BeneficiaryWhereInput[]
  OR?: Prisma.BeneficiaryWhereInput[]
  NOT?: Prisma.BeneficiaryWhereInput | Prisma.BeneficiaryWhereInput[]
  id?: Prisma.StringFilter<"Beneficiary"> | string
  projectId?: Prisma.StringFilter<"Beneficiary"> | string
  name?: Prisma.StringFilter<"Beneficiary"> | string
  type?: Prisma.StringFilter<"Beneficiary"> | string
  gender?: Prisma.StringNullableFilter<"Beneficiary"> | string | null
  age?: Prisma.IntNullableFilter<"Beneficiary"> | number | null
  dateOfBirth?: Prisma.DateTimeNullableFilter<"Beneficiary"> | Date | string | null
  contactNumber?: Prisma.StringNullableFilter<"Beneficiary"> | string | null
  email?: Prisma.StringNullableFilter<"Beneficiary"> | string | null
  address?: Prisma.StringNullableFilter<"Beneficiary"> | string | null
  location?: Prisma.StringNullableFilter<"Beneficiary"> | string | null
  category?: Prisma.StringNullableFilter<"Beneficiary"> | string | null
  enrollmentDate?: Prisma.DateTimeFilter<"Beneficiary"> | Date | string
  exitDate?: Prisma.DateTimeNullableFilter<"Beneficiary"> | Date | string | null
  status?: Prisma.StringFilter<"Beneficiary"> | string
  benefitsReceived?: Prisma.StringNullableListFilter<"Beneficiary">
  notes?: Prisma.StringNullableFilter<"Beneficiary"> | string | null
  metadata?: Prisma.JsonNullableFilter<"Beneficiary">
  createdAt?: Prisma.DateTimeFilter<"Beneficiary"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Beneficiary"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Beneficiary"> | Date | string | null
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
}

export type BeneficiaryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  gender?: Prisma.SortOrderInput | Prisma.SortOrder
  age?: Prisma.SortOrderInput | Prisma.SortOrder
  dateOfBirth?: Prisma.SortOrderInput | Prisma.SortOrder
  contactNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  location?: Prisma.SortOrderInput | Prisma.SortOrder
  category?: Prisma.SortOrderInput | Prisma.SortOrder
  enrollmentDate?: Prisma.SortOrder
  exitDate?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  benefitsReceived?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  project?: Prisma.ProjectOrderByWithRelationInput
}

export type BeneficiaryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.BeneficiaryWhereInput | Prisma.BeneficiaryWhereInput[]
  OR?: Prisma.BeneficiaryWhereInput[]
  NOT?: Prisma.BeneficiaryWhereInput | Prisma.BeneficiaryWhereInput[]
  projectId?: Prisma.StringFilter<"Beneficiary"> | string
  name?: Prisma.StringFilter<"Beneficiary"> | string
  type?: Prisma.StringFilter<"Beneficiary"> | string
  gender?: Prisma.StringNullableFilter<"Beneficiary"> | string | null
  age?: Prisma.IntNullableFilter<"Beneficiary"> | number | null
  dateOfBirth?: Prisma.DateTimeNullableFilter<"Beneficiary"> | Date | string | null
  contactNumber?: Prisma.StringNullableFilter<"Beneficiary"> | string | null
  email?: Prisma.StringNullableFilter<"Beneficiary"> | string | null
  address?: Prisma.StringNullableFilter<"Beneficiary"> | string | null
  location?: Prisma.StringNullableFilter<"Beneficiary"> | string | null
  category?: Prisma.StringNullableFilter<"Beneficiary"> | string | null
  enrollmentDate?: Prisma.DateTimeFilter<"Beneficiary"> | Date | string
  exitDate?: Prisma.DateTimeNullableFilter<"Beneficiary"> | Date | string | null
  status?: Prisma.StringFilter<"Beneficiary"> | string
  benefitsReceived?: Prisma.StringNullableListFilter<"Beneficiary">
  notes?: Prisma.StringNullableFilter<"Beneficiary"> | string | null
  metadata?: Prisma.JsonNullableFilter<"Beneficiary">
  createdAt?: Prisma.DateTimeFilter<"Beneficiary"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Beneficiary"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Beneficiary"> | Date | string | null
  project?: Prisma.XOR<Prisma.ProjectScalarRelationFilter, Prisma.ProjectWhereInput>
}, "id">

export type BeneficiaryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  gender?: Prisma.SortOrderInput | Prisma.SortOrder
  age?: Prisma.SortOrderInput | Prisma.SortOrder
  dateOfBirth?: Prisma.SortOrderInput | Prisma.SortOrder
  contactNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  location?: Prisma.SortOrderInput | Prisma.SortOrder
  category?: Prisma.SortOrderInput | Prisma.SortOrder
  enrollmentDate?: Prisma.SortOrder
  exitDate?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  benefitsReceived?: Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  metadata?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.BeneficiaryCountOrderByAggregateInput
  _avg?: Prisma.BeneficiaryAvgOrderByAggregateInput
  _max?: Prisma.BeneficiaryMaxOrderByAggregateInput
  _min?: Prisma.BeneficiaryMinOrderByAggregateInput
  _sum?: Prisma.BeneficiarySumOrderByAggregateInput
}

export type BeneficiaryScalarWhereWithAggregatesInput = {
  AND?: Prisma.BeneficiaryScalarWhereWithAggregatesInput | Prisma.BeneficiaryScalarWhereWithAggregatesInput[]
  OR?: Prisma.BeneficiaryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BeneficiaryScalarWhereWithAggregatesInput | Prisma.BeneficiaryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Beneficiary"> | string
  projectId?: Prisma.StringWithAggregatesFilter<"Beneficiary"> | string
  name?: Prisma.StringWithAggregatesFilter<"Beneficiary"> | string
  type?: Prisma.StringWithAggregatesFilter<"Beneficiary"> | string
  gender?: Prisma.StringNullableWithAggregatesFilter<"Beneficiary"> | string | null
  age?: Prisma.IntNullableWithAggregatesFilter<"Beneficiary"> | number | null
  dateOfBirth?: Prisma.DateTimeNullableWithAggregatesFilter<"Beneficiary"> | Date | string | null
  contactNumber?: Prisma.StringNullableWithAggregatesFilter<"Beneficiary"> | string | null
  email?: Prisma.StringNullableWithAggregatesFilter<"Beneficiary"> | string | null
  address?: Prisma.StringNullableWithAggregatesFilter<"Beneficiary"> | string | null
  location?: Prisma.StringNullableWithAggregatesFilter<"Beneficiary"> | string | null
  category?: Prisma.StringNullableWithAggregatesFilter<"Beneficiary"> | string | null
  enrollmentDate?: Prisma.DateTimeWithAggregatesFilter<"Beneficiary"> | Date | string
  exitDate?: Prisma.DateTimeNullableWithAggregatesFilter<"Beneficiary"> | Date | string | null
  status?: Prisma.StringWithAggregatesFilter<"Beneficiary"> | string
  benefitsReceived?: Prisma.StringNullableListFilter<"Beneficiary">
  notes?: Prisma.StringNullableWithAggregatesFilter<"Beneficiary"> | string | null
  metadata?: Prisma.JsonNullableWithAggregatesFilter<"Beneficiary">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Beneficiary"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Beneficiary"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Beneficiary"> | Date | string | null
}

export type BeneficiaryCreateInput = {
  id?: string
  name: string
  type: string
  gender?: string | null
  age?: number | null
  dateOfBirth?: Date | string | null
  contactNumber?: string | null
  email?: string | null
  address?: string | null
  location?: string | null
  category?: string | null
  enrollmentDate: Date | string
  exitDate?: Date | string | null
  status: string
  benefitsReceived?: Prisma.BeneficiaryCreatebenefitsReceivedInput | string[]
  notes?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  project: Prisma.ProjectCreateNestedOneWithoutBeneficiariesInput
}

export type BeneficiaryUncheckedCreateInput = {
  id?: string
  projectId: string
  name: string
  type: string
  gender?: string | null
  age?: number | null
  dateOfBirth?: Date | string | null
  contactNumber?: string | null
  email?: string | null
  address?: string | null
  location?: string | null
  category?: string | null
  enrollmentDate: Date | string
  exitDate?: Date | string | null
  status: string
  benefitsReceived?: Prisma.BeneficiaryCreatebenefitsReceivedInput | string[]
  notes?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type BeneficiaryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  age?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  dateOfBirth?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  contactNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  enrollmentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  exitDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  benefitsReceived?: Prisma.BeneficiaryUpdatebenefitsReceivedInput | string[]
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  project?: Prisma.ProjectUpdateOneRequiredWithoutBeneficiariesNestedInput
}

export type BeneficiaryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  age?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  dateOfBirth?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  contactNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  enrollmentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  exitDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  benefitsReceived?: Prisma.BeneficiaryUpdatebenefitsReceivedInput | string[]
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type BeneficiaryCreateManyInput = {
  id?: string
  projectId: string
  name: string
  type: string
  gender?: string | null
  age?: number | null
  dateOfBirth?: Date | string | null
  contactNumber?: string | null
  email?: string | null
  address?: string | null
  location?: string | null
  category?: string | null
  enrollmentDate: Date | string
  exitDate?: Date | string | null
  status: string
  benefitsReceived?: Prisma.BeneficiaryCreatebenefitsReceivedInput | string[]
  notes?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type BeneficiaryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  age?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  dateOfBirth?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  contactNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  enrollmentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  exitDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  benefitsReceived?: Prisma.BeneficiaryUpdatebenefitsReceivedInput | string[]
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type BeneficiaryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  projectId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  age?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  dateOfBirth?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  contactNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  enrollmentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  exitDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  benefitsReceived?: Prisma.BeneficiaryUpdatebenefitsReceivedInput | string[]
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type BeneficiaryListRelationFilter = {
  every?: Prisma.BeneficiaryWhereInput
  some?: Prisma.BeneficiaryWhereInput
  none?: Prisma.BeneficiaryWhereInput
}

export type BeneficiaryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BeneficiaryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  age?: Prisma.SortOrder
  dateOfBirth?: Prisma.SortOrder
  contactNumber?: Prisma.SortOrder
  email?: Prisma.SortOrder
  address?: Prisma.SortOrder
  location?: Prisma.SortOrder
  category?: Prisma.SortOrder
  enrollmentDate?: Prisma.SortOrder
  exitDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  benefitsReceived?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  metadata?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type BeneficiaryAvgOrderByAggregateInput = {
  age?: Prisma.SortOrder
}

export type BeneficiaryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  age?: Prisma.SortOrder
  dateOfBirth?: Prisma.SortOrder
  contactNumber?: Prisma.SortOrder
  email?: Prisma.SortOrder
  address?: Prisma.SortOrder
  location?: Prisma.SortOrder
  category?: Prisma.SortOrder
  enrollmentDate?: Prisma.SortOrder
  exitDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type BeneficiaryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  projectId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  type?: Prisma.SortOrder
  gender?: Prisma.SortOrder
  age?: Prisma.SortOrder
  dateOfBirth?: Prisma.SortOrder
  contactNumber?: Prisma.SortOrder
  email?: Prisma.SortOrder
  address?: Prisma.SortOrder
  location?: Prisma.SortOrder
  category?: Prisma.SortOrder
  enrollmentDate?: Prisma.SortOrder
  exitDate?: Prisma.SortOrder
  status?: Prisma.SortOrder
  notes?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type BeneficiarySumOrderByAggregateInput = {
  age?: Prisma.SortOrder
}

export type BeneficiaryCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.BeneficiaryCreateWithoutProjectInput, Prisma.BeneficiaryUncheckedCreateWithoutProjectInput> | Prisma.BeneficiaryCreateWithoutProjectInput[] | Prisma.BeneficiaryUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.BeneficiaryCreateOrConnectWithoutProjectInput | Prisma.BeneficiaryCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.BeneficiaryCreateManyProjectInputEnvelope
  connect?: Prisma.BeneficiaryWhereUniqueInput | Prisma.BeneficiaryWhereUniqueInput[]
}

export type BeneficiaryUncheckedCreateNestedManyWithoutProjectInput = {
  create?: Prisma.XOR<Prisma.BeneficiaryCreateWithoutProjectInput, Prisma.BeneficiaryUncheckedCreateWithoutProjectInput> | Prisma.BeneficiaryCreateWithoutProjectInput[] | Prisma.BeneficiaryUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.BeneficiaryCreateOrConnectWithoutProjectInput | Prisma.BeneficiaryCreateOrConnectWithoutProjectInput[]
  createMany?: Prisma.BeneficiaryCreateManyProjectInputEnvelope
  connect?: Prisma.BeneficiaryWhereUniqueInput | Prisma.BeneficiaryWhereUniqueInput[]
}

export type BeneficiaryUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.BeneficiaryCreateWithoutProjectInput, Prisma.BeneficiaryUncheckedCreateWithoutProjectInput> | Prisma.BeneficiaryCreateWithoutProjectInput[] | Prisma.BeneficiaryUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.BeneficiaryCreateOrConnectWithoutProjectInput | Prisma.BeneficiaryCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.BeneficiaryUpsertWithWhereUniqueWithoutProjectInput | Prisma.BeneficiaryUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.BeneficiaryCreateManyProjectInputEnvelope
  set?: Prisma.BeneficiaryWhereUniqueInput | Prisma.BeneficiaryWhereUniqueInput[]
  disconnect?: Prisma.BeneficiaryWhereUniqueInput | Prisma.BeneficiaryWhereUniqueInput[]
  delete?: Prisma.BeneficiaryWhereUniqueInput | Prisma.BeneficiaryWhereUniqueInput[]
  connect?: Prisma.BeneficiaryWhereUniqueInput | Prisma.BeneficiaryWhereUniqueInput[]
  update?: Prisma.BeneficiaryUpdateWithWhereUniqueWithoutProjectInput | Prisma.BeneficiaryUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.BeneficiaryUpdateManyWithWhereWithoutProjectInput | Prisma.BeneficiaryUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.BeneficiaryScalarWhereInput | Prisma.BeneficiaryScalarWhereInput[]
}

export type BeneficiaryUncheckedUpdateManyWithoutProjectNestedInput = {
  create?: Prisma.XOR<Prisma.BeneficiaryCreateWithoutProjectInput, Prisma.BeneficiaryUncheckedCreateWithoutProjectInput> | Prisma.BeneficiaryCreateWithoutProjectInput[] | Prisma.BeneficiaryUncheckedCreateWithoutProjectInput[]
  connectOrCreate?: Prisma.BeneficiaryCreateOrConnectWithoutProjectInput | Prisma.BeneficiaryCreateOrConnectWithoutProjectInput[]
  upsert?: Prisma.BeneficiaryUpsertWithWhereUniqueWithoutProjectInput | Prisma.BeneficiaryUpsertWithWhereUniqueWithoutProjectInput[]
  createMany?: Prisma.BeneficiaryCreateManyProjectInputEnvelope
  set?: Prisma.BeneficiaryWhereUniqueInput | Prisma.BeneficiaryWhereUniqueInput[]
  disconnect?: Prisma.BeneficiaryWhereUniqueInput | Prisma.BeneficiaryWhereUniqueInput[]
  delete?: Prisma.BeneficiaryWhereUniqueInput | Prisma.BeneficiaryWhereUniqueInput[]
  connect?: Prisma.BeneficiaryWhereUniqueInput | Prisma.BeneficiaryWhereUniqueInput[]
  update?: Prisma.BeneficiaryUpdateWithWhereUniqueWithoutProjectInput | Prisma.BeneficiaryUpdateWithWhereUniqueWithoutProjectInput[]
  updateMany?: Prisma.BeneficiaryUpdateManyWithWhereWithoutProjectInput | Prisma.BeneficiaryUpdateManyWithWhereWithoutProjectInput[]
  deleteMany?: Prisma.BeneficiaryScalarWhereInput | Prisma.BeneficiaryScalarWhereInput[]
}

export type BeneficiaryCreatebenefitsReceivedInput = {
  set: string[]
}

export type BeneficiaryUpdatebenefitsReceivedInput = {
  set?: string[]
  push?: string | string[]
}

export type BeneficiaryCreateWithoutProjectInput = {
  id?: string
  name: string
  type: string
  gender?: string | null
  age?: number | null
  dateOfBirth?: Date | string | null
  contactNumber?: string | null
  email?: string | null
  address?: string | null
  location?: string | null
  category?: string | null
  enrollmentDate: Date | string
  exitDate?: Date | string | null
  status: string
  benefitsReceived?: Prisma.BeneficiaryCreatebenefitsReceivedInput | string[]
  notes?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type BeneficiaryUncheckedCreateWithoutProjectInput = {
  id?: string
  name: string
  type: string
  gender?: string | null
  age?: number | null
  dateOfBirth?: Date | string | null
  contactNumber?: string | null
  email?: string | null
  address?: string | null
  location?: string | null
  category?: string | null
  enrollmentDate: Date | string
  exitDate?: Date | string | null
  status: string
  benefitsReceived?: Prisma.BeneficiaryCreatebenefitsReceivedInput | string[]
  notes?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type BeneficiaryCreateOrConnectWithoutProjectInput = {
  where: Prisma.BeneficiaryWhereUniqueInput
  create: Prisma.XOR<Prisma.BeneficiaryCreateWithoutProjectInput, Prisma.BeneficiaryUncheckedCreateWithoutProjectInput>
}

export type BeneficiaryCreateManyProjectInputEnvelope = {
  data: Prisma.BeneficiaryCreateManyProjectInput | Prisma.BeneficiaryCreateManyProjectInput[]
  skipDuplicates?: boolean
}

export type BeneficiaryUpsertWithWhereUniqueWithoutProjectInput = {
  where: Prisma.BeneficiaryWhereUniqueInput
  update: Prisma.XOR<Prisma.BeneficiaryUpdateWithoutProjectInput, Prisma.BeneficiaryUncheckedUpdateWithoutProjectInput>
  create: Prisma.XOR<Prisma.BeneficiaryCreateWithoutProjectInput, Prisma.BeneficiaryUncheckedCreateWithoutProjectInput>
}

export type BeneficiaryUpdateWithWhereUniqueWithoutProjectInput = {
  where: Prisma.BeneficiaryWhereUniqueInput
  data: Prisma.XOR<Prisma.BeneficiaryUpdateWithoutProjectInput, Prisma.BeneficiaryUncheckedUpdateWithoutProjectInput>
}

export type BeneficiaryUpdateManyWithWhereWithoutProjectInput = {
  where: Prisma.BeneficiaryScalarWhereInput
  data: Prisma.XOR<Prisma.BeneficiaryUpdateManyMutationInput, Prisma.BeneficiaryUncheckedUpdateManyWithoutProjectInput>
}

export type BeneficiaryScalarWhereInput = {
  AND?: Prisma.BeneficiaryScalarWhereInput | Prisma.BeneficiaryScalarWhereInput[]
  OR?: Prisma.BeneficiaryScalarWhereInput[]
  NOT?: Prisma.BeneficiaryScalarWhereInput | Prisma.BeneficiaryScalarWhereInput[]
  id?: Prisma.StringFilter<"Beneficiary"> | string
  projectId?: Prisma.StringFilter<"Beneficiary"> | string
  name?: Prisma.StringFilter<"Beneficiary"> | string
  type?: Prisma.StringFilter<"Beneficiary"> | string
  gender?: Prisma.StringNullableFilter<"Beneficiary"> | string | null
  age?: Prisma.IntNullableFilter<"Beneficiary"> | number | null
  dateOfBirth?: Prisma.DateTimeNullableFilter<"Beneficiary"> | Date | string | null
  contactNumber?: Prisma.StringNullableFilter<"Beneficiary"> | string | null
  email?: Prisma.StringNullableFilter<"Beneficiary"> | string | null
  address?: Prisma.StringNullableFilter<"Beneficiary"> | string | null
  location?: Prisma.StringNullableFilter<"Beneficiary"> | string | null
  category?: Prisma.StringNullableFilter<"Beneficiary"> | string | null
  enrollmentDate?: Prisma.DateTimeFilter<"Beneficiary"> | Date | string
  exitDate?: Prisma.DateTimeNullableFilter<"Beneficiary"> | Date | string | null
  status?: Prisma.StringFilter<"Beneficiary"> | string
  benefitsReceived?: Prisma.StringNullableListFilter<"Beneficiary">
  notes?: Prisma.StringNullableFilter<"Beneficiary"> | string | null
  metadata?: Prisma.JsonNullableFilter<"Beneficiary">
  createdAt?: Prisma.DateTimeFilter<"Beneficiary"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Beneficiary"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"Beneficiary"> | Date | string | null
}

export type BeneficiaryCreateManyProjectInput = {
  id?: string
  name: string
  type: string
  gender?: string | null
  age?: number | null
  dateOfBirth?: Date | string | null
  contactNumber?: string | null
  email?: string | null
  address?: string | null
  location?: string | null
  category?: string | null
  enrollmentDate: Date | string
  exitDate?: Date | string | null
  status: string
  benefitsReceived?: Prisma.BeneficiaryCreatebenefitsReceivedInput | string[]
  notes?: string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type BeneficiaryUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  age?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  dateOfBirth?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  contactNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  enrollmentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  exitDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  benefitsReceived?: Prisma.BeneficiaryUpdatebenefitsReceivedInput | string[]
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type BeneficiaryUncheckedUpdateWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  age?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  dateOfBirth?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  contactNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  enrollmentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  exitDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  benefitsReceived?: Prisma.BeneficiaryUpdatebenefitsReceivedInput | string[]
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type BeneficiaryUncheckedUpdateManyWithoutProjectInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.StringFieldUpdateOperationsInput | string
  gender?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  age?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  dateOfBirth?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  contactNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  location?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  category?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  enrollmentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  exitDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  status?: Prisma.StringFieldUpdateOperationsInput | string
  benefitsReceived?: Prisma.BeneficiaryUpdatebenefitsReceivedInput | string[]
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  metadata?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type BeneficiarySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  name?: boolean
  type?: boolean
  gender?: boolean
  age?: boolean
  dateOfBirth?: boolean
  contactNumber?: boolean
  email?: boolean
  address?: boolean
  location?: boolean
  category?: boolean
  enrollmentDate?: boolean
  exitDate?: boolean
  status?: boolean
  benefitsReceived?: boolean
  notes?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["beneficiary"]>

export type BeneficiarySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  name?: boolean
  type?: boolean
  gender?: boolean
  age?: boolean
  dateOfBirth?: boolean
  contactNumber?: boolean
  email?: boolean
  address?: boolean
  location?: boolean
  category?: boolean
  enrollmentDate?: boolean
  exitDate?: boolean
  status?: boolean
  benefitsReceived?: boolean
  notes?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["beneficiary"]>

export type BeneficiarySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  projectId?: boolean
  name?: boolean
  type?: boolean
  gender?: boolean
  age?: boolean
  dateOfBirth?: boolean
  contactNumber?: boolean
  email?: boolean
  address?: boolean
  location?: boolean
  category?: boolean
  enrollmentDate?: boolean
  exitDate?: boolean
  status?: boolean
  benefitsReceived?: boolean
  notes?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}, ExtArgs["result"]["beneficiary"]>

export type BeneficiarySelectScalar = {
  id?: boolean
  projectId?: boolean
  name?: boolean
  type?: boolean
  gender?: boolean
  age?: boolean
  dateOfBirth?: boolean
  contactNumber?: boolean
  email?: boolean
  address?: boolean
  location?: boolean
  category?: boolean
  enrollmentDate?: boolean
  exitDate?: boolean
  status?: boolean
  benefitsReceived?: boolean
  notes?: boolean
  metadata?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}

export type BeneficiaryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "projectId" | "name" | "type" | "gender" | "age" | "dateOfBirth" | "contactNumber" | "email" | "address" | "location" | "category" | "enrollmentDate" | "exitDate" | "status" | "benefitsReceived" | "notes" | "metadata" | "createdAt" | "updatedAt" | "deletedAt", ExtArgs["result"]["beneficiary"]>
export type BeneficiaryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}
export type BeneficiaryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}
export type BeneficiaryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  project?: boolean | Prisma.ProjectDefaultArgs<ExtArgs>
}

export type $BeneficiaryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Beneficiary"
  objects: {
    project: Prisma.$ProjectPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    projectId: string
    name: string
    type: string
    gender: string | null
    age: number | null
    dateOfBirth: Date | null
    contactNumber: string | null
    email: string | null
    address: string | null
    location: string | null
    category: string | null
    enrollmentDate: Date
    exitDate: Date | null
    status: string
    benefitsReceived: string[]
    notes: string | null
    metadata: runtime.JsonValue | null
    createdAt: Date
    updatedAt: Date
    deletedAt: Date | null
  }, ExtArgs["result"]["beneficiary"]>
  composites: {}
}

export type BeneficiaryGetPayload<S extends boolean | null | undefined | BeneficiaryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BeneficiaryPayload, S>

export type BeneficiaryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BeneficiaryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BeneficiaryCountAggregateInputType | true
  }

export interface BeneficiaryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Beneficiary'], meta: { name: 'Beneficiary' } }
  /**
   * Find zero or one Beneficiary that matches the filter.
   * @param {BeneficiaryFindUniqueArgs} args - Arguments to find a Beneficiary
   * @example
   * // Get one Beneficiary
   * const beneficiary = await prisma.beneficiary.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BeneficiaryFindUniqueArgs>(args: Prisma.SelectSubset<T, BeneficiaryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BeneficiaryClient<runtime.Types.Result.GetResult<Prisma.$BeneficiaryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Beneficiary that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BeneficiaryFindUniqueOrThrowArgs} args - Arguments to find a Beneficiary
   * @example
   * // Get one Beneficiary
   * const beneficiary = await prisma.beneficiary.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BeneficiaryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BeneficiaryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BeneficiaryClient<runtime.Types.Result.GetResult<Prisma.$BeneficiaryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Beneficiary that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BeneficiaryFindFirstArgs} args - Arguments to find a Beneficiary
   * @example
   * // Get one Beneficiary
   * const beneficiary = await prisma.beneficiary.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BeneficiaryFindFirstArgs>(args?: Prisma.SelectSubset<T, BeneficiaryFindFirstArgs<ExtArgs>>): Prisma.Prisma__BeneficiaryClient<runtime.Types.Result.GetResult<Prisma.$BeneficiaryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Beneficiary that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BeneficiaryFindFirstOrThrowArgs} args - Arguments to find a Beneficiary
   * @example
   * // Get one Beneficiary
   * const beneficiary = await prisma.beneficiary.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BeneficiaryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BeneficiaryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BeneficiaryClient<runtime.Types.Result.GetResult<Prisma.$BeneficiaryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Beneficiaries that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BeneficiaryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Beneficiaries
   * const beneficiaries = await prisma.beneficiary.findMany()
   * 
   * // Get first 10 Beneficiaries
   * const beneficiaries = await prisma.beneficiary.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const beneficiaryWithIdOnly = await prisma.beneficiary.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BeneficiaryFindManyArgs>(args?: Prisma.SelectSubset<T, BeneficiaryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BeneficiaryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Beneficiary.
   * @param {BeneficiaryCreateArgs} args - Arguments to create a Beneficiary.
   * @example
   * // Create one Beneficiary
   * const Beneficiary = await prisma.beneficiary.create({
   *   data: {
   *     // ... data to create a Beneficiary
   *   }
   * })
   * 
   */
  create<T extends BeneficiaryCreateArgs>(args: Prisma.SelectSubset<T, BeneficiaryCreateArgs<ExtArgs>>): Prisma.Prisma__BeneficiaryClient<runtime.Types.Result.GetResult<Prisma.$BeneficiaryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Beneficiaries.
   * @param {BeneficiaryCreateManyArgs} args - Arguments to create many Beneficiaries.
   * @example
   * // Create many Beneficiaries
   * const beneficiary = await prisma.beneficiary.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BeneficiaryCreateManyArgs>(args?: Prisma.SelectSubset<T, BeneficiaryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Beneficiaries and returns the data saved in the database.
   * @param {BeneficiaryCreateManyAndReturnArgs} args - Arguments to create many Beneficiaries.
   * @example
   * // Create many Beneficiaries
   * const beneficiary = await prisma.beneficiary.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Beneficiaries and only return the `id`
   * const beneficiaryWithIdOnly = await prisma.beneficiary.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BeneficiaryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BeneficiaryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BeneficiaryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Beneficiary.
   * @param {BeneficiaryDeleteArgs} args - Arguments to delete one Beneficiary.
   * @example
   * // Delete one Beneficiary
   * const Beneficiary = await prisma.beneficiary.delete({
   *   where: {
   *     // ... filter to delete one Beneficiary
   *   }
   * })
   * 
   */
  delete<T extends BeneficiaryDeleteArgs>(args: Prisma.SelectSubset<T, BeneficiaryDeleteArgs<ExtArgs>>): Prisma.Prisma__BeneficiaryClient<runtime.Types.Result.GetResult<Prisma.$BeneficiaryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Beneficiary.
   * @param {BeneficiaryUpdateArgs} args - Arguments to update one Beneficiary.
   * @example
   * // Update one Beneficiary
   * const beneficiary = await prisma.beneficiary.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BeneficiaryUpdateArgs>(args: Prisma.SelectSubset<T, BeneficiaryUpdateArgs<ExtArgs>>): Prisma.Prisma__BeneficiaryClient<runtime.Types.Result.GetResult<Prisma.$BeneficiaryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Beneficiaries.
   * @param {BeneficiaryDeleteManyArgs} args - Arguments to filter Beneficiaries to delete.
   * @example
   * // Delete a few Beneficiaries
   * const { count } = await prisma.beneficiary.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BeneficiaryDeleteManyArgs>(args?: Prisma.SelectSubset<T, BeneficiaryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Beneficiaries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BeneficiaryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Beneficiaries
   * const beneficiary = await prisma.beneficiary.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BeneficiaryUpdateManyArgs>(args: Prisma.SelectSubset<T, BeneficiaryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Beneficiaries and returns the data updated in the database.
   * @param {BeneficiaryUpdateManyAndReturnArgs} args - Arguments to update many Beneficiaries.
   * @example
   * // Update many Beneficiaries
   * const beneficiary = await prisma.beneficiary.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Beneficiaries and only return the `id`
   * const beneficiaryWithIdOnly = await prisma.beneficiary.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BeneficiaryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BeneficiaryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BeneficiaryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Beneficiary.
   * @param {BeneficiaryUpsertArgs} args - Arguments to update or create a Beneficiary.
   * @example
   * // Update or create a Beneficiary
   * const beneficiary = await prisma.beneficiary.upsert({
   *   create: {
   *     // ... data to create a Beneficiary
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Beneficiary we want to update
   *   }
   * })
   */
  upsert<T extends BeneficiaryUpsertArgs>(args: Prisma.SelectSubset<T, BeneficiaryUpsertArgs<ExtArgs>>): Prisma.Prisma__BeneficiaryClient<runtime.Types.Result.GetResult<Prisma.$BeneficiaryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Beneficiaries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BeneficiaryCountArgs} args - Arguments to filter Beneficiaries to count.
   * @example
   * // Count the number of Beneficiaries
   * const count = await prisma.beneficiary.count({
   *   where: {
   *     // ... the filter for the Beneficiaries we want to count
   *   }
   * })
  **/
  count<T extends BeneficiaryCountArgs>(
    args?: Prisma.Subset<T, BeneficiaryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BeneficiaryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Beneficiary.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BeneficiaryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BeneficiaryAggregateArgs>(args: Prisma.Subset<T, BeneficiaryAggregateArgs>): Prisma.PrismaPromise<GetBeneficiaryAggregateType<T>>

  /**
   * Group by Beneficiary.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BeneficiaryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BeneficiaryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BeneficiaryGroupByArgs['orderBy'] }
      : { orderBy?: BeneficiaryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BeneficiaryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBeneficiaryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Beneficiary model
 */
readonly fields: BeneficiaryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Beneficiary.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BeneficiaryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  project<T extends Prisma.ProjectDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ProjectDefaultArgs<ExtArgs>>): Prisma.Prisma__ProjectClient<runtime.Types.Result.GetResult<Prisma.$ProjectPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Beneficiary model
 */
export interface BeneficiaryFieldRefs {
  readonly id: Prisma.FieldRef<"Beneficiary", 'String'>
  readonly projectId: Prisma.FieldRef<"Beneficiary", 'String'>
  readonly name: Prisma.FieldRef<"Beneficiary", 'String'>
  readonly type: Prisma.FieldRef<"Beneficiary", 'String'>
  readonly gender: Prisma.FieldRef<"Beneficiary", 'String'>
  readonly age: Prisma.FieldRef<"Beneficiary", 'Int'>
  readonly dateOfBirth: Prisma.FieldRef<"Beneficiary", 'DateTime'>
  readonly contactNumber: Prisma.FieldRef<"Beneficiary", 'String'>
  readonly email: Prisma.FieldRef<"Beneficiary", 'String'>
  readonly address: Prisma.FieldRef<"Beneficiary", 'String'>
  readonly location: Prisma.FieldRef<"Beneficiary", 'String'>
  readonly category: Prisma.FieldRef<"Beneficiary", 'String'>
  readonly enrollmentDate: Prisma.FieldRef<"Beneficiary", 'DateTime'>
  readonly exitDate: Prisma.FieldRef<"Beneficiary", 'DateTime'>
  readonly status: Prisma.FieldRef<"Beneficiary", 'String'>
  readonly benefitsReceived: Prisma.FieldRef<"Beneficiary", 'String[]'>
  readonly notes: Prisma.FieldRef<"Beneficiary", 'String'>
  readonly metadata: Prisma.FieldRef<"Beneficiary", 'Json'>
  readonly createdAt: Prisma.FieldRef<"Beneficiary", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Beneficiary", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"Beneficiary", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Beneficiary findUnique
 */
export type BeneficiaryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Beneficiary
   */
  select?: Prisma.BeneficiarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Beneficiary
   */
  omit?: Prisma.BeneficiaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BeneficiaryInclude<ExtArgs> | null
  /**
   * Filter, which Beneficiary to fetch.
   */
  where: Prisma.BeneficiaryWhereUniqueInput
}

/**
 * Beneficiary findUniqueOrThrow
 */
export type BeneficiaryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Beneficiary
   */
  select?: Prisma.BeneficiarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Beneficiary
   */
  omit?: Prisma.BeneficiaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BeneficiaryInclude<ExtArgs> | null
  /**
   * Filter, which Beneficiary to fetch.
   */
  where: Prisma.BeneficiaryWhereUniqueInput
}

/**
 * Beneficiary findFirst
 */
export type BeneficiaryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Beneficiary
   */
  select?: Prisma.BeneficiarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Beneficiary
   */
  omit?: Prisma.BeneficiaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BeneficiaryInclude<ExtArgs> | null
  /**
   * Filter, which Beneficiary to fetch.
   */
  where?: Prisma.BeneficiaryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Beneficiaries to fetch.
   */
  orderBy?: Prisma.BeneficiaryOrderByWithRelationInput | Prisma.BeneficiaryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Beneficiaries.
   */
  cursor?: Prisma.BeneficiaryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Beneficiaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Beneficiaries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Beneficiaries.
   */
  distinct?: Prisma.BeneficiaryScalarFieldEnum | Prisma.BeneficiaryScalarFieldEnum[]
}

/**
 * Beneficiary findFirstOrThrow
 */
export type BeneficiaryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Beneficiary
   */
  select?: Prisma.BeneficiarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Beneficiary
   */
  omit?: Prisma.BeneficiaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BeneficiaryInclude<ExtArgs> | null
  /**
   * Filter, which Beneficiary to fetch.
   */
  where?: Prisma.BeneficiaryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Beneficiaries to fetch.
   */
  orderBy?: Prisma.BeneficiaryOrderByWithRelationInput | Prisma.BeneficiaryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Beneficiaries.
   */
  cursor?: Prisma.BeneficiaryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Beneficiaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Beneficiaries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Beneficiaries.
   */
  distinct?: Prisma.BeneficiaryScalarFieldEnum | Prisma.BeneficiaryScalarFieldEnum[]
}

/**
 * Beneficiary findMany
 */
export type BeneficiaryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Beneficiary
   */
  select?: Prisma.BeneficiarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Beneficiary
   */
  omit?: Prisma.BeneficiaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BeneficiaryInclude<ExtArgs> | null
  /**
   * Filter, which Beneficiaries to fetch.
   */
  where?: Prisma.BeneficiaryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Beneficiaries to fetch.
   */
  orderBy?: Prisma.BeneficiaryOrderByWithRelationInput | Prisma.BeneficiaryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Beneficiaries.
   */
  cursor?: Prisma.BeneficiaryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Beneficiaries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Beneficiaries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Beneficiaries.
   */
  distinct?: Prisma.BeneficiaryScalarFieldEnum | Prisma.BeneficiaryScalarFieldEnum[]
}

/**
 * Beneficiary create
 */
export type BeneficiaryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Beneficiary
   */
  select?: Prisma.BeneficiarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Beneficiary
   */
  omit?: Prisma.BeneficiaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BeneficiaryInclude<ExtArgs> | null
  /**
   * The data needed to create a Beneficiary.
   */
  data: Prisma.XOR<Prisma.BeneficiaryCreateInput, Prisma.BeneficiaryUncheckedCreateInput>
}

/**
 * Beneficiary createMany
 */
export type BeneficiaryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Beneficiaries.
   */
  data: Prisma.BeneficiaryCreateManyInput | Prisma.BeneficiaryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Beneficiary createManyAndReturn
 */
export type BeneficiaryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Beneficiary
   */
  select?: Prisma.BeneficiarySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Beneficiary
   */
  omit?: Prisma.BeneficiaryOmit<ExtArgs> | null
  /**
   * The data used to create many Beneficiaries.
   */
  data: Prisma.BeneficiaryCreateManyInput | Prisma.BeneficiaryCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BeneficiaryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Beneficiary update
 */
export type BeneficiaryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Beneficiary
   */
  select?: Prisma.BeneficiarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Beneficiary
   */
  omit?: Prisma.BeneficiaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BeneficiaryInclude<ExtArgs> | null
  /**
   * The data needed to update a Beneficiary.
   */
  data: Prisma.XOR<Prisma.BeneficiaryUpdateInput, Prisma.BeneficiaryUncheckedUpdateInput>
  /**
   * Choose, which Beneficiary to update.
   */
  where: Prisma.BeneficiaryWhereUniqueInput
}

/**
 * Beneficiary updateMany
 */
export type BeneficiaryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Beneficiaries.
   */
  data: Prisma.XOR<Prisma.BeneficiaryUpdateManyMutationInput, Prisma.BeneficiaryUncheckedUpdateManyInput>
  /**
   * Filter which Beneficiaries to update
   */
  where?: Prisma.BeneficiaryWhereInput
  /**
   * Limit how many Beneficiaries to update.
   */
  limit?: number
}

/**
 * Beneficiary updateManyAndReturn
 */
export type BeneficiaryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Beneficiary
   */
  select?: Prisma.BeneficiarySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Beneficiary
   */
  omit?: Prisma.BeneficiaryOmit<ExtArgs> | null
  /**
   * The data used to update Beneficiaries.
   */
  data: Prisma.XOR<Prisma.BeneficiaryUpdateManyMutationInput, Prisma.BeneficiaryUncheckedUpdateManyInput>
  /**
   * Filter which Beneficiaries to update
   */
  where?: Prisma.BeneficiaryWhereInput
  /**
   * Limit how many Beneficiaries to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BeneficiaryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Beneficiary upsert
 */
export type BeneficiaryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Beneficiary
   */
  select?: Prisma.BeneficiarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Beneficiary
   */
  omit?: Prisma.BeneficiaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BeneficiaryInclude<ExtArgs> | null
  /**
   * The filter to search for the Beneficiary to update in case it exists.
   */
  where: Prisma.BeneficiaryWhereUniqueInput
  /**
   * In case the Beneficiary found by the `where` argument doesn't exist, create a new Beneficiary with this data.
   */
  create: Prisma.XOR<Prisma.BeneficiaryCreateInput, Prisma.BeneficiaryUncheckedCreateInput>
  /**
   * In case the Beneficiary was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BeneficiaryUpdateInput, Prisma.BeneficiaryUncheckedUpdateInput>
}

/**
 * Beneficiary delete
 */
export type BeneficiaryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Beneficiary
   */
  select?: Prisma.BeneficiarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Beneficiary
   */
  omit?: Prisma.BeneficiaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BeneficiaryInclude<ExtArgs> | null
  /**
   * Filter which Beneficiary to delete.
   */
  where: Prisma.BeneficiaryWhereUniqueInput
}

/**
 * Beneficiary deleteMany
 */
export type BeneficiaryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Beneficiaries to delete
   */
  where?: Prisma.BeneficiaryWhereInput
  /**
   * Limit how many Beneficiaries to delete.
   */
  limit?: number
}

/**
 * Beneficiary without action
 */
export type BeneficiaryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Beneficiary
   */
  select?: Prisma.BeneficiarySelect<ExtArgs> | null
  /**
   * Omit specific fields from the Beneficiary
   */
  omit?: Prisma.BeneficiaryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BeneficiaryInclude<ExtArgs> | null
}
