
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `DocumentReference` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model DocumentReference
 * 
 */
export type DocumentReferenceModel = runtime.Types.Result.DefaultSelection<Prisma.$DocumentReferencePayload>

export type AggregateDocumentReference = {
  _count: DocumentReferenceCountAggregateOutputType | null
  _avg: DocumentReferenceAvgAggregateOutputType | null
  _sum: DocumentReferenceSumAggregateOutputType | null
  _min: DocumentReferenceMinAggregateOutputType | null
  _max: DocumentReferenceMaxAggregateOutputType | null
}

export type DocumentReferenceAvgAggregateOutputType = {
  fileSize: number | null
}

export type DocumentReferenceSumAggregateOutputType = {
  fileSize: number | null
}

export type DocumentReferenceMinAggregateOutputType = {
  id: string | null
  fileName: string | null
  remotePath: string | null
  publicToken: string | null
  contentType: string | null
  fileSize: number | null
  isPublic: boolean | null
  uploadedById: string | null
  storageOwnerSub: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type DocumentReferenceMaxAggregateOutputType = {
  id: string | null
  fileName: string | null
  remotePath: string | null
  publicToken: string | null
  contentType: string | null
  fileSize: number | null
  isPublic: boolean | null
  uploadedById: string | null
  storageOwnerSub: string | null
  createdAt: Date | null
  updatedAt: Date | null
  deletedAt: Date | null
}

export type DocumentReferenceCountAggregateOutputType = {
  id: number
  fileName: number
  remotePath: number
  publicToken: number
  contentType: number
  fileSize: number
  isPublic: number
  uploadedById: number
  storageOwnerSub: number
  createdAt: number
  updatedAt: number
  deletedAt: number
  _all: number
}


export type DocumentReferenceAvgAggregateInputType = {
  fileSize?: true
}

export type DocumentReferenceSumAggregateInputType = {
  fileSize?: true
}

export type DocumentReferenceMinAggregateInputType = {
  id?: true
  fileName?: true
  remotePath?: true
  publicToken?: true
  contentType?: true
  fileSize?: true
  isPublic?: true
  uploadedById?: true
  storageOwnerSub?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type DocumentReferenceMaxAggregateInputType = {
  id?: true
  fileName?: true
  remotePath?: true
  publicToken?: true
  contentType?: true
  fileSize?: true
  isPublic?: true
  uploadedById?: true
  storageOwnerSub?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
}

export type DocumentReferenceCountAggregateInputType = {
  id?: true
  fileName?: true
  remotePath?: true
  publicToken?: true
  contentType?: true
  fileSize?: true
  isPublic?: true
  uploadedById?: true
  storageOwnerSub?: true
  createdAt?: true
  updatedAt?: true
  deletedAt?: true
  _all?: true
}

export type DocumentReferenceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DocumentReference to aggregate.
   */
  where?: Prisma.DocumentReferenceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DocumentReferences to fetch.
   */
  orderBy?: Prisma.DocumentReferenceOrderByWithRelationInput | Prisma.DocumentReferenceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.DocumentReferenceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DocumentReferences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DocumentReferences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned DocumentReferences
  **/
  _count?: true | DocumentReferenceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DocumentReferenceAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DocumentReferenceSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DocumentReferenceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DocumentReferenceMaxAggregateInputType
}

export type GetDocumentReferenceAggregateType<T extends DocumentReferenceAggregateArgs> = {
      [P in keyof T & keyof AggregateDocumentReference]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDocumentReference[P]>
    : Prisma.GetScalarType<T[P], AggregateDocumentReference[P]>
}




export type DocumentReferenceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DocumentReferenceWhereInput
  orderBy?: Prisma.DocumentReferenceOrderByWithAggregationInput | Prisma.DocumentReferenceOrderByWithAggregationInput[]
  by: Prisma.DocumentReferenceScalarFieldEnum[] | Prisma.DocumentReferenceScalarFieldEnum
  having?: Prisma.DocumentReferenceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DocumentReferenceCountAggregateInputType | true
  _avg?: DocumentReferenceAvgAggregateInputType
  _sum?: DocumentReferenceSumAggregateInputType
  _min?: DocumentReferenceMinAggregateInputType
  _max?: DocumentReferenceMaxAggregateInputType
}

export type DocumentReferenceGroupByOutputType = {
  id: string
  fileName: string
  remotePath: string
  publicToken: string | null
  contentType: string
  fileSize: number | null
  isPublic: boolean
  uploadedById: string | null
  storageOwnerSub: string | null
  createdAt: Date
  updatedAt: Date
  deletedAt: Date | null
  _count: DocumentReferenceCountAggregateOutputType | null
  _avg: DocumentReferenceAvgAggregateOutputType | null
  _sum: DocumentReferenceSumAggregateOutputType | null
  _min: DocumentReferenceMinAggregateOutputType | null
  _max: DocumentReferenceMaxAggregateOutputType | null
}

export type GetDocumentReferenceGroupByPayload<T extends DocumentReferenceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DocumentReferenceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DocumentReferenceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DocumentReferenceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DocumentReferenceGroupByOutputType[P]>
      }
    >
  >



export type DocumentReferenceWhereInput = {
  AND?: Prisma.DocumentReferenceWhereInput | Prisma.DocumentReferenceWhereInput[]
  OR?: Prisma.DocumentReferenceWhereInput[]
  NOT?: Prisma.DocumentReferenceWhereInput | Prisma.DocumentReferenceWhereInput[]
  id?: Prisma.StringFilter<"DocumentReference"> | string
  fileName?: Prisma.StringFilter<"DocumentReference"> | string
  remotePath?: Prisma.StringFilter<"DocumentReference"> | string
  publicToken?: Prisma.StringNullableFilter<"DocumentReference"> | string | null
  contentType?: Prisma.StringFilter<"DocumentReference"> | string
  fileSize?: Prisma.IntNullableFilter<"DocumentReference"> | number | null
  isPublic?: Prisma.BoolFilter<"DocumentReference"> | boolean
  uploadedById?: Prisma.StringNullableFilter<"DocumentReference"> | string | null
  storageOwnerSub?: Prisma.StringNullableFilter<"DocumentReference"> | string | null
  createdAt?: Prisma.DateTimeFilter<"DocumentReference"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DocumentReference"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"DocumentReference"> | Date | string | null
  mappings?: Prisma.DocumentMappingListRelationFilter
}

export type DocumentReferenceOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  remotePath?: Prisma.SortOrder
  publicToken?: Prisma.SortOrderInput | Prisma.SortOrder
  contentType?: Prisma.SortOrder
  fileSize?: Prisma.SortOrderInput | Prisma.SortOrder
  isPublic?: Prisma.SortOrder
  uploadedById?: Prisma.SortOrderInput | Prisma.SortOrder
  storageOwnerSub?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  mappings?: Prisma.DocumentMappingOrderByRelationAggregateInput
}

export type DocumentReferenceWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.DocumentReferenceWhereInput | Prisma.DocumentReferenceWhereInput[]
  OR?: Prisma.DocumentReferenceWhereInput[]
  NOT?: Prisma.DocumentReferenceWhereInput | Prisma.DocumentReferenceWhereInput[]
  fileName?: Prisma.StringFilter<"DocumentReference"> | string
  remotePath?: Prisma.StringFilter<"DocumentReference"> | string
  publicToken?: Prisma.StringNullableFilter<"DocumentReference"> | string | null
  contentType?: Prisma.StringFilter<"DocumentReference"> | string
  fileSize?: Prisma.IntNullableFilter<"DocumentReference"> | number | null
  isPublic?: Prisma.BoolFilter<"DocumentReference"> | boolean
  uploadedById?: Prisma.StringNullableFilter<"DocumentReference"> | string | null
  storageOwnerSub?: Prisma.StringNullableFilter<"DocumentReference"> | string | null
  createdAt?: Prisma.DateTimeFilter<"DocumentReference"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"DocumentReference"> | Date | string
  deletedAt?: Prisma.DateTimeNullableFilter<"DocumentReference"> | Date | string | null
  mappings?: Prisma.DocumentMappingListRelationFilter
}, "id">

export type DocumentReferenceOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  remotePath?: Prisma.SortOrder
  publicToken?: Prisma.SortOrderInput | Prisma.SortOrder
  contentType?: Prisma.SortOrder
  fileSize?: Prisma.SortOrderInput | Prisma.SortOrder
  isPublic?: Prisma.SortOrder
  uploadedById?: Prisma.SortOrderInput | Prisma.SortOrder
  storageOwnerSub?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.DocumentReferenceCountOrderByAggregateInput
  _avg?: Prisma.DocumentReferenceAvgOrderByAggregateInput
  _max?: Prisma.DocumentReferenceMaxOrderByAggregateInput
  _min?: Prisma.DocumentReferenceMinOrderByAggregateInput
  _sum?: Prisma.DocumentReferenceSumOrderByAggregateInput
}

export type DocumentReferenceScalarWhereWithAggregatesInput = {
  AND?: Prisma.DocumentReferenceScalarWhereWithAggregatesInput | Prisma.DocumentReferenceScalarWhereWithAggregatesInput[]
  OR?: Prisma.DocumentReferenceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.DocumentReferenceScalarWhereWithAggregatesInput | Prisma.DocumentReferenceScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"DocumentReference"> | string
  fileName?: Prisma.StringWithAggregatesFilter<"DocumentReference"> | string
  remotePath?: Prisma.StringWithAggregatesFilter<"DocumentReference"> | string
  publicToken?: Prisma.StringNullableWithAggregatesFilter<"DocumentReference"> | string | null
  contentType?: Prisma.StringWithAggregatesFilter<"DocumentReference"> | string
  fileSize?: Prisma.IntNullableWithAggregatesFilter<"DocumentReference"> | number | null
  isPublic?: Prisma.BoolWithAggregatesFilter<"DocumentReference"> | boolean
  uploadedById?: Prisma.StringNullableWithAggregatesFilter<"DocumentReference"> | string | null
  storageOwnerSub?: Prisma.StringNullableWithAggregatesFilter<"DocumentReference"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"DocumentReference"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"DocumentReference"> | Date | string
  deletedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"DocumentReference"> | Date | string | null
}

export type DocumentReferenceCreateInput = {
  id?: string
  fileName: string
  remotePath: string
  publicToken?: string | null
  contentType: string
  fileSize?: number | null
  isPublic?: boolean
  uploadedById?: string | null
  storageOwnerSub?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  mappings?: Prisma.DocumentMappingCreateNestedManyWithoutDocumentInput
}

export type DocumentReferenceUncheckedCreateInput = {
  id?: string
  fileName: string
  remotePath: string
  publicToken?: string | null
  contentType: string
  fileSize?: number | null
  isPublic?: boolean
  uploadedById?: string | null
  storageOwnerSub?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
  mappings?: Prisma.DocumentMappingUncheckedCreateNestedManyWithoutDocumentInput
}

export type DocumentReferenceUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  remotePath?: Prisma.StringFieldUpdateOperationsInput | string
  publicToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contentType?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  uploadedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  storageOwnerSub?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  mappings?: Prisma.DocumentMappingUpdateManyWithoutDocumentNestedInput
}

export type DocumentReferenceUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  remotePath?: Prisma.StringFieldUpdateOperationsInput | string
  publicToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contentType?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  uploadedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  storageOwnerSub?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  mappings?: Prisma.DocumentMappingUncheckedUpdateManyWithoutDocumentNestedInput
}

export type DocumentReferenceCreateManyInput = {
  id?: string
  fileName: string
  remotePath: string
  publicToken?: string | null
  contentType: string
  fileSize?: number | null
  isPublic?: boolean
  uploadedById?: string | null
  storageOwnerSub?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type DocumentReferenceUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  remotePath?: Prisma.StringFieldUpdateOperationsInput | string
  publicToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contentType?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  uploadedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  storageOwnerSub?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type DocumentReferenceUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  remotePath?: Prisma.StringFieldUpdateOperationsInput | string
  publicToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contentType?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  uploadedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  storageOwnerSub?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type DocumentReferenceCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  remotePath?: Prisma.SortOrder
  publicToken?: Prisma.SortOrder
  contentType?: Prisma.SortOrder
  fileSize?: Prisma.SortOrder
  isPublic?: Prisma.SortOrder
  uploadedById?: Prisma.SortOrder
  storageOwnerSub?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type DocumentReferenceAvgOrderByAggregateInput = {
  fileSize?: Prisma.SortOrder
}

export type DocumentReferenceMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  remotePath?: Prisma.SortOrder
  publicToken?: Prisma.SortOrder
  contentType?: Prisma.SortOrder
  fileSize?: Prisma.SortOrder
  isPublic?: Prisma.SortOrder
  uploadedById?: Prisma.SortOrder
  storageOwnerSub?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type DocumentReferenceMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  fileName?: Prisma.SortOrder
  remotePath?: Prisma.SortOrder
  publicToken?: Prisma.SortOrder
  contentType?: Prisma.SortOrder
  fileSize?: Prisma.SortOrder
  isPublic?: Prisma.SortOrder
  uploadedById?: Prisma.SortOrder
  storageOwnerSub?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  deletedAt?: Prisma.SortOrder
}

export type DocumentReferenceSumOrderByAggregateInput = {
  fileSize?: Prisma.SortOrder
}

export type DocumentReferenceScalarRelationFilter = {
  is?: Prisma.DocumentReferenceWhereInput
  isNot?: Prisma.DocumentReferenceWhereInput
}

export type DocumentReferenceCreateNestedOneWithoutMappingsInput = {
  create?: Prisma.XOR<Prisma.DocumentReferenceCreateWithoutMappingsInput, Prisma.DocumentReferenceUncheckedCreateWithoutMappingsInput>
  connectOrCreate?: Prisma.DocumentReferenceCreateOrConnectWithoutMappingsInput
  connect?: Prisma.DocumentReferenceWhereUniqueInput
}

export type DocumentReferenceUpdateOneRequiredWithoutMappingsNestedInput = {
  create?: Prisma.XOR<Prisma.DocumentReferenceCreateWithoutMappingsInput, Prisma.DocumentReferenceUncheckedCreateWithoutMappingsInput>
  connectOrCreate?: Prisma.DocumentReferenceCreateOrConnectWithoutMappingsInput
  upsert?: Prisma.DocumentReferenceUpsertWithoutMappingsInput
  connect?: Prisma.DocumentReferenceWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.DocumentReferenceUpdateToOneWithWhereWithoutMappingsInput, Prisma.DocumentReferenceUpdateWithoutMappingsInput>, Prisma.DocumentReferenceUncheckedUpdateWithoutMappingsInput>
}

export type DocumentReferenceCreateWithoutMappingsInput = {
  id?: string
  fileName: string
  remotePath: string
  publicToken?: string | null
  contentType: string
  fileSize?: number | null
  isPublic?: boolean
  uploadedById?: string | null
  storageOwnerSub?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type DocumentReferenceUncheckedCreateWithoutMappingsInput = {
  id?: string
  fileName: string
  remotePath: string
  publicToken?: string | null
  contentType: string
  fileSize?: number | null
  isPublic?: boolean
  uploadedById?: string | null
  storageOwnerSub?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  deletedAt?: Date | string | null
}

export type DocumentReferenceCreateOrConnectWithoutMappingsInput = {
  where: Prisma.DocumentReferenceWhereUniqueInput
  create: Prisma.XOR<Prisma.DocumentReferenceCreateWithoutMappingsInput, Prisma.DocumentReferenceUncheckedCreateWithoutMappingsInput>
}

export type DocumentReferenceUpsertWithoutMappingsInput = {
  update: Prisma.XOR<Prisma.DocumentReferenceUpdateWithoutMappingsInput, Prisma.DocumentReferenceUncheckedUpdateWithoutMappingsInput>
  create: Prisma.XOR<Prisma.DocumentReferenceCreateWithoutMappingsInput, Prisma.DocumentReferenceUncheckedCreateWithoutMappingsInput>
  where?: Prisma.DocumentReferenceWhereInput
}

export type DocumentReferenceUpdateToOneWithWhereWithoutMappingsInput = {
  where?: Prisma.DocumentReferenceWhereInput
  data: Prisma.XOR<Prisma.DocumentReferenceUpdateWithoutMappingsInput, Prisma.DocumentReferenceUncheckedUpdateWithoutMappingsInput>
}

export type DocumentReferenceUpdateWithoutMappingsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  remotePath?: Prisma.StringFieldUpdateOperationsInput | string
  publicToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contentType?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  uploadedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  storageOwnerSub?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type DocumentReferenceUncheckedUpdateWithoutMappingsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  fileName?: Prisma.StringFieldUpdateOperationsInput | string
  remotePath?: Prisma.StringFieldUpdateOperationsInput | string
  publicToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  contentType?: Prisma.StringFieldUpdateOperationsInput | string
  fileSize?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  isPublic?: Prisma.BoolFieldUpdateOperationsInput | boolean
  uploadedById?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  storageOwnerSub?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  deletedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type DocumentReferenceCountOutputType
 */

export type DocumentReferenceCountOutputType = {
  mappings: number
}

export type DocumentReferenceCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  mappings?: boolean | DocumentReferenceCountOutputTypeCountMappingsArgs
}

/**
 * DocumentReferenceCountOutputType without action
 */
export type DocumentReferenceCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentReferenceCountOutputType
   */
  select?: Prisma.DocumentReferenceCountOutputTypeSelect<ExtArgs> | null
}

/**
 * DocumentReferenceCountOutputType without action
 */
export type DocumentReferenceCountOutputTypeCountMappingsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.DocumentMappingWhereInput
}


export type DocumentReferenceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fileName?: boolean
  remotePath?: boolean
  publicToken?: boolean
  contentType?: boolean
  fileSize?: boolean
  isPublic?: boolean
  uploadedById?: boolean
  storageOwnerSub?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
  mappings?: boolean | Prisma.DocumentReference$mappingsArgs<ExtArgs>
  _count?: boolean | Prisma.DocumentReferenceCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["documentReference"]>

export type DocumentReferenceSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fileName?: boolean
  remotePath?: boolean
  publicToken?: boolean
  contentType?: boolean
  fileSize?: boolean
  isPublic?: boolean
  uploadedById?: boolean
  storageOwnerSub?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}, ExtArgs["result"]["documentReference"]>

export type DocumentReferenceSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  fileName?: boolean
  remotePath?: boolean
  publicToken?: boolean
  contentType?: boolean
  fileSize?: boolean
  isPublic?: boolean
  uploadedById?: boolean
  storageOwnerSub?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}, ExtArgs["result"]["documentReference"]>

export type DocumentReferenceSelectScalar = {
  id?: boolean
  fileName?: boolean
  remotePath?: boolean
  publicToken?: boolean
  contentType?: boolean
  fileSize?: boolean
  isPublic?: boolean
  uploadedById?: boolean
  storageOwnerSub?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  deletedAt?: boolean
}

export type DocumentReferenceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "fileName" | "remotePath" | "publicToken" | "contentType" | "fileSize" | "isPublic" | "uploadedById" | "storageOwnerSub" | "createdAt" | "updatedAt" | "deletedAt", ExtArgs["result"]["documentReference"]>
export type DocumentReferenceInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  mappings?: boolean | Prisma.DocumentReference$mappingsArgs<ExtArgs>
  _count?: boolean | Prisma.DocumentReferenceCountOutputTypeDefaultArgs<ExtArgs>
}
export type DocumentReferenceIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type DocumentReferenceIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $DocumentReferencePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "DocumentReference"
  objects: {
    mappings: Prisma.$DocumentMappingPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    fileName: string
    remotePath: string
    publicToken: string | null
    contentType: string
    fileSize: number | null
    isPublic: boolean
    uploadedById: string | null
    /**
     * Owning account (e.g. Google `sub`) for per-user storage providers such as Google Drive. Unused by Firebase.
     */
    storageOwnerSub: string | null
    createdAt: Date
    updatedAt: Date
    deletedAt: Date | null
  }, ExtArgs["result"]["documentReference"]>
  composites: {}
}

export type DocumentReferenceGetPayload<S extends boolean | null | undefined | DocumentReferenceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DocumentReferencePayload, S>

export type DocumentReferenceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<DocumentReferenceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DocumentReferenceCountAggregateInputType | true
  }

export interface DocumentReferenceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['DocumentReference'], meta: { name: 'DocumentReference' } }
  /**
   * Find zero or one DocumentReference that matches the filter.
   * @param {DocumentReferenceFindUniqueArgs} args - Arguments to find a DocumentReference
   * @example
   * // Get one DocumentReference
   * const documentReference = await prisma.documentReference.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends DocumentReferenceFindUniqueArgs>(args: Prisma.SelectSubset<T, DocumentReferenceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__DocumentReferenceClient<runtime.Types.Result.GetResult<Prisma.$DocumentReferencePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one DocumentReference that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {DocumentReferenceFindUniqueOrThrowArgs} args - Arguments to find a DocumentReference
   * @example
   * // Get one DocumentReference
   * const documentReference = await prisma.documentReference.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends DocumentReferenceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, DocumentReferenceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__DocumentReferenceClient<runtime.Types.Result.GetResult<Prisma.$DocumentReferencePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DocumentReference that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocumentReferenceFindFirstArgs} args - Arguments to find a DocumentReference
   * @example
   * // Get one DocumentReference
   * const documentReference = await prisma.documentReference.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends DocumentReferenceFindFirstArgs>(args?: Prisma.SelectSubset<T, DocumentReferenceFindFirstArgs<ExtArgs>>): Prisma.Prisma__DocumentReferenceClient<runtime.Types.Result.GetResult<Prisma.$DocumentReferencePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first DocumentReference that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocumentReferenceFindFirstOrThrowArgs} args - Arguments to find a DocumentReference
   * @example
   * // Get one DocumentReference
   * const documentReference = await prisma.documentReference.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends DocumentReferenceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, DocumentReferenceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__DocumentReferenceClient<runtime.Types.Result.GetResult<Prisma.$DocumentReferencePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more DocumentReferences that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocumentReferenceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all DocumentReferences
   * const documentReferences = await prisma.documentReference.findMany()
   * 
   * // Get first 10 DocumentReferences
   * const documentReferences = await prisma.documentReference.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const documentReferenceWithIdOnly = await prisma.documentReference.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends DocumentReferenceFindManyArgs>(args?: Prisma.SelectSubset<T, DocumentReferenceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DocumentReferencePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a DocumentReference.
   * @param {DocumentReferenceCreateArgs} args - Arguments to create a DocumentReference.
   * @example
   * // Create one DocumentReference
   * const DocumentReference = await prisma.documentReference.create({
   *   data: {
   *     // ... data to create a DocumentReference
   *   }
   * })
   * 
   */
  create<T extends DocumentReferenceCreateArgs>(args: Prisma.SelectSubset<T, DocumentReferenceCreateArgs<ExtArgs>>): Prisma.Prisma__DocumentReferenceClient<runtime.Types.Result.GetResult<Prisma.$DocumentReferencePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many DocumentReferences.
   * @param {DocumentReferenceCreateManyArgs} args - Arguments to create many DocumentReferences.
   * @example
   * // Create many DocumentReferences
   * const documentReference = await prisma.documentReference.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends DocumentReferenceCreateManyArgs>(args?: Prisma.SelectSubset<T, DocumentReferenceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many DocumentReferences and returns the data saved in the database.
   * @param {DocumentReferenceCreateManyAndReturnArgs} args - Arguments to create many DocumentReferences.
   * @example
   * // Create many DocumentReferences
   * const documentReference = await prisma.documentReference.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many DocumentReferences and only return the `id`
   * const documentReferenceWithIdOnly = await prisma.documentReference.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends DocumentReferenceCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, DocumentReferenceCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DocumentReferencePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a DocumentReference.
   * @param {DocumentReferenceDeleteArgs} args - Arguments to delete one DocumentReference.
   * @example
   * // Delete one DocumentReference
   * const DocumentReference = await prisma.documentReference.delete({
   *   where: {
   *     // ... filter to delete one DocumentReference
   *   }
   * })
   * 
   */
  delete<T extends DocumentReferenceDeleteArgs>(args: Prisma.SelectSubset<T, DocumentReferenceDeleteArgs<ExtArgs>>): Prisma.Prisma__DocumentReferenceClient<runtime.Types.Result.GetResult<Prisma.$DocumentReferencePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one DocumentReference.
   * @param {DocumentReferenceUpdateArgs} args - Arguments to update one DocumentReference.
   * @example
   * // Update one DocumentReference
   * const documentReference = await prisma.documentReference.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends DocumentReferenceUpdateArgs>(args: Prisma.SelectSubset<T, DocumentReferenceUpdateArgs<ExtArgs>>): Prisma.Prisma__DocumentReferenceClient<runtime.Types.Result.GetResult<Prisma.$DocumentReferencePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more DocumentReferences.
   * @param {DocumentReferenceDeleteManyArgs} args - Arguments to filter DocumentReferences to delete.
   * @example
   * // Delete a few DocumentReferences
   * const { count } = await prisma.documentReference.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends DocumentReferenceDeleteManyArgs>(args?: Prisma.SelectSubset<T, DocumentReferenceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DocumentReferences.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocumentReferenceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many DocumentReferences
   * const documentReference = await prisma.documentReference.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends DocumentReferenceUpdateManyArgs>(args: Prisma.SelectSubset<T, DocumentReferenceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more DocumentReferences and returns the data updated in the database.
   * @param {DocumentReferenceUpdateManyAndReturnArgs} args - Arguments to update many DocumentReferences.
   * @example
   * // Update many DocumentReferences
   * const documentReference = await prisma.documentReference.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more DocumentReferences and only return the `id`
   * const documentReferenceWithIdOnly = await prisma.documentReference.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends DocumentReferenceUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, DocumentReferenceUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DocumentReferencePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one DocumentReference.
   * @param {DocumentReferenceUpsertArgs} args - Arguments to update or create a DocumentReference.
   * @example
   * // Update or create a DocumentReference
   * const documentReference = await prisma.documentReference.upsert({
   *   create: {
   *     // ... data to create a DocumentReference
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the DocumentReference we want to update
   *   }
   * })
   */
  upsert<T extends DocumentReferenceUpsertArgs>(args: Prisma.SelectSubset<T, DocumentReferenceUpsertArgs<ExtArgs>>): Prisma.Prisma__DocumentReferenceClient<runtime.Types.Result.GetResult<Prisma.$DocumentReferencePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of DocumentReferences.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocumentReferenceCountArgs} args - Arguments to filter DocumentReferences to count.
   * @example
   * // Count the number of DocumentReferences
   * const count = await prisma.documentReference.count({
   *   where: {
   *     // ... the filter for the DocumentReferences we want to count
   *   }
   * })
  **/
  count<T extends DocumentReferenceCountArgs>(
    args?: Prisma.Subset<T, DocumentReferenceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DocumentReferenceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a DocumentReference.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocumentReferenceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DocumentReferenceAggregateArgs>(args: Prisma.Subset<T, DocumentReferenceAggregateArgs>): Prisma.PrismaPromise<GetDocumentReferenceAggregateType<T>>

  /**
   * Group by DocumentReference.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DocumentReferenceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends DocumentReferenceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: DocumentReferenceGroupByArgs['orderBy'] }
      : { orderBy?: DocumentReferenceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, DocumentReferenceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDocumentReferenceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the DocumentReference model
 */
readonly fields: DocumentReferenceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for DocumentReference.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__DocumentReferenceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  mappings<T extends Prisma.DocumentReference$mappingsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.DocumentReference$mappingsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$DocumentMappingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the DocumentReference model
 */
export interface DocumentReferenceFieldRefs {
  readonly id: Prisma.FieldRef<"DocumentReference", 'String'>
  readonly fileName: Prisma.FieldRef<"DocumentReference", 'String'>
  readonly remotePath: Prisma.FieldRef<"DocumentReference", 'String'>
  readonly publicToken: Prisma.FieldRef<"DocumentReference", 'String'>
  readonly contentType: Prisma.FieldRef<"DocumentReference", 'String'>
  readonly fileSize: Prisma.FieldRef<"DocumentReference", 'Int'>
  readonly isPublic: Prisma.FieldRef<"DocumentReference", 'Boolean'>
  readonly uploadedById: Prisma.FieldRef<"DocumentReference", 'String'>
  readonly storageOwnerSub: Prisma.FieldRef<"DocumentReference", 'String'>
  readonly createdAt: Prisma.FieldRef<"DocumentReference", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"DocumentReference", 'DateTime'>
  readonly deletedAt: Prisma.FieldRef<"DocumentReference", 'DateTime'>
}
    

// Custom InputTypes
/**
 * DocumentReference findUnique
 */
export type DocumentReferenceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentReference
   */
  select?: Prisma.DocumentReferenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentReference
   */
  omit?: Prisma.DocumentReferenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentReferenceInclude<ExtArgs> | null
  /**
   * Filter, which DocumentReference to fetch.
   */
  where: Prisma.DocumentReferenceWhereUniqueInput
}

/**
 * DocumentReference findUniqueOrThrow
 */
export type DocumentReferenceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentReference
   */
  select?: Prisma.DocumentReferenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentReference
   */
  omit?: Prisma.DocumentReferenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentReferenceInclude<ExtArgs> | null
  /**
   * Filter, which DocumentReference to fetch.
   */
  where: Prisma.DocumentReferenceWhereUniqueInput
}

/**
 * DocumentReference findFirst
 */
export type DocumentReferenceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentReference
   */
  select?: Prisma.DocumentReferenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentReference
   */
  omit?: Prisma.DocumentReferenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentReferenceInclude<ExtArgs> | null
  /**
   * Filter, which DocumentReference to fetch.
   */
  where?: Prisma.DocumentReferenceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DocumentReferences to fetch.
   */
  orderBy?: Prisma.DocumentReferenceOrderByWithRelationInput | Prisma.DocumentReferenceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DocumentReferences.
   */
  cursor?: Prisma.DocumentReferenceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DocumentReferences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DocumentReferences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DocumentReferences.
   */
  distinct?: Prisma.DocumentReferenceScalarFieldEnum | Prisma.DocumentReferenceScalarFieldEnum[]
}

/**
 * DocumentReference findFirstOrThrow
 */
export type DocumentReferenceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentReference
   */
  select?: Prisma.DocumentReferenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentReference
   */
  omit?: Prisma.DocumentReferenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentReferenceInclude<ExtArgs> | null
  /**
   * Filter, which DocumentReference to fetch.
   */
  where?: Prisma.DocumentReferenceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DocumentReferences to fetch.
   */
  orderBy?: Prisma.DocumentReferenceOrderByWithRelationInput | Prisma.DocumentReferenceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for DocumentReferences.
   */
  cursor?: Prisma.DocumentReferenceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DocumentReferences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DocumentReferences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DocumentReferences.
   */
  distinct?: Prisma.DocumentReferenceScalarFieldEnum | Prisma.DocumentReferenceScalarFieldEnum[]
}

/**
 * DocumentReference findMany
 */
export type DocumentReferenceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentReference
   */
  select?: Prisma.DocumentReferenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentReference
   */
  omit?: Prisma.DocumentReferenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentReferenceInclude<ExtArgs> | null
  /**
   * Filter, which DocumentReferences to fetch.
   */
  where?: Prisma.DocumentReferenceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of DocumentReferences to fetch.
   */
  orderBy?: Prisma.DocumentReferenceOrderByWithRelationInput | Prisma.DocumentReferenceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing DocumentReferences.
   */
  cursor?: Prisma.DocumentReferenceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` DocumentReferences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` DocumentReferences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of DocumentReferences.
   */
  distinct?: Prisma.DocumentReferenceScalarFieldEnum | Prisma.DocumentReferenceScalarFieldEnum[]
}

/**
 * DocumentReference create
 */
export type DocumentReferenceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentReference
   */
  select?: Prisma.DocumentReferenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentReference
   */
  omit?: Prisma.DocumentReferenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentReferenceInclude<ExtArgs> | null
  /**
   * The data needed to create a DocumentReference.
   */
  data: Prisma.XOR<Prisma.DocumentReferenceCreateInput, Prisma.DocumentReferenceUncheckedCreateInput>
}

/**
 * DocumentReference createMany
 */
export type DocumentReferenceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many DocumentReferences.
   */
  data: Prisma.DocumentReferenceCreateManyInput | Prisma.DocumentReferenceCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DocumentReference createManyAndReturn
 */
export type DocumentReferenceCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentReference
   */
  select?: Prisma.DocumentReferenceSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentReference
   */
  omit?: Prisma.DocumentReferenceOmit<ExtArgs> | null
  /**
   * The data used to create many DocumentReferences.
   */
  data: Prisma.DocumentReferenceCreateManyInput | Prisma.DocumentReferenceCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * DocumentReference update
 */
export type DocumentReferenceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentReference
   */
  select?: Prisma.DocumentReferenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentReference
   */
  omit?: Prisma.DocumentReferenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentReferenceInclude<ExtArgs> | null
  /**
   * The data needed to update a DocumentReference.
   */
  data: Prisma.XOR<Prisma.DocumentReferenceUpdateInput, Prisma.DocumentReferenceUncheckedUpdateInput>
  /**
   * Choose, which DocumentReference to update.
   */
  where: Prisma.DocumentReferenceWhereUniqueInput
}

/**
 * DocumentReference updateMany
 */
export type DocumentReferenceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update DocumentReferences.
   */
  data: Prisma.XOR<Prisma.DocumentReferenceUpdateManyMutationInput, Prisma.DocumentReferenceUncheckedUpdateManyInput>
  /**
   * Filter which DocumentReferences to update
   */
  where?: Prisma.DocumentReferenceWhereInput
  /**
   * Limit how many DocumentReferences to update.
   */
  limit?: number
}

/**
 * DocumentReference updateManyAndReturn
 */
export type DocumentReferenceUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentReference
   */
  select?: Prisma.DocumentReferenceSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentReference
   */
  omit?: Prisma.DocumentReferenceOmit<ExtArgs> | null
  /**
   * The data used to update DocumentReferences.
   */
  data: Prisma.XOR<Prisma.DocumentReferenceUpdateManyMutationInput, Prisma.DocumentReferenceUncheckedUpdateManyInput>
  /**
   * Filter which DocumentReferences to update
   */
  where?: Prisma.DocumentReferenceWhereInput
  /**
   * Limit how many DocumentReferences to update.
   */
  limit?: number
}

/**
 * DocumentReference upsert
 */
export type DocumentReferenceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentReference
   */
  select?: Prisma.DocumentReferenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentReference
   */
  omit?: Prisma.DocumentReferenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentReferenceInclude<ExtArgs> | null
  /**
   * The filter to search for the DocumentReference to update in case it exists.
   */
  where: Prisma.DocumentReferenceWhereUniqueInput
  /**
   * In case the DocumentReference found by the `where` argument doesn't exist, create a new DocumentReference with this data.
   */
  create: Prisma.XOR<Prisma.DocumentReferenceCreateInput, Prisma.DocumentReferenceUncheckedCreateInput>
  /**
   * In case the DocumentReference was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.DocumentReferenceUpdateInput, Prisma.DocumentReferenceUncheckedUpdateInput>
}

/**
 * DocumentReference delete
 */
export type DocumentReferenceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentReference
   */
  select?: Prisma.DocumentReferenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentReference
   */
  omit?: Prisma.DocumentReferenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentReferenceInclude<ExtArgs> | null
  /**
   * Filter which DocumentReference to delete.
   */
  where: Prisma.DocumentReferenceWhereUniqueInput
}

/**
 * DocumentReference deleteMany
 */
export type DocumentReferenceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which DocumentReferences to delete
   */
  where?: Prisma.DocumentReferenceWhereInput
  /**
   * Limit how many DocumentReferences to delete.
   */
  limit?: number
}

/**
 * DocumentReference.mappings
 */
export type DocumentReference$mappingsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentMapping
   */
  select?: Prisma.DocumentMappingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentMapping
   */
  omit?: Prisma.DocumentMappingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentMappingInclude<ExtArgs> | null
  where?: Prisma.DocumentMappingWhereInput
  orderBy?: Prisma.DocumentMappingOrderByWithRelationInput | Prisma.DocumentMappingOrderByWithRelationInput[]
  cursor?: Prisma.DocumentMappingWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.DocumentMappingScalarFieldEnum | Prisma.DocumentMappingScalarFieldEnum[]
}

/**
 * DocumentReference without action
 */
export type DocumentReferenceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DocumentReference
   */
  select?: Prisma.DocumentReferenceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DocumentReference
   */
  omit?: Prisma.DocumentReferenceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.DocumentReferenceInclude<ExtArgs> | null
}
