
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `FormFieldValueHistoryEntry` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model FormFieldValueHistoryEntry
 * 
 */
export type FormFieldValueHistoryEntryModel = runtime.Types.Result.DefaultSelection<Prisma.$FormFieldValueHistoryEntryPayload>

export type AggregateFormFieldValueHistoryEntry = {
  _count: FormFieldValueHistoryEntryCountAggregateOutputType | null
  _min: FormFieldValueHistoryEntryMinAggregateOutputType | null
  _max: FormFieldValueHistoryEntryMaxAggregateOutputType | null
}

export type FormFieldValueHistoryEntryMinAggregateOutputType = {
  id: string | null
  formFieldValueId: string | null
  entityType: string | null
  entityId: string | null
  formId: string | null
  fieldDefId: string | null
  oldValue: string | null
  newValue: string | null
  changedBy: string | null
  createdAt: Date | null
}

export type FormFieldValueHistoryEntryMaxAggregateOutputType = {
  id: string | null
  formFieldValueId: string | null
  entityType: string | null
  entityId: string | null
  formId: string | null
  fieldDefId: string | null
  oldValue: string | null
  newValue: string | null
  changedBy: string | null
  createdAt: Date | null
}

export type FormFieldValueHistoryEntryCountAggregateOutputType = {
  id: number
  formFieldValueId: number
  entityType: number
  entityId: number
  formId: number
  fieldDefId: number
  oldValue: number
  newValue: number
  changedBy: number
  createdAt: number
  _all: number
}


export type FormFieldValueHistoryEntryMinAggregateInputType = {
  id?: true
  formFieldValueId?: true
  entityType?: true
  entityId?: true
  formId?: true
  fieldDefId?: true
  oldValue?: true
  newValue?: true
  changedBy?: true
  createdAt?: true
}

export type FormFieldValueHistoryEntryMaxAggregateInputType = {
  id?: true
  formFieldValueId?: true
  entityType?: true
  entityId?: true
  formId?: true
  fieldDefId?: true
  oldValue?: true
  newValue?: true
  changedBy?: true
  createdAt?: true
}

export type FormFieldValueHistoryEntryCountAggregateInputType = {
  id?: true
  formFieldValueId?: true
  entityType?: true
  entityId?: true
  formId?: true
  fieldDefId?: true
  oldValue?: true
  newValue?: true
  changedBy?: true
  createdAt?: true
  _all?: true
}

export type FormFieldValueHistoryEntryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FormFieldValueHistoryEntry to aggregate.
   */
  where?: Prisma.FormFieldValueHistoryEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FormFieldValueHistoryEntries to fetch.
   */
  orderBy?: Prisma.FormFieldValueHistoryEntryOrderByWithRelationInput | Prisma.FormFieldValueHistoryEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FormFieldValueHistoryEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FormFieldValueHistoryEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FormFieldValueHistoryEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FormFieldValueHistoryEntries
  **/
  _count?: true | FormFieldValueHistoryEntryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FormFieldValueHistoryEntryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FormFieldValueHistoryEntryMaxAggregateInputType
}

export type GetFormFieldValueHistoryEntryAggregateType<T extends FormFieldValueHistoryEntryAggregateArgs> = {
      [P in keyof T & keyof AggregateFormFieldValueHistoryEntry]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFormFieldValueHistoryEntry[P]>
    : Prisma.GetScalarType<T[P], AggregateFormFieldValueHistoryEntry[P]>
}




export type FormFieldValueHistoryEntryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FormFieldValueHistoryEntryWhereInput
  orderBy?: Prisma.FormFieldValueHistoryEntryOrderByWithAggregationInput | Prisma.FormFieldValueHistoryEntryOrderByWithAggregationInput[]
  by: Prisma.FormFieldValueHistoryEntryScalarFieldEnum[] | Prisma.FormFieldValueHistoryEntryScalarFieldEnum
  having?: Prisma.FormFieldValueHistoryEntryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FormFieldValueHistoryEntryCountAggregateInputType | true
  _min?: FormFieldValueHistoryEntryMinAggregateInputType
  _max?: FormFieldValueHistoryEntryMaxAggregateInputType
}

export type FormFieldValueHistoryEntryGroupByOutputType = {
  id: string
  formFieldValueId: string
  entityType: string
  entityId: string
  formId: string
  fieldDefId: string
  oldValue: string | null
  newValue: string | null
  changedBy: string | null
  createdAt: Date
  _count: FormFieldValueHistoryEntryCountAggregateOutputType | null
  _min: FormFieldValueHistoryEntryMinAggregateOutputType | null
  _max: FormFieldValueHistoryEntryMaxAggregateOutputType | null
}

export type GetFormFieldValueHistoryEntryGroupByPayload<T extends FormFieldValueHistoryEntryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FormFieldValueHistoryEntryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FormFieldValueHistoryEntryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FormFieldValueHistoryEntryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FormFieldValueHistoryEntryGroupByOutputType[P]>
      }
    >
  >



export type FormFieldValueHistoryEntryWhereInput = {
  AND?: Prisma.FormFieldValueHistoryEntryWhereInput | Prisma.FormFieldValueHistoryEntryWhereInput[]
  OR?: Prisma.FormFieldValueHistoryEntryWhereInput[]
  NOT?: Prisma.FormFieldValueHistoryEntryWhereInput | Prisma.FormFieldValueHistoryEntryWhereInput[]
  id?: Prisma.StringFilter<"FormFieldValueHistoryEntry"> | string
  formFieldValueId?: Prisma.StringFilter<"FormFieldValueHistoryEntry"> | string
  entityType?: Prisma.StringFilter<"FormFieldValueHistoryEntry"> | string
  entityId?: Prisma.StringFilter<"FormFieldValueHistoryEntry"> | string
  formId?: Prisma.StringFilter<"FormFieldValueHistoryEntry"> | string
  fieldDefId?: Prisma.StringFilter<"FormFieldValueHistoryEntry"> | string
  oldValue?: Prisma.StringNullableFilter<"FormFieldValueHistoryEntry"> | string | null
  newValue?: Prisma.StringNullableFilter<"FormFieldValueHistoryEntry"> | string | null
  changedBy?: Prisma.StringNullableFilter<"FormFieldValueHistoryEntry"> | string | null
  createdAt?: Prisma.DateTimeFilter<"FormFieldValueHistoryEntry"> | Date | string
  formFieldValue?: Prisma.XOR<Prisma.FormFieldValueScalarRelationFilter, Prisma.FormFieldValueWhereInput>
}

export type FormFieldValueHistoryEntryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  formFieldValueId?: Prisma.SortOrder
  entityType?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  formId?: Prisma.SortOrder
  fieldDefId?: Prisma.SortOrder
  oldValue?: Prisma.SortOrderInput | Prisma.SortOrder
  newValue?: Prisma.SortOrderInput | Prisma.SortOrder
  changedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  formFieldValue?: Prisma.FormFieldValueOrderByWithRelationInput
}

export type FormFieldValueHistoryEntryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.FormFieldValueHistoryEntryWhereInput | Prisma.FormFieldValueHistoryEntryWhereInput[]
  OR?: Prisma.FormFieldValueHistoryEntryWhereInput[]
  NOT?: Prisma.FormFieldValueHistoryEntryWhereInput | Prisma.FormFieldValueHistoryEntryWhereInput[]
  formFieldValueId?: Prisma.StringFilter<"FormFieldValueHistoryEntry"> | string
  entityType?: Prisma.StringFilter<"FormFieldValueHistoryEntry"> | string
  entityId?: Prisma.StringFilter<"FormFieldValueHistoryEntry"> | string
  formId?: Prisma.StringFilter<"FormFieldValueHistoryEntry"> | string
  fieldDefId?: Prisma.StringFilter<"FormFieldValueHistoryEntry"> | string
  oldValue?: Prisma.StringNullableFilter<"FormFieldValueHistoryEntry"> | string | null
  newValue?: Prisma.StringNullableFilter<"FormFieldValueHistoryEntry"> | string | null
  changedBy?: Prisma.StringNullableFilter<"FormFieldValueHistoryEntry"> | string | null
  createdAt?: Prisma.DateTimeFilter<"FormFieldValueHistoryEntry"> | Date | string
  formFieldValue?: Prisma.XOR<Prisma.FormFieldValueScalarRelationFilter, Prisma.FormFieldValueWhereInput>
}, "id">

export type FormFieldValueHistoryEntryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  formFieldValueId?: Prisma.SortOrder
  entityType?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  formId?: Prisma.SortOrder
  fieldDefId?: Prisma.SortOrder
  oldValue?: Prisma.SortOrderInput | Prisma.SortOrder
  newValue?: Prisma.SortOrderInput | Prisma.SortOrder
  changedBy?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.FormFieldValueHistoryEntryCountOrderByAggregateInput
  _max?: Prisma.FormFieldValueHistoryEntryMaxOrderByAggregateInput
  _min?: Prisma.FormFieldValueHistoryEntryMinOrderByAggregateInput
}

export type FormFieldValueHistoryEntryScalarWhereWithAggregatesInput = {
  AND?: Prisma.FormFieldValueHistoryEntryScalarWhereWithAggregatesInput | Prisma.FormFieldValueHistoryEntryScalarWhereWithAggregatesInput[]
  OR?: Prisma.FormFieldValueHistoryEntryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FormFieldValueHistoryEntryScalarWhereWithAggregatesInput | Prisma.FormFieldValueHistoryEntryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FormFieldValueHistoryEntry"> | string
  formFieldValueId?: Prisma.StringWithAggregatesFilter<"FormFieldValueHistoryEntry"> | string
  entityType?: Prisma.StringWithAggregatesFilter<"FormFieldValueHistoryEntry"> | string
  entityId?: Prisma.StringWithAggregatesFilter<"FormFieldValueHistoryEntry"> | string
  formId?: Prisma.StringWithAggregatesFilter<"FormFieldValueHistoryEntry"> | string
  fieldDefId?: Prisma.StringWithAggregatesFilter<"FormFieldValueHistoryEntry"> | string
  oldValue?: Prisma.StringNullableWithAggregatesFilter<"FormFieldValueHistoryEntry"> | string | null
  newValue?: Prisma.StringNullableWithAggregatesFilter<"FormFieldValueHistoryEntry"> | string | null
  changedBy?: Prisma.StringNullableWithAggregatesFilter<"FormFieldValueHistoryEntry"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"FormFieldValueHistoryEntry"> | Date | string
}

export type FormFieldValueHistoryEntryCreateInput = {
  id?: string
  entityType: string
  entityId: string
  formId: string
  fieldDefId: string
  oldValue?: string | null
  newValue?: string | null
  changedBy?: string | null
  createdAt?: Date | string
  formFieldValue: Prisma.FormFieldValueCreateNestedOneWithoutHistoryEntriesInput
}

export type FormFieldValueHistoryEntryUncheckedCreateInput = {
  id?: string
  formFieldValueId: string
  entityType: string
  entityId: string
  formId: string
  fieldDefId: string
  oldValue?: string | null
  newValue?: string | null
  changedBy?: string | null
  createdAt?: Date | string
}

export type FormFieldValueHistoryEntryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entityType?: Prisma.StringFieldUpdateOperationsInput | string
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  formId?: Prisma.StringFieldUpdateOperationsInput | string
  fieldDefId?: Prisma.StringFieldUpdateOperationsInput | string
  oldValue?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  newValue?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  changedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  formFieldValue?: Prisma.FormFieldValueUpdateOneRequiredWithoutHistoryEntriesNestedInput
}

export type FormFieldValueHistoryEntryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  formFieldValueId?: Prisma.StringFieldUpdateOperationsInput | string
  entityType?: Prisma.StringFieldUpdateOperationsInput | string
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  formId?: Prisma.StringFieldUpdateOperationsInput | string
  fieldDefId?: Prisma.StringFieldUpdateOperationsInput | string
  oldValue?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  newValue?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  changedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FormFieldValueHistoryEntryCreateManyInput = {
  id?: string
  formFieldValueId: string
  entityType: string
  entityId: string
  formId: string
  fieldDefId: string
  oldValue?: string | null
  newValue?: string | null
  changedBy?: string | null
  createdAt?: Date | string
}

export type FormFieldValueHistoryEntryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entityType?: Prisma.StringFieldUpdateOperationsInput | string
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  formId?: Prisma.StringFieldUpdateOperationsInput | string
  fieldDefId?: Prisma.StringFieldUpdateOperationsInput | string
  oldValue?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  newValue?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  changedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FormFieldValueHistoryEntryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  formFieldValueId?: Prisma.StringFieldUpdateOperationsInput | string
  entityType?: Prisma.StringFieldUpdateOperationsInput | string
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  formId?: Prisma.StringFieldUpdateOperationsInput | string
  fieldDefId?: Prisma.StringFieldUpdateOperationsInput | string
  oldValue?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  newValue?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  changedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FormFieldValueHistoryEntryListRelationFilter = {
  every?: Prisma.FormFieldValueHistoryEntryWhereInput
  some?: Prisma.FormFieldValueHistoryEntryWhereInput
  none?: Prisma.FormFieldValueHistoryEntryWhereInput
}

export type FormFieldValueHistoryEntryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FormFieldValueHistoryEntryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  formFieldValueId?: Prisma.SortOrder
  entityType?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  formId?: Prisma.SortOrder
  fieldDefId?: Prisma.SortOrder
  oldValue?: Prisma.SortOrder
  newValue?: Prisma.SortOrder
  changedBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type FormFieldValueHistoryEntryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  formFieldValueId?: Prisma.SortOrder
  entityType?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  formId?: Prisma.SortOrder
  fieldDefId?: Prisma.SortOrder
  oldValue?: Prisma.SortOrder
  newValue?: Prisma.SortOrder
  changedBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type FormFieldValueHistoryEntryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  formFieldValueId?: Prisma.SortOrder
  entityType?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  formId?: Prisma.SortOrder
  fieldDefId?: Prisma.SortOrder
  oldValue?: Prisma.SortOrder
  newValue?: Prisma.SortOrder
  changedBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type FormFieldValueHistoryEntryCreateNestedManyWithoutFormFieldValueInput = {
  create?: Prisma.XOR<Prisma.FormFieldValueHistoryEntryCreateWithoutFormFieldValueInput, Prisma.FormFieldValueHistoryEntryUncheckedCreateWithoutFormFieldValueInput> | Prisma.FormFieldValueHistoryEntryCreateWithoutFormFieldValueInput[] | Prisma.FormFieldValueHistoryEntryUncheckedCreateWithoutFormFieldValueInput[]
  connectOrCreate?: Prisma.FormFieldValueHistoryEntryCreateOrConnectWithoutFormFieldValueInput | Prisma.FormFieldValueHistoryEntryCreateOrConnectWithoutFormFieldValueInput[]
  createMany?: Prisma.FormFieldValueHistoryEntryCreateManyFormFieldValueInputEnvelope
  connect?: Prisma.FormFieldValueHistoryEntryWhereUniqueInput | Prisma.FormFieldValueHistoryEntryWhereUniqueInput[]
}

export type FormFieldValueHistoryEntryUncheckedCreateNestedManyWithoutFormFieldValueInput = {
  create?: Prisma.XOR<Prisma.FormFieldValueHistoryEntryCreateWithoutFormFieldValueInput, Prisma.FormFieldValueHistoryEntryUncheckedCreateWithoutFormFieldValueInput> | Prisma.FormFieldValueHistoryEntryCreateWithoutFormFieldValueInput[] | Prisma.FormFieldValueHistoryEntryUncheckedCreateWithoutFormFieldValueInput[]
  connectOrCreate?: Prisma.FormFieldValueHistoryEntryCreateOrConnectWithoutFormFieldValueInput | Prisma.FormFieldValueHistoryEntryCreateOrConnectWithoutFormFieldValueInput[]
  createMany?: Prisma.FormFieldValueHistoryEntryCreateManyFormFieldValueInputEnvelope
  connect?: Prisma.FormFieldValueHistoryEntryWhereUniqueInput | Prisma.FormFieldValueHistoryEntryWhereUniqueInput[]
}

export type FormFieldValueHistoryEntryUpdateManyWithoutFormFieldValueNestedInput = {
  create?: Prisma.XOR<Prisma.FormFieldValueHistoryEntryCreateWithoutFormFieldValueInput, Prisma.FormFieldValueHistoryEntryUncheckedCreateWithoutFormFieldValueInput> | Prisma.FormFieldValueHistoryEntryCreateWithoutFormFieldValueInput[] | Prisma.FormFieldValueHistoryEntryUncheckedCreateWithoutFormFieldValueInput[]
  connectOrCreate?: Prisma.FormFieldValueHistoryEntryCreateOrConnectWithoutFormFieldValueInput | Prisma.FormFieldValueHistoryEntryCreateOrConnectWithoutFormFieldValueInput[]
  upsert?: Prisma.FormFieldValueHistoryEntryUpsertWithWhereUniqueWithoutFormFieldValueInput | Prisma.FormFieldValueHistoryEntryUpsertWithWhereUniqueWithoutFormFieldValueInput[]
  createMany?: Prisma.FormFieldValueHistoryEntryCreateManyFormFieldValueInputEnvelope
  set?: Prisma.FormFieldValueHistoryEntryWhereUniqueInput | Prisma.FormFieldValueHistoryEntryWhereUniqueInput[]
  disconnect?: Prisma.FormFieldValueHistoryEntryWhereUniqueInput | Prisma.FormFieldValueHistoryEntryWhereUniqueInput[]
  delete?: Prisma.FormFieldValueHistoryEntryWhereUniqueInput | Prisma.FormFieldValueHistoryEntryWhereUniqueInput[]
  connect?: Prisma.FormFieldValueHistoryEntryWhereUniqueInput | Prisma.FormFieldValueHistoryEntryWhereUniqueInput[]
  update?: Prisma.FormFieldValueHistoryEntryUpdateWithWhereUniqueWithoutFormFieldValueInput | Prisma.FormFieldValueHistoryEntryUpdateWithWhereUniqueWithoutFormFieldValueInput[]
  updateMany?: Prisma.FormFieldValueHistoryEntryUpdateManyWithWhereWithoutFormFieldValueInput | Prisma.FormFieldValueHistoryEntryUpdateManyWithWhereWithoutFormFieldValueInput[]
  deleteMany?: Prisma.FormFieldValueHistoryEntryScalarWhereInput | Prisma.FormFieldValueHistoryEntryScalarWhereInput[]
}

export type FormFieldValueHistoryEntryUncheckedUpdateManyWithoutFormFieldValueNestedInput = {
  create?: Prisma.XOR<Prisma.FormFieldValueHistoryEntryCreateWithoutFormFieldValueInput, Prisma.FormFieldValueHistoryEntryUncheckedCreateWithoutFormFieldValueInput> | Prisma.FormFieldValueHistoryEntryCreateWithoutFormFieldValueInput[] | Prisma.FormFieldValueHistoryEntryUncheckedCreateWithoutFormFieldValueInput[]
  connectOrCreate?: Prisma.FormFieldValueHistoryEntryCreateOrConnectWithoutFormFieldValueInput | Prisma.FormFieldValueHistoryEntryCreateOrConnectWithoutFormFieldValueInput[]
  upsert?: Prisma.FormFieldValueHistoryEntryUpsertWithWhereUniqueWithoutFormFieldValueInput | Prisma.FormFieldValueHistoryEntryUpsertWithWhereUniqueWithoutFormFieldValueInput[]
  createMany?: Prisma.FormFieldValueHistoryEntryCreateManyFormFieldValueInputEnvelope
  set?: Prisma.FormFieldValueHistoryEntryWhereUniqueInput | Prisma.FormFieldValueHistoryEntryWhereUniqueInput[]
  disconnect?: Prisma.FormFieldValueHistoryEntryWhereUniqueInput | Prisma.FormFieldValueHistoryEntryWhereUniqueInput[]
  delete?: Prisma.FormFieldValueHistoryEntryWhereUniqueInput | Prisma.FormFieldValueHistoryEntryWhereUniqueInput[]
  connect?: Prisma.FormFieldValueHistoryEntryWhereUniqueInput | Prisma.FormFieldValueHistoryEntryWhereUniqueInput[]
  update?: Prisma.FormFieldValueHistoryEntryUpdateWithWhereUniqueWithoutFormFieldValueInput | Prisma.FormFieldValueHistoryEntryUpdateWithWhereUniqueWithoutFormFieldValueInput[]
  updateMany?: Prisma.FormFieldValueHistoryEntryUpdateManyWithWhereWithoutFormFieldValueInput | Prisma.FormFieldValueHistoryEntryUpdateManyWithWhereWithoutFormFieldValueInput[]
  deleteMany?: Prisma.FormFieldValueHistoryEntryScalarWhereInput | Prisma.FormFieldValueHistoryEntryScalarWhereInput[]
}

export type FormFieldValueHistoryEntryCreateWithoutFormFieldValueInput = {
  id?: string
  entityType: string
  entityId: string
  formId: string
  fieldDefId: string
  oldValue?: string | null
  newValue?: string | null
  changedBy?: string | null
  createdAt?: Date | string
}

export type FormFieldValueHistoryEntryUncheckedCreateWithoutFormFieldValueInput = {
  id?: string
  entityType: string
  entityId: string
  formId: string
  fieldDefId: string
  oldValue?: string | null
  newValue?: string | null
  changedBy?: string | null
  createdAt?: Date | string
}

export type FormFieldValueHistoryEntryCreateOrConnectWithoutFormFieldValueInput = {
  where: Prisma.FormFieldValueHistoryEntryWhereUniqueInput
  create: Prisma.XOR<Prisma.FormFieldValueHistoryEntryCreateWithoutFormFieldValueInput, Prisma.FormFieldValueHistoryEntryUncheckedCreateWithoutFormFieldValueInput>
}

export type FormFieldValueHistoryEntryCreateManyFormFieldValueInputEnvelope = {
  data: Prisma.FormFieldValueHistoryEntryCreateManyFormFieldValueInput | Prisma.FormFieldValueHistoryEntryCreateManyFormFieldValueInput[]
  skipDuplicates?: boolean
}

export type FormFieldValueHistoryEntryUpsertWithWhereUniqueWithoutFormFieldValueInput = {
  where: Prisma.FormFieldValueHistoryEntryWhereUniqueInput
  update: Prisma.XOR<Prisma.FormFieldValueHistoryEntryUpdateWithoutFormFieldValueInput, Prisma.FormFieldValueHistoryEntryUncheckedUpdateWithoutFormFieldValueInput>
  create: Prisma.XOR<Prisma.FormFieldValueHistoryEntryCreateWithoutFormFieldValueInput, Prisma.FormFieldValueHistoryEntryUncheckedCreateWithoutFormFieldValueInput>
}

export type FormFieldValueHistoryEntryUpdateWithWhereUniqueWithoutFormFieldValueInput = {
  where: Prisma.FormFieldValueHistoryEntryWhereUniqueInput
  data: Prisma.XOR<Prisma.FormFieldValueHistoryEntryUpdateWithoutFormFieldValueInput, Prisma.FormFieldValueHistoryEntryUncheckedUpdateWithoutFormFieldValueInput>
}

export type FormFieldValueHistoryEntryUpdateManyWithWhereWithoutFormFieldValueInput = {
  where: Prisma.FormFieldValueHistoryEntryScalarWhereInput
  data: Prisma.XOR<Prisma.FormFieldValueHistoryEntryUpdateManyMutationInput, Prisma.FormFieldValueHistoryEntryUncheckedUpdateManyWithoutFormFieldValueInput>
}

export type FormFieldValueHistoryEntryScalarWhereInput = {
  AND?: Prisma.FormFieldValueHistoryEntryScalarWhereInput | Prisma.FormFieldValueHistoryEntryScalarWhereInput[]
  OR?: Prisma.FormFieldValueHistoryEntryScalarWhereInput[]
  NOT?: Prisma.FormFieldValueHistoryEntryScalarWhereInput | Prisma.FormFieldValueHistoryEntryScalarWhereInput[]
  id?: Prisma.StringFilter<"FormFieldValueHistoryEntry"> | string
  formFieldValueId?: Prisma.StringFilter<"FormFieldValueHistoryEntry"> | string
  entityType?: Prisma.StringFilter<"FormFieldValueHistoryEntry"> | string
  entityId?: Prisma.StringFilter<"FormFieldValueHistoryEntry"> | string
  formId?: Prisma.StringFilter<"FormFieldValueHistoryEntry"> | string
  fieldDefId?: Prisma.StringFilter<"FormFieldValueHistoryEntry"> | string
  oldValue?: Prisma.StringNullableFilter<"FormFieldValueHistoryEntry"> | string | null
  newValue?: Prisma.StringNullableFilter<"FormFieldValueHistoryEntry"> | string | null
  changedBy?: Prisma.StringNullableFilter<"FormFieldValueHistoryEntry"> | string | null
  createdAt?: Prisma.DateTimeFilter<"FormFieldValueHistoryEntry"> | Date | string
}

export type FormFieldValueHistoryEntryCreateManyFormFieldValueInput = {
  id?: string
  entityType: string
  entityId: string
  formId: string
  fieldDefId: string
  oldValue?: string | null
  newValue?: string | null
  changedBy?: string | null
  createdAt?: Date | string
}

export type FormFieldValueHistoryEntryUpdateWithoutFormFieldValueInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entityType?: Prisma.StringFieldUpdateOperationsInput | string
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  formId?: Prisma.StringFieldUpdateOperationsInput | string
  fieldDefId?: Prisma.StringFieldUpdateOperationsInput | string
  oldValue?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  newValue?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  changedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FormFieldValueHistoryEntryUncheckedUpdateWithoutFormFieldValueInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entityType?: Prisma.StringFieldUpdateOperationsInput | string
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  formId?: Prisma.StringFieldUpdateOperationsInput | string
  fieldDefId?: Prisma.StringFieldUpdateOperationsInput | string
  oldValue?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  newValue?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  changedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FormFieldValueHistoryEntryUncheckedUpdateManyWithoutFormFieldValueInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entityType?: Prisma.StringFieldUpdateOperationsInput | string
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  formId?: Prisma.StringFieldUpdateOperationsInput | string
  fieldDefId?: Prisma.StringFieldUpdateOperationsInput | string
  oldValue?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  newValue?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  changedBy?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type FormFieldValueHistoryEntrySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  formFieldValueId?: boolean
  entityType?: boolean
  entityId?: boolean
  formId?: boolean
  fieldDefId?: boolean
  oldValue?: boolean
  newValue?: boolean
  changedBy?: boolean
  createdAt?: boolean
  formFieldValue?: boolean | Prisma.FormFieldValueDefaultArgs<ExtArgs>
}, ExtArgs["result"]["formFieldValueHistoryEntry"]>

export type FormFieldValueHistoryEntrySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  formFieldValueId?: boolean
  entityType?: boolean
  entityId?: boolean
  formId?: boolean
  fieldDefId?: boolean
  oldValue?: boolean
  newValue?: boolean
  changedBy?: boolean
  createdAt?: boolean
  formFieldValue?: boolean | Prisma.FormFieldValueDefaultArgs<ExtArgs>
}, ExtArgs["result"]["formFieldValueHistoryEntry"]>

export type FormFieldValueHistoryEntrySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  formFieldValueId?: boolean
  entityType?: boolean
  entityId?: boolean
  formId?: boolean
  fieldDefId?: boolean
  oldValue?: boolean
  newValue?: boolean
  changedBy?: boolean
  createdAt?: boolean
  formFieldValue?: boolean | Prisma.FormFieldValueDefaultArgs<ExtArgs>
}, ExtArgs["result"]["formFieldValueHistoryEntry"]>

export type FormFieldValueHistoryEntrySelectScalar = {
  id?: boolean
  formFieldValueId?: boolean
  entityType?: boolean
  entityId?: boolean
  formId?: boolean
  fieldDefId?: boolean
  oldValue?: boolean
  newValue?: boolean
  changedBy?: boolean
  createdAt?: boolean
}

export type FormFieldValueHistoryEntryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "formFieldValueId" | "entityType" | "entityId" | "formId" | "fieldDefId" | "oldValue" | "newValue" | "changedBy" | "createdAt", ExtArgs["result"]["formFieldValueHistoryEntry"]>
export type FormFieldValueHistoryEntryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  formFieldValue?: boolean | Prisma.FormFieldValueDefaultArgs<ExtArgs>
}
export type FormFieldValueHistoryEntryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  formFieldValue?: boolean | Prisma.FormFieldValueDefaultArgs<ExtArgs>
}
export type FormFieldValueHistoryEntryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  formFieldValue?: boolean | Prisma.FormFieldValueDefaultArgs<ExtArgs>
}

export type $FormFieldValueHistoryEntryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FormFieldValueHistoryEntry"
  objects: {
    formFieldValue: Prisma.$FormFieldValuePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    formFieldValueId: string
    entityType: string
    entityId: string
    formId: string
    fieldDefId: string
    oldValue: string | null
    newValue: string | null
    changedBy: string | null
    createdAt: Date
  }, ExtArgs["result"]["formFieldValueHistoryEntry"]>
  composites: {}
}

export type FormFieldValueHistoryEntryGetPayload<S extends boolean | null | undefined | FormFieldValueHistoryEntryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FormFieldValueHistoryEntryPayload, S>

export type FormFieldValueHistoryEntryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FormFieldValueHistoryEntryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FormFieldValueHistoryEntryCountAggregateInputType | true
  }

export interface FormFieldValueHistoryEntryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FormFieldValueHistoryEntry'], meta: { name: 'FormFieldValueHistoryEntry' } }
  /**
   * Find zero or one FormFieldValueHistoryEntry that matches the filter.
   * @param {FormFieldValueHistoryEntryFindUniqueArgs} args - Arguments to find a FormFieldValueHistoryEntry
   * @example
   * // Get one FormFieldValueHistoryEntry
   * const formFieldValueHistoryEntry = await prisma.formFieldValueHistoryEntry.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FormFieldValueHistoryEntryFindUniqueArgs>(args: Prisma.SelectSubset<T, FormFieldValueHistoryEntryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FormFieldValueHistoryEntryClient<runtime.Types.Result.GetResult<Prisma.$FormFieldValueHistoryEntryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FormFieldValueHistoryEntry that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FormFieldValueHistoryEntryFindUniqueOrThrowArgs} args - Arguments to find a FormFieldValueHistoryEntry
   * @example
   * // Get one FormFieldValueHistoryEntry
   * const formFieldValueHistoryEntry = await prisma.formFieldValueHistoryEntry.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FormFieldValueHistoryEntryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FormFieldValueHistoryEntryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FormFieldValueHistoryEntryClient<runtime.Types.Result.GetResult<Prisma.$FormFieldValueHistoryEntryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FormFieldValueHistoryEntry that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FormFieldValueHistoryEntryFindFirstArgs} args - Arguments to find a FormFieldValueHistoryEntry
   * @example
   * // Get one FormFieldValueHistoryEntry
   * const formFieldValueHistoryEntry = await prisma.formFieldValueHistoryEntry.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FormFieldValueHistoryEntryFindFirstArgs>(args?: Prisma.SelectSubset<T, FormFieldValueHistoryEntryFindFirstArgs<ExtArgs>>): Prisma.Prisma__FormFieldValueHistoryEntryClient<runtime.Types.Result.GetResult<Prisma.$FormFieldValueHistoryEntryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FormFieldValueHistoryEntry that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FormFieldValueHistoryEntryFindFirstOrThrowArgs} args - Arguments to find a FormFieldValueHistoryEntry
   * @example
   * // Get one FormFieldValueHistoryEntry
   * const formFieldValueHistoryEntry = await prisma.formFieldValueHistoryEntry.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FormFieldValueHistoryEntryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FormFieldValueHistoryEntryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FormFieldValueHistoryEntryClient<runtime.Types.Result.GetResult<Prisma.$FormFieldValueHistoryEntryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FormFieldValueHistoryEntries that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FormFieldValueHistoryEntryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FormFieldValueHistoryEntries
   * const formFieldValueHistoryEntries = await prisma.formFieldValueHistoryEntry.findMany()
   * 
   * // Get first 10 FormFieldValueHistoryEntries
   * const formFieldValueHistoryEntries = await prisma.formFieldValueHistoryEntry.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const formFieldValueHistoryEntryWithIdOnly = await prisma.formFieldValueHistoryEntry.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FormFieldValueHistoryEntryFindManyArgs>(args?: Prisma.SelectSubset<T, FormFieldValueHistoryEntryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FormFieldValueHistoryEntryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FormFieldValueHistoryEntry.
   * @param {FormFieldValueHistoryEntryCreateArgs} args - Arguments to create a FormFieldValueHistoryEntry.
   * @example
   * // Create one FormFieldValueHistoryEntry
   * const FormFieldValueHistoryEntry = await prisma.formFieldValueHistoryEntry.create({
   *   data: {
   *     // ... data to create a FormFieldValueHistoryEntry
   *   }
   * })
   * 
   */
  create<T extends FormFieldValueHistoryEntryCreateArgs>(args: Prisma.SelectSubset<T, FormFieldValueHistoryEntryCreateArgs<ExtArgs>>): Prisma.Prisma__FormFieldValueHistoryEntryClient<runtime.Types.Result.GetResult<Prisma.$FormFieldValueHistoryEntryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FormFieldValueHistoryEntries.
   * @param {FormFieldValueHistoryEntryCreateManyArgs} args - Arguments to create many FormFieldValueHistoryEntries.
   * @example
   * // Create many FormFieldValueHistoryEntries
   * const formFieldValueHistoryEntry = await prisma.formFieldValueHistoryEntry.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FormFieldValueHistoryEntryCreateManyArgs>(args?: Prisma.SelectSubset<T, FormFieldValueHistoryEntryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many FormFieldValueHistoryEntries and returns the data saved in the database.
   * @param {FormFieldValueHistoryEntryCreateManyAndReturnArgs} args - Arguments to create many FormFieldValueHistoryEntries.
   * @example
   * // Create many FormFieldValueHistoryEntries
   * const formFieldValueHistoryEntry = await prisma.formFieldValueHistoryEntry.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many FormFieldValueHistoryEntries and only return the `id`
   * const formFieldValueHistoryEntryWithIdOnly = await prisma.formFieldValueHistoryEntry.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FormFieldValueHistoryEntryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FormFieldValueHistoryEntryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FormFieldValueHistoryEntryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a FormFieldValueHistoryEntry.
   * @param {FormFieldValueHistoryEntryDeleteArgs} args - Arguments to delete one FormFieldValueHistoryEntry.
   * @example
   * // Delete one FormFieldValueHistoryEntry
   * const FormFieldValueHistoryEntry = await prisma.formFieldValueHistoryEntry.delete({
   *   where: {
   *     // ... filter to delete one FormFieldValueHistoryEntry
   *   }
   * })
   * 
   */
  delete<T extends FormFieldValueHistoryEntryDeleteArgs>(args: Prisma.SelectSubset<T, FormFieldValueHistoryEntryDeleteArgs<ExtArgs>>): Prisma.Prisma__FormFieldValueHistoryEntryClient<runtime.Types.Result.GetResult<Prisma.$FormFieldValueHistoryEntryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FormFieldValueHistoryEntry.
   * @param {FormFieldValueHistoryEntryUpdateArgs} args - Arguments to update one FormFieldValueHistoryEntry.
   * @example
   * // Update one FormFieldValueHistoryEntry
   * const formFieldValueHistoryEntry = await prisma.formFieldValueHistoryEntry.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FormFieldValueHistoryEntryUpdateArgs>(args: Prisma.SelectSubset<T, FormFieldValueHistoryEntryUpdateArgs<ExtArgs>>): Prisma.Prisma__FormFieldValueHistoryEntryClient<runtime.Types.Result.GetResult<Prisma.$FormFieldValueHistoryEntryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FormFieldValueHistoryEntries.
   * @param {FormFieldValueHistoryEntryDeleteManyArgs} args - Arguments to filter FormFieldValueHistoryEntries to delete.
   * @example
   * // Delete a few FormFieldValueHistoryEntries
   * const { count } = await prisma.formFieldValueHistoryEntry.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FormFieldValueHistoryEntryDeleteManyArgs>(args?: Prisma.SelectSubset<T, FormFieldValueHistoryEntryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FormFieldValueHistoryEntries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FormFieldValueHistoryEntryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FormFieldValueHistoryEntries
   * const formFieldValueHistoryEntry = await prisma.formFieldValueHistoryEntry.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FormFieldValueHistoryEntryUpdateManyArgs>(args: Prisma.SelectSubset<T, FormFieldValueHistoryEntryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FormFieldValueHistoryEntries and returns the data updated in the database.
   * @param {FormFieldValueHistoryEntryUpdateManyAndReturnArgs} args - Arguments to update many FormFieldValueHistoryEntries.
   * @example
   * // Update many FormFieldValueHistoryEntries
   * const formFieldValueHistoryEntry = await prisma.formFieldValueHistoryEntry.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more FormFieldValueHistoryEntries and only return the `id`
   * const formFieldValueHistoryEntryWithIdOnly = await prisma.formFieldValueHistoryEntry.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FormFieldValueHistoryEntryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FormFieldValueHistoryEntryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FormFieldValueHistoryEntryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one FormFieldValueHistoryEntry.
   * @param {FormFieldValueHistoryEntryUpsertArgs} args - Arguments to update or create a FormFieldValueHistoryEntry.
   * @example
   * // Update or create a FormFieldValueHistoryEntry
   * const formFieldValueHistoryEntry = await prisma.formFieldValueHistoryEntry.upsert({
   *   create: {
   *     // ... data to create a FormFieldValueHistoryEntry
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FormFieldValueHistoryEntry we want to update
   *   }
   * })
   */
  upsert<T extends FormFieldValueHistoryEntryUpsertArgs>(args: Prisma.SelectSubset<T, FormFieldValueHistoryEntryUpsertArgs<ExtArgs>>): Prisma.Prisma__FormFieldValueHistoryEntryClient<runtime.Types.Result.GetResult<Prisma.$FormFieldValueHistoryEntryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of FormFieldValueHistoryEntries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FormFieldValueHistoryEntryCountArgs} args - Arguments to filter FormFieldValueHistoryEntries to count.
   * @example
   * // Count the number of FormFieldValueHistoryEntries
   * const count = await prisma.formFieldValueHistoryEntry.count({
   *   where: {
   *     // ... the filter for the FormFieldValueHistoryEntries we want to count
   *   }
   * })
  **/
  count<T extends FormFieldValueHistoryEntryCountArgs>(
    args?: Prisma.Subset<T, FormFieldValueHistoryEntryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FormFieldValueHistoryEntryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FormFieldValueHistoryEntry.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FormFieldValueHistoryEntryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FormFieldValueHistoryEntryAggregateArgs>(args: Prisma.Subset<T, FormFieldValueHistoryEntryAggregateArgs>): Prisma.PrismaPromise<GetFormFieldValueHistoryEntryAggregateType<T>>

  /**
   * Group by FormFieldValueHistoryEntry.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FormFieldValueHistoryEntryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FormFieldValueHistoryEntryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FormFieldValueHistoryEntryGroupByArgs['orderBy'] }
      : { orderBy?: FormFieldValueHistoryEntryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FormFieldValueHistoryEntryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFormFieldValueHistoryEntryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FormFieldValueHistoryEntry model
 */
readonly fields: FormFieldValueHistoryEntryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FormFieldValueHistoryEntry.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FormFieldValueHistoryEntryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  formFieldValue<T extends Prisma.FormFieldValueDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FormFieldValueDefaultArgs<ExtArgs>>): Prisma.Prisma__FormFieldValueClient<runtime.Types.Result.GetResult<Prisma.$FormFieldValuePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FormFieldValueHistoryEntry model
 */
export interface FormFieldValueHistoryEntryFieldRefs {
  readonly id: Prisma.FieldRef<"FormFieldValueHistoryEntry", 'String'>
  readonly formFieldValueId: Prisma.FieldRef<"FormFieldValueHistoryEntry", 'String'>
  readonly entityType: Prisma.FieldRef<"FormFieldValueHistoryEntry", 'String'>
  readonly entityId: Prisma.FieldRef<"FormFieldValueHistoryEntry", 'String'>
  readonly formId: Prisma.FieldRef<"FormFieldValueHistoryEntry", 'String'>
  readonly fieldDefId: Prisma.FieldRef<"FormFieldValueHistoryEntry", 'String'>
  readonly oldValue: Prisma.FieldRef<"FormFieldValueHistoryEntry", 'String'>
  readonly newValue: Prisma.FieldRef<"FormFieldValueHistoryEntry", 'String'>
  readonly changedBy: Prisma.FieldRef<"FormFieldValueHistoryEntry", 'String'>
  readonly createdAt: Prisma.FieldRef<"FormFieldValueHistoryEntry", 'DateTime'>
}
    

// Custom InputTypes
/**
 * FormFieldValueHistoryEntry findUnique
 */
export type FormFieldValueHistoryEntryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FormFieldValueHistoryEntry
   */
  select?: Prisma.FormFieldValueHistoryEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the FormFieldValueHistoryEntry
   */
  omit?: Prisma.FormFieldValueHistoryEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FormFieldValueHistoryEntryInclude<ExtArgs> | null
  /**
   * Filter, which FormFieldValueHistoryEntry to fetch.
   */
  where: Prisma.FormFieldValueHistoryEntryWhereUniqueInput
}

/**
 * FormFieldValueHistoryEntry findUniqueOrThrow
 */
export type FormFieldValueHistoryEntryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FormFieldValueHistoryEntry
   */
  select?: Prisma.FormFieldValueHistoryEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the FormFieldValueHistoryEntry
   */
  omit?: Prisma.FormFieldValueHistoryEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FormFieldValueHistoryEntryInclude<ExtArgs> | null
  /**
   * Filter, which FormFieldValueHistoryEntry to fetch.
   */
  where: Prisma.FormFieldValueHistoryEntryWhereUniqueInput
}

/**
 * FormFieldValueHistoryEntry findFirst
 */
export type FormFieldValueHistoryEntryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FormFieldValueHistoryEntry
   */
  select?: Prisma.FormFieldValueHistoryEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the FormFieldValueHistoryEntry
   */
  omit?: Prisma.FormFieldValueHistoryEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FormFieldValueHistoryEntryInclude<ExtArgs> | null
  /**
   * Filter, which FormFieldValueHistoryEntry to fetch.
   */
  where?: Prisma.FormFieldValueHistoryEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FormFieldValueHistoryEntries to fetch.
   */
  orderBy?: Prisma.FormFieldValueHistoryEntryOrderByWithRelationInput | Prisma.FormFieldValueHistoryEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FormFieldValueHistoryEntries.
   */
  cursor?: Prisma.FormFieldValueHistoryEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FormFieldValueHistoryEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FormFieldValueHistoryEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FormFieldValueHistoryEntries.
   */
  distinct?: Prisma.FormFieldValueHistoryEntryScalarFieldEnum | Prisma.FormFieldValueHistoryEntryScalarFieldEnum[]
}

/**
 * FormFieldValueHistoryEntry findFirstOrThrow
 */
export type FormFieldValueHistoryEntryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FormFieldValueHistoryEntry
   */
  select?: Prisma.FormFieldValueHistoryEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the FormFieldValueHistoryEntry
   */
  omit?: Prisma.FormFieldValueHistoryEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FormFieldValueHistoryEntryInclude<ExtArgs> | null
  /**
   * Filter, which FormFieldValueHistoryEntry to fetch.
   */
  where?: Prisma.FormFieldValueHistoryEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FormFieldValueHistoryEntries to fetch.
   */
  orderBy?: Prisma.FormFieldValueHistoryEntryOrderByWithRelationInput | Prisma.FormFieldValueHistoryEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FormFieldValueHistoryEntries.
   */
  cursor?: Prisma.FormFieldValueHistoryEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FormFieldValueHistoryEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FormFieldValueHistoryEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FormFieldValueHistoryEntries.
   */
  distinct?: Prisma.FormFieldValueHistoryEntryScalarFieldEnum | Prisma.FormFieldValueHistoryEntryScalarFieldEnum[]
}

/**
 * FormFieldValueHistoryEntry findMany
 */
export type FormFieldValueHistoryEntryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FormFieldValueHistoryEntry
   */
  select?: Prisma.FormFieldValueHistoryEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the FormFieldValueHistoryEntry
   */
  omit?: Prisma.FormFieldValueHistoryEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FormFieldValueHistoryEntryInclude<ExtArgs> | null
  /**
   * Filter, which FormFieldValueHistoryEntries to fetch.
   */
  where?: Prisma.FormFieldValueHistoryEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FormFieldValueHistoryEntries to fetch.
   */
  orderBy?: Prisma.FormFieldValueHistoryEntryOrderByWithRelationInput | Prisma.FormFieldValueHistoryEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FormFieldValueHistoryEntries.
   */
  cursor?: Prisma.FormFieldValueHistoryEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FormFieldValueHistoryEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FormFieldValueHistoryEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FormFieldValueHistoryEntries.
   */
  distinct?: Prisma.FormFieldValueHistoryEntryScalarFieldEnum | Prisma.FormFieldValueHistoryEntryScalarFieldEnum[]
}

/**
 * FormFieldValueHistoryEntry create
 */
export type FormFieldValueHistoryEntryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FormFieldValueHistoryEntry
   */
  select?: Prisma.FormFieldValueHistoryEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the FormFieldValueHistoryEntry
   */
  omit?: Prisma.FormFieldValueHistoryEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FormFieldValueHistoryEntryInclude<ExtArgs> | null
  /**
   * The data needed to create a FormFieldValueHistoryEntry.
   */
  data: Prisma.XOR<Prisma.FormFieldValueHistoryEntryCreateInput, Prisma.FormFieldValueHistoryEntryUncheckedCreateInput>
}

/**
 * FormFieldValueHistoryEntry createMany
 */
export type FormFieldValueHistoryEntryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FormFieldValueHistoryEntries.
   */
  data: Prisma.FormFieldValueHistoryEntryCreateManyInput | Prisma.FormFieldValueHistoryEntryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * FormFieldValueHistoryEntry createManyAndReturn
 */
export type FormFieldValueHistoryEntryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FormFieldValueHistoryEntry
   */
  select?: Prisma.FormFieldValueHistoryEntrySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FormFieldValueHistoryEntry
   */
  omit?: Prisma.FormFieldValueHistoryEntryOmit<ExtArgs> | null
  /**
   * The data used to create many FormFieldValueHistoryEntries.
   */
  data: Prisma.FormFieldValueHistoryEntryCreateManyInput | Prisma.FormFieldValueHistoryEntryCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FormFieldValueHistoryEntryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * FormFieldValueHistoryEntry update
 */
export type FormFieldValueHistoryEntryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FormFieldValueHistoryEntry
   */
  select?: Prisma.FormFieldValueHistoryEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the FormFieldValueHistoryEntry
   */
  omit?: Prisma.FormFieldValueHistoryEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FormFieldValueHistoryEntryInclude<ExtArgs> | null
  /**
   * The data needed to update a FormFieldValueHistoryEntry.
   */
  data: Prisma.XOR<Prisma.FormFieldValueHistoryEntryUpdateInput, Prisma.FormFieldValueHistoryEntryUncheckedUpdateInput>
  /**
   * Choose, which FormFieldValueHistoryEntry to update.
   */
  where: Prisma.FormFieldValueHistoryEntryWhereUniqueInput
}

/**
 * FormFieldValueHistoryEntry updateMany
 */
export type FormFieldValueHistoryEntryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FormFieldValueHistoryEntries.
   */
  data: Prisma.XOR<Prisma.FormFieldValueHistoryEntryUpdateManyMutationInput, Prisma.FormFieldValueHistoryEntryUncheckedUpdateManyInput>
  /**
   * Filter which FormFieldValueHistoryEntries to update
   */
  where?: Prisma.FormFieldValueHistoryEntryWhereInput
  /**
   * Limit how many FormFieldValueHistoryEntries to update.
   */
  limit?: number
}

/**
 * FormFieldValueHistoryEntry updateManyAndReturn
 */
export type FormFieldValueHistoryEntryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FormFieldValueHistoryEntry
   */
  select?: Prisma.FormFieldValueHistoryEntrySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the FormFieldValueHistoryEntry
   */
  omit?: Prisma.FormFieldValueHistoryEntryOmit<ExtArgs> | null
  /**
   * The data used to update FormFieldValueHistoryEntries.
   */
  data: Prisma.XOR<Prisma.FormFieldValueHistoryEntryUpdateManyMutationInput, Prisma.FormFieldValueHistoryEntryUncheckedUpdateManyInput>
  /**
   * Filter which FormFieldValueHistoryEntries to update
   */
  where?: Prisma.FormFieldValueHistoryEntryWhereInput
  /**
   * Limit how many FormFieldValueHistoryEntries to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FormFieldValueHistoryEntryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * FormFieldValueHistoryEntry upsert
 */
export type FormFieldValueHistoryEntryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FormFieldValueHistoryEntry
   */
  select?: Prisma.FormFieldValueHistoryEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the FormFieldValueHistoryEntry
   */
  omit?: Prisma.FormFieldValueHistoryEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FormFieldValueHistoryEntryInclude<ExtArgs> | null
  /**
   * The filter to search for the FormFieldValueHistoryEntry to update in case it exists.
   */
  where: Prisma.FormFieldValueHistoryEntryWhereUniqueInput
  /**
   * In case the FormFieldValueHistoryEntry found by the `where` argument doesn't exist, create a new FormFieldValueHistoryEntry with this data.
   */
  create: Prisma.XOR<Prisma.FormFieldValueHistoryEntryCreateInput, Prisma.FormFieldValueHistoryEntryUncheckedCreateInput>
  /**
   * In case the FormFieldValueHistoryEntry was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FormFieldValueHistoryEntryUpdateInput, Prisma.FormFieldValueHistoryEntryUncheckedUpdateInput>
}

/**
 * FormFieldValueHistoryEntry delete
 */
export type FormFieldValueHistoryEntryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FormFieldValueHistoryEntry
   */
  select?: Prisma.FormFieldValueHistoryEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the FormFieldValueHistoryEntry
   */
  omit?: Prisma.FormFieldValueHistoryEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FormFieldValueHistoryEntryInclude<ExtArgs> | null
  /**
   * Filter which FormFieldValueHistoryEntry to delete.
   */
  where: Prisma.FormFieldValueHistoryEntryWhereUniqueInput
}

/**
 * FormFieldValueHistoryEntry deleteMany
 */
export type FormFieldValueHistoryEntryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FormFieldValueHistoryEntries to delete
   */
  where?: Prisma.FormFieldValueHistoryEntryWhereInput
  /**
   * Limit how many FormFieldValueHistoryEntries to delete.
   */
  limit?: number
}

/**
 * FormFieldValueHistoryEntry without action
 */
export type FormFieldValueHistoryEntryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FormFieldValueHistoryEntry
   */
  select?: Prisma.FormFieldValueHistoryEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the FormFieldValueHistoryEntry
   */
  omit?: Prisma.FormFieldValueHistoryEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FormFieldValueHistoryEntryInclude<ExtArgs> | null
}
