
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `JsonStoreDocument` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model JsonStoreDocument
 * 
 */
export type JsonStoreDocumentModel = runtime.Types.Result.DefaultSelection<Prisma.$JsonStoreDocumentPayload>

export type AggregateJsonStoreDocument = {
  _count: JsonStoreDocumentCountAggregateOutputType | null
  _min: JsonStoreDocumentMinAggregateOutputType | null
  _max: JsonStoreDocumentMaxAggregateOutputType | null
}

export type JsonStoreDocumentMinAggregateOutputType = {
  id: string | null
  key: string | null
  namespace: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type JsonStoreDocumentMaxAggregateOutputType = {
  id: string | null
  key: string | null
  namespace: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type JsonStoreDocumentCountAggregateOutputType = {
  id: number
  key: number
  namespace: number
  payload: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type JsonStoreDocumentMinAggregateInputType = {
  id?: true
  key?: true
  namespace?: true
  createdAt?: true
  updatedAt?: true
}

export type JsonStoreDocumentMaxAggregateInputType = {
  id?: true
  key?: true
  namespace?: true
  createdAt?: true
  updatedAt?: true
}

export type JsonStoreDocumentCountAggregateInputType = {
  id?: true
  key?: true
  namespace?: true
  payload?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type JsonStoreDocumentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which JsonStoreDocument to aggregate.
   */
  where?: Prisma.JsonStoreDocumentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JsonStoreDocuments to fetch.
   */
  orderBy?: Prisma.JsonStoreDocumentOrderByWithRelationInput | Prisma.JsonStoreDocumentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.JsonStoreDocumentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JsonStoreDocuments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JsonStoreDocuments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned JsonStoreDocuments
  **/
  _count?: true | JsonStoreDocumentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: JsonStoreDocumentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: JsonStoreDocumentMaxAggregateInputType
}

export type GetJsonStoreDocumentAggregateType<T extends JsonStoreDocumentAggregateArgs> = {
      [P in keyof T & keyof AggregateJsonStoreDocument]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateJsonStoreDocument[P]>
    : Prisma.GetScalarType<T[P], AggregateJsonStoreDocument[P]>
}




export type JsonStoreDocumentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.JsonStoreDocumentWhereInput
  orderBy?: Prisma.JsonStoreDocumentOrderByWithAggregationInput | Prisma.JsonStoreDocumentOrderByWithAggregationInput[]
  by: Prisma.JsonStoreDocumentScalarFieldEnum[] | Prisma.JsonStoreDocumentScalarFieldEnum
  having?: Prisma.JsonStoreDocumentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: JsonStoreDocumentCountAggregateInputType | true
  _min?: JsonStoreDocumentMinAggregateInputType
  _max?: JsonStoreDocumentMaxAggregateInputType
}

export type JsonStoreDocumentGroupByOutputType = {
  id: string
  key: string
  namespace: string
  payload: runtime.JsonValue
  createdAt: Date
  updatedAt: Date
  _count: JsonStoreDocumentCountAggregateOutputType | null
  _min: JsonStoreDocumentMinAggregateOutputType | null
  _max: JsonStoreDocumentMaxAggregateOutputType | null
}

export type GetJsonStoreDocumentGroupByPayload<T extends JsonStoreDocumentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<JsonStoreDocumentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof JsonStoreDocumentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], JsonStoreDocumentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], JsonStoreDocumentGroupByOutputType[P]>
      }
    >
  >



export type JsonStoreDocumentWhereInput = {
  AND?: Prisma.JsonStoreDocumentWhereInput | Prisma.JsonStoreDocumentWhereInput[]
  OR?: Prisma.JsonStoreDocumentWhereInput[]
  NOT?: Prisma.JsonStoreDocumentWhereInput | Prisma.JsonStoreDocumentWhereInput[]
  id?: Prisma.StringFilter<"JsonStoreDocument"> | string
  key?: Prisma.StringFilter<"JsonStoreDocument"> | string
  namespace?: Prisma.StringFilter<"JsonStoreDocument"> | string
  payload?: Prisma.JsonFilter<"JsonStoreDocument">
  createdAt?: Prisma.DateTimeFilter<"JsonStoreDocument"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"JsonStoreDocument"> | Date | string
}

export type JsonStoreDocumentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  namespace?: Prisma.SortOrder
  payload?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type JsonStoreDocumentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  json_store_key_namespace_unique?: Prisma.JsonStoreDocumentJson_store_key_namespace_uniqueCompoundUniqueInput
  AND?: Prisma.JsonStoreDocumentWhereInput | Prisma.JsonStoreDocumentWhereInput[]
  OR?: Prisma.JsonStoreDocumentWhereInput[]
  NOT?: Prisma.JsonStoreDocumentWhereInput | Prisma.JsonStoreDocumentWhereInput[]
  key?: Prisma.StringFilter<"JsonStoreDocument"> | string
  namespace?: Prisma.StringFilter<"JsonStoreDocument"> | string
  payload?: Prisma.JsonFilter<"JsonStoreDocument">
  createdAt?: Prisma.DateTimeFilter<"JsonStoreDocument"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"JsonStoreDocument"> | Date | string
}, "id" | "json_store_key_namespace_unique">

export type JsonStoreDocumentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  namespace?: Prisma.SortOrder
  payload?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.JsonStoreDocumentCountOrderByAggregateInput
  _max?: Prisma.JsonStoreDocumentMaxOrderByAggregateInput
  _min?: Prisma.JsonStoreDocumentMinOrderByAggregateInput
}

export type JsonStoreDocumentScalarWhereWithAggregatesInput = {
  AND?: Prisma.JsonStoreDocumentScalarWhereWithAggregatesInput | Prisma.JsonStoreDocumentScalarWhereWithAggregatesInput[]
  OR?: Prisma.JsonStoreDocumentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.JsonStoreDocumentScalarWhereWithAggregatesInput | Prisma.JsonStoreDocumentScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"JsonStoreDocument"> | string
  key?: Prisma.StringWithAggregatesFilter<"JsonStoreDocument"> | string
  namespace?: Prisma.StringWithAggregatesFilter<"JsonStoreDocument"> | string
  payload?: Prisma.JsonWithAggregatesFilter<"JsonStoreDocument">
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"JsonStoreDocument"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"JsonStoreDocument"> | Date | string
}

export type JsonStoreDocumentCreateInput = {
  id?: string
  key: string
  namespace: string
  payload: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type JsonStoreDocumentUncheckedCreateInput = {
  id?: string
  key: string
  namespace: string
  payload: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type JsonStoreDocumentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  namespace?: Prisma.StringFieldUpdateOperationsInput | string
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type JsonStoreDocumentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  namespace?: Prisma.StringFieldUpdateOperationsInput | string
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type JsonStoreDocumentCreateManyInput = {
  id?: string
  key: string
  namespace: string
  payload: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type JsonStoreDocumentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  namespace?: Prisma.StringFieldUpdateOperationsInput | string
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type JsonStoreDocumentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  key?: Prisma.StringFieldUpdateOperationsInput | string
  namespace?: Prisma.StringFieldUpdateOperationsInput | string
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type JsonStoreDocumentJson_store_key_namespace_uniqueCompoundUniqueInput = {
  key: string
  namespace: string
}

export type JsonStoreDocumentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  namespace?: Prisma.SortOrder
  payload?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type JsonStoreDocumentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  namespace?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type JsonStoreDocumentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  key?: Prisma.SortOrder
  namespace?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}



export type JsonStoreDocumentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  key?: boolean
  namespace?: boolean
  payload?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["jsonStoreDocument"]>

export type JsonStoreDocumentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  key?: boolean
  namespace?: boolean
  payload?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["jsonStoreDocument"]>

export type JsonStoreDocumentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  key?: boolean
  namespace?: boolean
  payload?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["jsonStoreDocument"]>

export type JsonStoreDocumentSelectScalar = {
  id?: boolean
  key?: boolean
  namespace?: boolean
  payload?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type JsonStoreDocumentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "key" | "namespace" | "payload" | "createdAt" | "updatedAt", ExtArgs["result"]["jsonStoreDocument"]>

export type $JsonStoreDocumentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "JsonStoreDocument"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    key: string
    namespace: string
    payload: runtime.JsonValue
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["jsonStoreDocument"]>
  composites: {}
}

export type JsonStoreDocumentGetPayload<S extends boolean | null | undefined | JsonStoreDocumentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$JsonStoreDocumentPayload, S>

export type JsonStoreDocumentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<JsonStoreDocumentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: JsonStoreDocumentCountAggregateInputType | true
  }

export interface JsonStoreDocumentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['JsonStoreDocument'], meta: { name: 'JsonStoreDocument' } }
  /**
   * Find zero or one JsonStoreDocument that matches the filter.
   * @param {JsonStoreDocumentFindUniqueArgs} args - Arguments to find a JsonStoreDocument
   * @example
   * // Get one JsonStoreDocument
   * const jsonStoreDocument = await prisma.jsonStoreDocument.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends JsonStoreDocumentFindUniqueArgs>(args: Prisma.SelectSubset<T, JsonStoreDocumentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__JsonStoreDocumentClient<runtime.Types.Result.GetResult<Prisma.$JsonStoreDocumentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one JsonStoreDocument that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {JsonStoreDocumentFindUniqueOrThrowArgs} args - Arguments to find a JsonStoreDocument
   * @example
   * // Get one JsonStoreDocument
   * const jsonStoreDocument = await prisma.jsonStoreDocument.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends JsonStoreDocumentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, JsonStoreDocumentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__JsonStoreDocumentClient<runtime.Types.Result.GetResult<Prisma.$JsonStoreDocumentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first JsonStoreDocument that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JsonStoreDocumentFindFirstArgs} args - Arguments to find a JsonStoreDocument
   * @example
   * // Get one JsonStoreDocument
   * const jsonStoreDocument = await prisma.jsonStoreDocument.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends JsonStoreDocumentFindFirstArgs>(args?: Prisma.SelectSubset<T, JsonStoreDocumentFindFirstArgs<ExtArgs>>): Prisma.Prisma__JsonStoreDocumentClient<runtime.Types.Result.GetResult<Prisma.$JsonStoreDocumentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first JsonStoreDocument that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JsonStoreDocumentFindFirstOrThrowArgs} args - Arguments to find a JsonStoreDocument
   * @example
   * // Get one JsonStoreDocument
   * const jsonStoreDocument = await prisma.jsonStoreDocument.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends JsonStoreDocumentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, JsonStoreDocumentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__JsonStoreDocumentClient<runtime.Types.Result.GetResult<Prisma.$JsonStoreDocumentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more JsonStoreDocuments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JsonStoreDocumentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all JsonStoreDocuments
   * const jsonStoreDocuments = await prisma.jsonStoreDocument.findMany()
   * 
   * // Get first 10 JsonStoreDocuments
   * const jsonStoreDocuments = await prisma.jsonStoreDocument.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const jsonStoreDocumentWithIdOnly = await prisma.jsonStoreDocument.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends JsonStoreDocumentFindManyArgs>(args?: Prisma.SelectSubset<T, JsonStoreDocumentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JsonStoreDocumentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a JsonStoreDocument.
   * @param {JsonStoreDocumentCreateArgs} args - Arguments to create a JsonStoreDocument.
   * @example
   * // Create one JsonStoreDocument
   * const JsonStoreDocument = await prisma.jsonStoreDocument.create({
   *   data: {
   *     // ... data to create a JsonStoreDocument
   *   }
   * })
   * 
   */
  create<T extends JsonStoreDocumentCreateArgs>(args: Prisma.SelectSubset<T, JsonStoreDocumentCreateArgs<ExtArgs>>): Prisma.Prisma__JsonStoreDocumentClient<runtime.Types.Result.GetResult<Prisma.$JsonStoreDocumentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many JsonStoreDocuments.
   * @param {JsonStoreDocumentCreateManyArgs} args - Arguments to create many JsonStoreDocuments.
   * @example
   * // Create many JsonStoreDocuments
   * const jsonStoreDocument = await prisma.jsonStoreDocument.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends JsonStoreDocumentCreateManyArgs>(args?: Prisma.SelectSubset<T, JsonStoreDocumentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many JsonStoreDocuments and returns the data saved in the database.
   * @param {JsonStoreDocumentCreateManyAndReturnArgs} args - Arguments to create many JsonStoreDocuments.
   * @example
   * // Create many JsonStoreDocuments
   * const jsonStoreDocument = await prisma.jsonStoreDocument.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many JsonStoreDocuments and only return the `id`
   * const jsonStoreDocumentWithIdOnly = await prisma.jsonStoreDocument.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends JsonStoreDocumentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, JsonStoreDocumentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JsonStoreDocumentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a JsonStoreDocument.
   * @param {JsonStoreDocumentDeleteArgs} args - Arguments to delete one JsonStoreDocument.
   * @example
   * // Delete one JsonStoreDocument
   * const JsonStoreDocument = await prisma.jsonStoreDocument.delete({
   *   where: {
   *     // ... filter to delete one JsonStoreDocument
   *   }
   * })
   * 
   */
  delete<T extends JsonStoreDocumentDeleteArgs>(args: Prisma.SelectSubset<T, JsonStoreDocumentDeleteArgs<ExtArgs>>): Prisma.Prisma__JsonStoreDocumentClient<runtime.Types.Result.GetResult<Prisma.$JsonStoreDocumentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one JsonStoreDocument.
   * @param {JsonStoreDocumentUpdateArgs} args - Arguments to update one JsonStoreDocument.
   * @example
   * // Update one JsonStoreDocument
   * const jsonStoreDocument = await prisma.jsonStoreDocument.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends JsonStoreDocumentUpdateArgs>(args: Prisma.SelectSubset<T, JsonStoreDocumentUpdateArgs<ExtArgs>>): Prisma.Prisma__JsonStoreDocumentClient<runtime.Types.Result.GetResult<Prisma.$JsonStoreDocumentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more JsonStoreDocuments.
   * @param {JsonStoreDocumentDeleteManyArgs} args - Arguments to filter JsonStoreDocuments to delete.
   * @example
   * // Delete a few JsonStoreDocuments
   * const { count } = await prisma.jsonStoreDocument.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends JsonStoreDocumentDeleteManyArgs>(args?: Prisma.SelectSubset<T, JsonStoreDocumentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more JsonStoreDocuments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JsonStoreDocumentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many JsonStoreDocuments
   * const jsonStoreDocument = await prisma.jsonStoreDocument.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends JsonStoreDocumentUpdateManyArgs>(args: Prisma.SelectSubset<T, JsonStoreDocumentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more JsonStoreDocuments and returns the data updated in the database.
   * @param {JsonStoreDocumentUpdateManyAndReturnArgs} args - Arguments to update many JsonStoreDocuments.
   * @example
   * // Update many JsonStoreDocuments
   * const jsonStoreDocument = await prisma.jsonStoreDocument.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more JsonStoreDocuments and only return the `id`
   * const jsonStoreDocumentWithIdOnly = await prisma.jsonStoreDocument.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends JsonStoreDocumentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, JsonStoreDocumentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$JsonStoreDocumentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one JsonStoreDocument.
   * @param {JsonStoreDocumentUpsertArgs} args - Arguments to update or create a JsonStoreDocument.
   * @example
   * // Update or create a JsonStoreDocument
   * const jsonStoreDocument = await prisma.jsonStoreDocument.upsert({
   *   create: {
   *     // ... data to create a JsonStoreDocument
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the JsonStoreDocument we want to update
   *   }
   * })
   */
  upsert<T extends JsonStoreDocumentUpsertArgs>(args: Prisma.SelectSubset<T, JsonStoreDocumentUpsertArgs<ExtArgs>>): Prisma.Prisma__JsonStoreDocumentClient<runtime.Types.Result.GetResult<Prisma.$JsonStoreDocumentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of JsonStoreDocuments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JsonStoreDocumentCountArgs} args - Arguments to filter JsonStoreDocuments to count.
   * @example
   * // Count the number of JsonStoreDocuments
   * const count = await prisma.jsonStoreDocument.count({
   *   where: {
   *     // ... the filter for the JsonStoreDocuments we want to count
   *   }
   * })
  **/
  count<T extends JsonStoreDocumentCountArgs>(
    args?: Prisma.Subset<T, JsonStoreDocumentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], JsonStoreDocumentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a JsonStoreDocument.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JsonStoreDocumentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends JsonStoreDocumentAggregateArgs>(args: Prisma.Subset<T, JsonStoreDocumentAggregateArgs>): Prisma.PrismaPromise<GetJsonStoreDocumentAggregateType<T>>

  /**
   * Group by JsonStoreDocument.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {JsonStoreDocumentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends JsonStoreDocumentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: JsonStoreDocumentGroupByArgs['orderBy'] }
      : { orderBy?: JsonStoreDocumentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, JsonStoreDocumentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetJsonStoreDocumentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the JsonStoreDocument model
 */
readonly fields: JsonStoreDocumentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for JsonStoreDocument.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__JsonStoreDocumentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the JsonStoreDocument model
 */
export interface JsonStoreDocumentFieldRefs {
  readonly id: Prisma.FieldRef<"JsonStoreDocument", 'String'>
  readonly key: Prisma.FieldRef<"JsonStoreDocument", 'String'>
  readonly namespace: Prisma.FieldRef<"JsonStoreDocument", 'String'>
  readonly payload: Prisma.FieldRef<"JsonStoreDocument", 'Json'>
  readonly createdAt: Prisma.FieldRef<"JsonStoreDocument", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"JsonStoreDocument", 'DateTime'>
}
    

// Custom InputTypes
/**
 * JsonStoreDocument findUnique
 */
export type JsonStoreDocumentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JsonStoreDocument
   */
  select?: Prisma.JsonStoreDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JsonStoreDocument
   */
  omit?: Prisma.JsonStoreDocumentOmit<ExtArgs> | null
  /**
   * Filter, which JsonStoreDocument to fetch.
   */
  where: Prisma.JsonStoreDocumentWhereUniqueInput
}

/**
 * JsonStoreDocument findUniqueOrThrow
 */
export type JsonStoreDocumentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JsonStoreDocument
   */
  select?: Prisma.JsonStoreDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JsonStoreDocument
   */
  omit?: Prisma.JsonStoreDocumentOmit<ExtArgs> | null
  /**
   * Filter, which JsonStoreDocument to fetch.
   */
  where: Prisma.JsonStoreDocumentWhereUniqueInput
}

/**
 * JsonStoreDocument findFirst
 */
export type JsonStoreDocumentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JsonStoreDocument
   */
  select?: Prisma.JsonStoreDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JsonStoreDocument
   */
  omit?: Prisma.JsonStoreDocumentOmit<ExtArgs> | null
  /**
   * Filter, which JsonStoreDocument to fetch.
   */
  where?: Prisma.JsonStoreDocumentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JsonStoreDocuments to fetch.
   */
  orderBy?: Prisma.JsonStoreDocumentOrderByWithRelationInput | Prisma.JsonStoreDocumentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for JsonStoreDocuments.
   */
  cursor?: Prisma.JsonStoreDocumentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JsonStoreDocuments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JsonStoreDocuments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of JsonStoreDocuments.
   */
  distinct?: Prisma.JsonStoreDocumentScalarFieldEnum | Prisma.JsonStoreDocumentScalarFieldEnum[]
}

/**
 * JsonStoreDocument findFirstOrThrow
 */
export type JsonStoreDocumentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JsonStoreDocument
   */
  select?: Prisma.JsonStoreDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JsonStoreDocument
   */
  omit?: Prisma.JsonStoreDocumentOmit<ExtArgs> | null
  /**
   * Filter, which JsonStoreDocument to fetch.
   */
  where?: Prisma.JsonStoreDocumentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JsonStoreDocuments to fetch.
   */
  orderBy?: Prisma.JsonStoreDocumentOrderByWithRelationInput | Prisma.JsonStoreDocumentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for JsonStoreDocuments.
   */
  cursor?: Prisma.JsonStoreDocumentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JsonStoreDocuments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JsonStoreDocuments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of JsonStoreDocuments.
   */
  distinct?: Prisma.JsonStoreDocumentScalarFieldEnum | Prisma.JsonStoreDocumentScalarFieldEnum[]
}

/**
 * JsonStoreDocument findMany
 */
export type JsonStoreDocumentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JsonStoreDocument
   */
  select?: Prisma.JsonStoreDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JsonStoreDocument
   */
  omit?: Prisma.JsonStoreDocumentOmit<ExtArgs> | null
  /**
   * Filter, which JsonStoreDocuments to fetch.
   */
  where?: Prisma.JsonStoreDocumentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of JsonStoreDocuments to fetch.
   */
  orderBy?: Prisma.JsonStoreDocumentOrderByWithRelationInput | Prisma.JsonStoreDocumentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing JsonStoreDocuments.
   */
  cursor?: Prisma.JsonStoreDocumentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` JsonStoreDocuments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` JsonStoreDocuments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of JsonStoreDocuments.
   */
  distinct?: Prisma.JsonStoreDocumentScalarFieldEnum | Prisma.JsonStoreDocumentScalarFieldEnum[]
}

/**
 * JsonStoreDocument create
 */
export type JsonStoreDocumentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JsonStoreDocument
   */
  select?: Prisma.JsonStoreDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JsonStoreDocument
   */
  omit?: Prisma.JsonStoreDocumentOmit<ExtArgs> | null
  /**
   * The data needed to create a JsonStoreDocument.
   */
  data: Prisma.XOR<Prisma.JsonStoreDocumentCreateInput, Prisma.JsonStoreDocumentUncheckedCreateInput>
}

/**
 * JsonStoreDocument createMany
 */
export type JsonStoreDocumentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many JsonStoreDocuments.
   */
  data: Prisma.JsonStoreDocumentCreateManyInput | Prisma.JsonStoreDocumentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * JsonStoreDocument createManyAndReturn
 */
export type JsonStoreDocumentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JsonStoreDocument
   */
  select?: Prisma.JsonStoreDocumentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the JsonStoreDocument
   */
  omit?: Prisma.JsonStoreDocumentOmit<ExtArgs> | null
  /**
   * The data used to create many JsonStoreDocuments.
   */
  data: Prisma.JsonStoreDocumentCreateManyInput | Prisma.JsonStoreDocumentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * JsonStoreDocument update
 */
export type JsonStoreDocumentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JsonStoreDocument
   */
  select?: Prisma.JsonStoreDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JsonStoreDocument
   */
  omit?: Prisma.JsonStoreDocumentOmit<ExtArgs> | null
  /**
   * The data needed to update a JsonStoreDocument.
   */
  data: Prisma.XOR<Prisma.JsonStoreDocumentUpdateInput, Prisma.JsonStoreDocumentUncheckedUpdateInput>
  /**
   * Choose, which JsonStoreDocument to update.
   */
  where: Prisma.JsonStoreDocumentWhereUniqueInput
}

/**
 * JsonStoreDocument updateMany
 */
export type JsonStoreDocumentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update JsonStoreDocuments.
   */
  data: Prisma.XOR<Prisma.JsonStoreDocumentUpdateManyMutationInput, Prisma.JsonStoreDocumentUncheckedUpdateManyInput>
  /**
   * Filter which JsonStoreDocuments to update
   */
  where?: Prisma.JsonStoreDocumentWhereInput
  /**
   * Limit how many JsonStoreDocuments to update.
   */
  limit?: number
}

/**
 * JsonStoreDocument updateManyAndReturn
 */
export type JsonStoreDocumentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JsonStoreDocument
   */
  select?: Prisma.JsonStoreDocumentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the JsonStoreDocument
   */
  omit?: Prisma.JsonStoreDocumentOmit<ExtArgs> | null
  /**
   * The data used to update JsonStoreDocuments.
   */
  data: Prisma.XOR<Prisma.JsonStoreDocumentUpdateManyMutationInput, Prisma.JsonStoreDocumentUncheckedUpdateManyInput>
  /**
   * Filter which JsonStoreDocuments to update
   */
  where?: Prisma.JsonStoreDocumentWhereInput
  /**
   * Limit how many JsonStoreDocuments to update.
   */
  limit?: number
}

/**
 * JsonStoreDocument upsert
 */
export type JsonStoreDocumentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JsonStoreDocument
   */
  select?: Prisma.JsonStoreDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JsonStoreDocument
   */
  omit?: Prisma.JsonStoreDocumentOmit<ExtArgs> | null
  /**
   * The filter to search for the JsonStoreDocument to update in case it exists.
   */
  where: Prisma.JsonStoreDocumentWhereUniqueInput
  /**
   * In case the JsonStoreDocument found by the `where` argument doesn't exist, create a new JsonStoreDocument with this data.
   */
  create: Prisma.XOR<Prisma.JsonStoreDocumentCreateInput, Prisma.JsonStoreDocumentUncheckedCreateInput>
  /**
   * In case the JsonStoreDocument was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.JsonStoreDocumentUpdateInput, Prisma.JsonStoreDocumentUncheckedUpdateInput>
}

/**
 * JsonStoreDocument delete
 */
export type JsonStoreDocumentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JsonStoreDocument
   */
  select?: Prisma.JsonStoreDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JsonStoreDocument
   */
  omit?: Prisma.JsonStoreDocumentOmit<ExtArgs> | null
  /**
   * Filter which JsonStoreDocument to delete.
   */
  where: Prisma.JsonStoreDocumentWhereUniqueInput
}

/**
 * JsonStoreDocument deleteMany
 */
export type JsonStoreDocumentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which JsonStoreDocuments to delete
   */
  where?: Prisma.JsonStoreDocumentWhereInput
  /**
   * Limit how many JsonStoreDocuments to delete.
   */
  limit?: number
}

/**
 * JsonStoreDocument without action
 */
export type JsonStoreDocumentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the JsonStoreDocument
   */
  select?: Prisma.JsonStoreDocumentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the JsonStoreDocument
   */
  omit?: Prisma.JsonStoreDocumentOmit<ExtArgs> | null
}
