
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `WorkflowIdempotencyKey` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model WorkflowIdempotencyKey
 * 
 */
export type WorkflowIdempotencyKeyModel = runtime.Types.Result.DefaultSelection<Prisma.$WorkflowIdempotencyKeyPayload>

export type AggregateWorkflowIdempotencyKey = {
  _count: WorkflowIdempotencyKeyCountAggregateOutputType | null
  _min: WorkflowIdempotencyKeyMinAggregateOutputType | null
  _max: WorkflowIdempotencyKeyMaxAggregateOutputType | null
}

export type WorkflowIdempotencyKeyMinAggregateOutputType = {
  key: string | null
  scope: string | null
  instanceId: string | null
  expiresAt: Date | null
  createdAt: Date | null
}

export type WorkflowIdempotencyKeyMaxAggregateOutputType = {
  key: string | null
  scope: string | null
  instanceId: string | null
  expiresAt: Date | null
  createdAt: Date | null
}

export type WorkflowIdempotencyKeyCountAggregateOutputType = {
  key: number
  scope: number
  instanceId: number
  result: number
  expiresAt: number
  createdAt: number
  _all: number
}


export type WorkflowIdempotencyKeyMinAggregateInputType = {
  key?: true
  scope?: true
  instanceId?: true
  expiresAt?: true
  createdAt?: true
}

export type WorkflowIdempotencyKeyMaxAggregateInputType = {
  key?: true
  scope?: true
  instanceId?: true
  expiresAt?: true
  createdAt?: true
}

export type WorkflowIdempotencyKeyCountAggregateInputType = {
  key?: true
  scope?: true
  instanceId?: true
  result?: true
  expiresAt?: true
  createdAt?: true
  _all?: true
}

export type WorkflowIdempotencyKeyAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorkflowIdempotencyKey to aggregate.
   */
  where?: Prisma.WorkflowIdempotencyKeyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkflowIdempotencyKeys to fetch.
   */
  orderBy?: Prisma.WorkflowIdempotencyKeyOrderByWithRelationInput | Prisma.WorkflowIdempotencyKeyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.WorkflowIdempotencyKeyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkflowIdempotencyKeys from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkflowIdempotencyKeys.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned WorkflowIdempotencyKeys
  **/
  _count?: true | WorkflowIdempotencyKeyCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: WorkflowIdempotencyKeyMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: WorkflowIdempotencyKeyMaxAggregateInputType
}

export type GetWorkflowIdempotencyKeyAggregateType<T extends WorkflowIdempotencyKeyAggregateArgs> = {
      [P in keyof T & keyof AggregateWorkflowIdempotencyKey]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWorkflowIdempotencyKey[P]>
    : Prisma.GetScalarType<T[P], AggregateWorkflowIdempotencyKey[P]>
}




export type WorkflowIdempotencyKeyGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WorkflowIdempotencyKeyWhereInput
  orderBy?: Prisma.WorkflowIdempotencyKeyOrderByWithAggregationInput | Prisma.WorkflowIdempotencyKeyOrderByWithAggregationInput[]
  by: Prisma.WorkflowIdempotencyKeyScalarFieldEnum[] | Prisma.WorkflowIdempotencyKeyScalarFieldEnum
  having?: Prisma.WorkflowIdempotencyKeyScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WorkflowIdempotencyKeyCountAggregateInputType | true
  _min?: WorkflowIdempotencyKeyMinAggregateInputType
  _max?: WorkflowIdempotencyKeyMaxAggregateInputType
}

export type WorkflowIdempotencyKeyGroupByOutputType = {
  key: string
  scope: string
  instanceId: string | null
  result: runtime.JsonValue | null
  expiresAt: Date
  createdAt: Date
  _count: WorkflowIdempotencyKeyCountAggregateOutputType | null
  _min: WorkflowIdempotencyKeyMinAggregateOutputType | null
  _max: WorkflowIdempotencyKeyMaxAggregateOutputType | null
}

export type GetWorkflowIdempotencyKeyGroupByPayload<T extends WorkflowIdempotencyKeyGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<WorkflowIdempotencyKeyGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof WorkflowIdempotencyKeyGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WorkflowIdempotencyKeyGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WorkflowIdempotencyKeyGroupByOutputType[P]>
      }
    >
  >



export type WorkflowIdempotencyKeyWhereInput = {
  AND?: Prisma.WorkflowIdempotencyKeyWhereInput | Prisma.WorkflowIdempotencyKeyWhereInput[]
  OR?: Prisma.WorkflowIdempotencyKeyWhereInput[]
  NOT?: Prisma.WorkflowIdempotencyKeyWhereInput | Prisma.WorkflowIdempotencyKeyWhereInput[]
  key?: Prisma.StringFilter<"WorkflowIdempotencyKey"> | string
  scope?: Prisma.StringFilter<"WorkflowIdempotencyKey"> | string
  instanceId?: Prisma.StringNullableFilter<"WorkflowIdempotencyKey"> | string | null
  result?: Prisma.JsonNullableFilter<"WorkflowIdempotencyKey">
  expiresAt?: Prisma.DateTimeFilter<"WorkflowIdempotencyKey"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"WorkflowIdempotencyKey"> | Date | string
}

export type WorkflowIdempotencyKeyOrderByWithRelationInput = {
  key?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  instanceId?: Prisma.SortOrderInput | Prisma.SortOrder
  result?: Prisma.SortOrderInput | Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type WorkflowIdempotencyKeyWhereUniqueInput = Prisma.AtLeast<{
  key?: string
  AND?: Prisma.WorkflowIdempotencyKeyWhereInput | Prisma.WorkflowIdempotencyKeyWhereInput[]
  OR?: Prisma.WorkflowIdempotencyKeyWhereInput[]
  NOT?: Prisma.WorkflowIdempotencyKeyWhereInput | Prisma.WorkflowIdempotencyKeyWhereInput[]
  scope?: Prisma.StringFilter<"WorkflowIdempotencyKey"> | string
  instanceId?: Prisma.StringNullableFilter<"WorkflowIdempotencyKey"> | string | null
  result?: Prisma.JsonNullableFilter<"WorkflowIdempotencyKey">
  expiresAt?: Prisma.DateTimeFilter<"WorkflowIdempotencyKey"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"WorkflowIdempotencyKey"> | Date | string
}, "key">

export type WorkflowIdempotencyKeyOrderByWithAggregationInput = {
  key?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  instanceId?: Prisma.SortOrderInput | Prisma.SortOrder
  result?: Prisma.SortOrderInput | Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.WorkflowIdempotencyKeyCountOrderByAggregateInput
  _max?: Prisma.WorkflowIdempotencyKeyMaxOrderByAggregateInput
  _min?: Prisma.WorkflowIdempotencyKeyMinOrderByAggregateInput
}

export type WorkflowIdempotencyKeyScalarWhereWithAggregatesInput = {
  AND?: Prisma.WorkflowIdempotencyKeyScalarWhereWithAggregatesInput | Prisma.WorkflowIdempotencyKeyScalarWhereWithAggregatesInput[]
  OR?: Prisma.WorkflowIdempotencyKeyScalarWhereWithAggregatesInput[]
  NOT?: Prisma.WorkflowIdempotencyKeyScalarWhereWithAggregatesInput | Prisma.WorkflowIdempotencyKeyScalarWhereWithAggregatesInput[]
  key?: Prisma.StringWithAggregatesFilter<"WorkflowIdempotencyKey"> | string
  scope?: Prisma.StringWithAggregatesFilter<"WorkflowIdempotencyKey"> | string
  instanceId?: Prisma.StringNullableWithAggregatesFilter<"WorkflowIdempotencyKey"> | string | null
  result?: Prisma.JsonNullableWithAggregatesFilter<"WorkflowIdempotencyKey">
  expiresAt?: Prisma.DateTimeWithAggregatesFilter<"WorkflowIdempotencyKey"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"WorkflowIdempotencyKey"> | Date | string
}

export type WorkflowIdempotencyKeyCreateInput = {
  key: string
  scope: string
  instanceId?: string | null
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  expiresAt: Date | string
  createdAt?: Date | string
}

export type WorkflowIdempotencyKeyUncheckedCreateInput = {
  key: string
  scope: string
  instanceId?: string | null
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  expiresAt: Date | string
  createdAt?: Date | string
}

export type WorkflowIdempotencyKeyUpdateInput = {
  key?: Prisma.StringFieldUpdateOperationsInput | string
  scope?: Prisma.StringFieldUpdateOperationsInput | string
  instanceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkflowIdempotencyKeyUncheckedUpdateInput = {
  key?: Prisma.StringFieldUpdateOperationsInput | string
  scope?: Prisma.StringFieldUpdateOperationsInput | string
  instanceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkflowIdempotencyKeyCreateManyInput = {
  key: string
  scope: string
  instanceId?: string | null
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  expiresAt: Date | string
  createdAt?: Date | string
}

export type WorkflowIdempotencyKeyUpdateManyMutationInput = {
  key?: Prisma.StringFieldUpdateOperationsInput | string
  scope?: Prisma.StringFieldUpdateOperationsInput | string
  instanceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkflowIdempotencyKeyUncheckedUpdateManyInput = {
  key?: Prisma.StringFieldUpdateOperationsInput | string
  scope?: Prisma.StringFieldUpdateOperationsInput | string
  instanceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  result?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  expiresAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkflowIdempotencyKeyCountOrderByAggregateInput = {
  key?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  instanceId?: Prisma.SortOrder
  result?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type WorkflowIdempotencyKeyMaxOrderByAggregateInput = {
  key?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  instanceId?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type WorkflowIdempotencyKeyMinOrderByAggregateInput = {
  key?: Prisma.SortOrder
  scope?: Prisma.SortOrder
  instanceId?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}



export type WorkflowIdempotencyKeySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  key?: boolean
  scope?: boolean
  instanceId?: boolean
  result?: boolean
  expiresAt?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["workflowIdempotencyKey"]>

export type WorkflowIdempotencyKeySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  key?: boolean
  scope?: boolean
  instanceId?: boolean
  result?: boolean
  expiresAt?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["workflowIdempotencyKey"]>

export type WorkflowIdempotencyKeySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  key?: boolean
  scope?: boolean
  instanceId?: boolean
  result?: boolean
  expiresAt?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["workflowIdempotencyKey"]>

export type WorkflowIdempotencyKeySelectScalar = {
  key?: boolean
  scope?: boolean
  instanceId?: boolean
  result?: boolean
  expiresAt?: boolean
  createdAt?: boolean
}

export type WorkflowIdempotencyKeyOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"key" | "scope" | "instanceId" | "result" | "expiresAt" | "createdAt", ExtArgs["result"]["workflowIdempotencyKey"]>

export type $WorkflowIdempotencyKeyPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "WorkflowIdempotencyKey"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    key: string
    scope: string
    instanceId: string | null
    result: runtime.JsonValue | null
    expiresAt: Date
    createdAt: Date
  }, ExtArgs["result"]["workflowIdempotencyKey"]>
  composites: {}
}

export type WorkflowIdempotencyKeyGetPayload<S extends boolean | null | undefined | WorkflowIdempotencyKeyDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$WorkflowIdempotencyKeyPayload, S>

export type WorkflowIdempotencyKeyCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<WorkflowIdempotencyKeyFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: WorkflowIdempotencyKeyCountAggregateInputType | true
  }

export interface WorkflowIdempotencyKeyDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['WorkflowIdempotencyKey'], meta: { name: 'WorkflowIdempotencyKey' } }
  /**
   * Find zero or one WorkflowIdempotencyKey that matches the filter.
   * @param {WorkflowIdempotencyKeyFindUniqueArgs} args - Arguments to find a WorkflowIdempotencyKey
   * @example
   * // Get one WorkflowIdempotencyKey
   * const workflowIdempotencyKey = await prisma.workflowIdempotencyKey.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WorkflowIdempotencyKeyFindUniqueArgs>(args: Prisma.SelectSubset<T, WorkflowIdempotencyKeyFindUniqueArgs<ExtArgs>>): Prisma.Prisma__WorkflowIdempotencyKeyClient<runtime.Types.Result.GetResult<Prisma.$WorkflowIdempotencyKeyPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one WorkflowIdempotencyKey that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WorkflowIdempotencyKeyFindUniqueOrThrowArgs} args - Arguments to find a WorkflowIdempotencyKey
   * @example
   * // Get one WorkflowIdempotencyKey
   * const workflowIdempotencyKey = await prisma.workflowIdempotencyKey.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WorkflowIdempotencyKeyFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, WorkflowIdempotencyKeyFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkflowIdempotencyKeyClient<runtime.Types.Result.GetResult<Prisma.$WorkflowIdempotencyKeyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorkflowIdempotencyKey that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowIdempotencyKeyFindFirstArgs} args - Arguments to find a WorkflowIdempotencyKey
   * @example
   * // Get one WorkflowIdempotencyKey
   * const workflowIdempotencyKey = await prisma.workflowIdempotencyKey.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WorkflowIdempotencyKeyFindFirstArgs>(args?: Prisma.SelectSubset<T, WorkflowIdempotencyKeyFindFirstArgs<ExtArgs>>): Prisma.Prisma__WorkflowIdempotencyKeyClient<runtime.Types.Result.GetResult<Prisma.$WorkflowIdempotencyKeyPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorkflowIdempotencyKey that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowIdempotencyKeyFindFirstOrThrowArgs} args - Arguments to find a WorkflowIdempotencyKey
   * @example
   * // Get one WorkflowIdempotencyKey
   * const workflowIdempotencyKey = await prisma.workflowIdempotencyKey.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WorkflowIdempotencyKeyFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, WorkflowIdempotencyKeyFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkflowIdempotencyKeyClient<runtime.Types.Result.GetResult<Prisma.$WorkflowIdempotencyKeyPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more WorkflowIdempotencyKeys that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowIdempotencyKeyFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all WorkflowIdempotencyKeys
   * const workflowIdempotencyKeys = await prisma.workflowIdempotencyKey.findMany()
   * 
   * // Get first 10 WorkflowIdempotencyKeys
   * const workflowIdempotencyKeys = await prisma.workflowIdempotencyKey.findMany({ take: 10 })
   * 
   * // Only select the `key`
   * const workflowIdempotencyKeyWithKeyOnly = await prisma.workflowIdempotencyKey.findMany({ select: { key: true } })
   * 
   */
  findMany<T extends WorkflowIdempotencyKeyFindManyArgs>(args?: Prisma.SelectSubset<T, WorkflowIdempotencyKeyFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkflowIdempotencyKeyPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a WorkflowIdempotencyKey.
   * @param {WorkflowIdempotencyKeyCreateArgs} args - Arguments to create a WorkflowIdempotencyKey.
   * @example
   * // Create one WorkflowIdempotencyKey
   * const WorkflowIdempotencyKey = await prisma.workflowIdempotencyKey.create({
   *   data: {
   *     // ... data to create a WorkflowIdempotencyKey
   *   }
   * })
   * 
   */
  create<T extends WorkflowIdempotencyKeyCreateArgs>(args: Prisma.SelectSubset<T, WorkflowIdempotencyKeyCreateArgs<ExtArgs>>): Prisma.Prisma__WorkflowIdempotencyKeyClient<runtime.Types.Result.GetResult<Prisma.$WorkflowIdempotencyKeyPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many WorkflowIdempotencyKeys.
   * @param {WorkflowIdempotencyKeyCreateManyArgs} args - Arguments to create many WorkflowIdempotencyKeys.
   * @example
   * // Create many WorkflowIdempotencyKeys
   * const workflowIdempotencyKey = await prisma.workflowIdempotencyKey.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends WorkflowIdempotencyKeyCreateManyArgs>(args?: Prisma.SelectSubset<T, WorkflowIdempotencyKeyCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many WorkflowIdempotencyKeys and returns the data saved in the database.
   * @param {WorkflowIdempotencyKeyCreateManyAndReturnArgs} args - Arguments to create many WorkflowIdempotencyKeys.
   * @example
   * // Create many WorkflowIdempotencyKeys
   * const workflowIdempotencyKey = await prisma.workflowIdempotencyKey.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many WorkflowIdempotencyKeys and only return the `key`
   * const workflowIdempotencyKeyWithKeyOnly = await prisma.workflowIdempotencyKey.createManyAndReturn({
   *   select: { key: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends WorkflowIdempotencyKeyCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, WorkflowIdempotencyKeyCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkflowIdempotencyKeyPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a WorkflowIdempotencyKey.
   * @param {WorkflowIdempotencyKeyDeleteArgs} args - Arguments to delete one WorkflowIdempotencyKey.
   * @example
   * // Delete one WorkflowIdempotencyKey
   * const WorkflowIdempotencyKey = await prisma.workflowIdempotencyKey.delete({
   *   where: {
   *     // ... filter to delete one WorkflowIdempotencyKey
   *   }
   * })
   * 
   */
  delete<T extends WorkflowIdempotencyKeyDeleteArgs>(args: Prisma.SelectSubset<T, WorkflowIdempotencyKeyDeleteArgs<ExtArgs>>): Prisma.Prisma__WorkflowIdempotencyKeyClient<runtime.Types.Result.GetResult<Prisma.$WorkflowIdempotencyKeyPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one WorkflowIdempotencyKey.
   * @param {WorkflowIdempotencyKeyUpdateArgs} args - Arguments to update one WorkflowIdempotencyKey.
   * @example
   * // Update one WorkflowIdempotencyKey
   * const workflowIdempotencyKey = await prisma.workflowIdempotencyKey.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends WorkflowIdempotencyKeyUpdateArgs>(args: Prisma.SelectSubset<T, WorkflowIdempotencyKeyUpdateArgs<ExtArgs>>): Prisma.Prisma__WorkflowIdempotencyKeyClient<runtime.Types.Result.GetResult<Prisma.$WorkflowIdempotencyKeyPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more WorkflowIdempotencyKeys.
   * @param {WorkflowIdempotencyKeyDeleteManyArgs} args - Arguments to filter WorkflowIdempotencyKeys to delete.
   * @example
   * // Delete a few WorkflowIdempotencyKeys
   * const { count } = await prisma.workflowIdempotencyKey.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends WorkflowIdempotencyKeyDeleteManyArgs>(args?: Prisma.SelectSubset<T, WorkflowIdempotencyKeyDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorkflowIdempotencyKeys.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowIdempotencyKeyUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many WorkflowIdempotencyKeys
   * const workflowIdempotencyKey = await prisma.workflowIdempotencyKey.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends WorkflowIdempotencyKeyUpdateManyArgs>(args: Prisma.SelectSubset<T, WorkflowIdempotencyKeyUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorkflowIdempotencyKeys and returns the data updated in the database.
   * @param {WorkflowIdempotencyKeyUpdateManyAndReturnArgs} args - Arguments to update many WorkflowIdempotencyKeys.
   * @example
   * // Update many WorkflowIdempotencyKeys
   * const workflowIdempotencyKey = await prisma.workflowIdempotencyKey.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more WorkflowIdempotencyKeys and only return the `key`
   * const workflowIdempotencyKeyWithKeyOnly = await prisma.workflowIdempotencyKey.updateManyAndReturn({
   *   select: { key: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends WorkflowIdempotencyKeyUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, WorkflowIdempotencyKeyUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkflowIdempotencyKeyPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one WorkflowIdempotencyKey.
   * @param {WorkflowIdempotencyKeyUpsertArgs} args - Arguments to update or create a WorkflowIdempotencyKey.
   * @example
   * // Update or create a WorkflowIdempotencyKey
   * const workflowIdempotencyKey = await prisma.workflowIdempotencyKey.upsert({
   *   create: {
   *     // ... data to create a WorkflowIdempotencyKey
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the WorkflowIdempotencyKey we want to update
   *   }
   * })
   */
  upsert<T extends WorkflowIdempotencyKeyUpsertArgs>(args: Prisma.SelectSubset<T, WorkflowIdempotencyKeyUpsertArgs<ExtArgs>>): Prisma.Prisma__WorkflowIdempotencyKeyClient<runtime.Types.Result.GetResult<Prisma.$WorkflowIdempotencyKeyPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of WorkflowIdempotencyKeys.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowIdempotencyKeyCountArgs} args - Arguments to filter WorkflowIdempotencyKeys to count.
   * @example
   * // Count the number of WorkflowIdempotencyKeys
   * const count = await prisma.workflowIdempotencyKey.count({
   *   where: {
   *     // ... the filter for the WorkflowIdempotencyKeys we want to count
   *   }
   * })
  **/
  count<T extends WorkflowIdempotencyKeyCountArgs>(
    args?: Prisma.Subset<T, WorkflowIdempotencyKeyCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WorkflowIdempotencyKeyCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a WorkflowIdempotencyKey.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowIdempotencyKeyAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends WorkflowIdempotencyKeyAggregateArgs>(args: Prisma.Subset<T, WorkflowIdempotencyKeyAggregateArgs>): Prisma.PrismaPromise<GetWorkflowIdempotencyKeyAggregateType<T>>

  /**
   * Group by WorkflowIdempotencyKey.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowIdempotencyKeyGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends WorkflowIdempotencyKeyGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WorkflowIdempotencyKeyGroupByArgs['orderBy'] }
      : { orderBy?: WorkflowIdempotencyKeyGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, WorkflowIdempotencyKeyGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWorkflowIdempotencyKeyGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the WorkflowIdempotencyKey model
 */
readonly fields: WorkflowIdempotencyKeyFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for WorkflowIdempotencyKey.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WorkflowIdempotencyKeyClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the WorkflowIdempotencyKey model
 */
export interface WorkflowIdempotencyKeyFieldRefs {
  readonly key: Prisma.FieldRef<"WorkflowIdempotencyKey", 'String'>
  readonly scope: Prisma.FieldRef<"WorkflowIdempotencyKey", 'String'>
  readonly instanceId: Prisma.FieldRef<"WorkflowIdempotencyKey", 'String'>
  readonly result: Prisma.FieldRef<"WorkflowIdempotencyKey", 'Json'>
  readonly expiresAt: Prisma.FieldRef<"WorkflowIdempotencyKey", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"WorkflowIdempotencyKey", 'DateTime'>
}
    

// Custom InputTypes
/**
 * WorkflowIdempotencyKey findUnique
 */
export type WorkflowIdempotencyKeyFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowIdempotencyKey
   */
  select?: Prisma.WorkflowIdempotencyKeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowIdempotencyKey
   */
  omit?: Prisma.WorkflowIdempotencyKeyOmit<ExtArgs> | null
  /**
   * Filter, which WorkflowIdempotencyKey to fetch.
   */
  where: Prisma.WorkflowIdempotencyKeyWhereUniqueInput
}

/**
 * WorkflowIdempotencyKey findUniqueOrThrow
 */
export type WorkflowIdempotencyKeyFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowIdempotencyKey
   */
  select?: Prisma.WorkflowIdempotencyKeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowIdempotencyKey
   */
  omit?: Prisma.WorkflowIdempotencyKeyOmit<ExtArgs> | null
  /**
   * Filter, which WorkflowIdempotencyKey to fetch.
   */
  where: Prisma.WorkflowIdempotencyKeyWhereUniqueInput
}

/**
 * WorkflowIdempotencyKey findFirst
 */
export type WorkflowIdempotencyKeyFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowIdempotencyKey
   */
  select?: Prisma.WorkflowIdempotencyKeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowIdempotencyKey
   */
  omit?: Prisma.WorkflowIdempotencyKeyOmit<ExtArgs> | null
  /**
   * Filter, which WorkflowIdempotencyKey to fetch.
   */
  where?: Prisma.WorkflowIdempotencyKeyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkflowIdempotencyKeys to fetch.
   */
  orderBy?: Prisma.WorkflowIdempotencyKeyOrderByWithRelationInput | Prisma.WorkflowIdempotencyKeyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorkflowIdempotencyKeys.
   */
  cursor?: Prisma.WorkflowIdempotencyKeyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkflowIdempotencyKeys from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkflowIdempotencyKeys.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkflowIdempotencyKeys.
   */
  distinct?: Prisma.WorkflowIdempotencyKeyScalarFieldEnum | Prisma.WorkflowIdempotencyKeyScalarFieldEnum[]
}

/**
 * WorkflowIdempotencyKey findFirstOrThrow
 */
export type WorkflowIdempotencyKeyFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowIdempotencyKey
   */
  select?: Prisma.WorkflowIdempotencyKeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowIdempotencyKey
   */
  omit?: Prisma.WorkflowIdempotencyKeyOmit<ExtArgs> | null
  /**
   * Filter, which WorkflowIdempotencyKey to fetch.
   */
  where?: Prisma.WorkflowIdempotencyKeyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkflowIdempotencyKeys to fetch.
   */
  orderBy?: Prisma.WorkflowIdempotencyKeyOrderByWithRelationInput | Prisma.WorkflowIdempotencyKeyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorkflowIdempotencyKeys.
   */
  cursor?: Prisma.WorkflowIdempotencyKeyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkflowIdempotencyKeys from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkflowIdempotencyKeys.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkflowIdempotencyKeys.
   */
  distinct?: Prisma.WorkflowIdempotencyKeyScalarFieldEnum | Prisma.WorkflowIdempotencyKeyScalarFieldEnum[]
}

/**
 * WorkflowIdempotencyKey findMany
 */
export type WorkflowIdempotencyKeyFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowIdempotencyKey
   */
  select?: Prisma.WorkflowIdempotencyKeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowIdempotencyKey
   */
  omit?: Prisma.WorkflowIdempotencyKeyOmit<ExtArgs> | null
  /**
   * Filter, which WorkflowIdempotencyKeys to fetch.
   */
  where?: Prisma.WorkflowIdempotencyKeyWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkflowIdempotencyKeys to fetch.
   */
  orderBy?: Prisma.WorkflowIdempotencyKeyOrderByWithRelationInput | Prisma.WorkflowIdempotencyKeyOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing WorkflowIdempotencyKeys.
   */
  cursor?: Prisma.WorkflowIdempotencyKeyWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkflowIdempotencyKeys from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkflowIdempotencyKeys.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkflowIdempotencyKeys.
   */
  distinct?: Prisma.WorkflowIdempotencyKeyScalarFieldEnum | Prisma.WorkflowIdempotencyKeyScalarFieldEnum[]
}

/**
 * WorkflowIdempotencyKey create
 */
export type WorkflowIdempotencyKeyCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowIdempotencyKey
   */
  select?: Prisma.WorkflowIdempotencyKeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowIdempotencyKey
   */
  omit?: Prisma.WorkflowIdempotencyKeyOmit<ExtArgs> | null
  /**
   * The data needed to create a WorkflowIdempotencyKey.
   */
  data: Prisma.XOR<Prisma.WorkflowIdempotencyKeyCreateInput, Prisma.WorkflowIdempotencyKeyUncheckedCreateInput>
}

/**
 * WorkflowIdempotencyKey createMany
 */
export type WorkflowIdempotencyKeyCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many WorkflowIdempotencyKeys.
   */
  data: Prisma.WorkflowIdempotencyKeyCreateManyInput | Prisma.WorkflowIdempotencyKeyCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * WorkflowIdempotencyKey createManyAndReturn
 */
export type WorkflowIdempotencyKeyCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowIdempotencyKey
   */
  select?: Prisma.WorkflowIdempotencyKeySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowIdempotencyKey
   */
  omit?: Prisma.WorkflowIdempotencyKeyOmit<ExtArgs> | null
  /**
   * The data used to create many WorkflowIdempotencyKeys.
   */
  data: Prisma.WorkflowIdempotencyKeyCreateManyInput | Prisma.WorkflowIdempotencyKeyCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * WorkflowIdempotencyKey update
 */
export type WorkflowIdempotencyKeyUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowIdempotencyKey
   */
  select?: Prisma.WorkflowIdempotencyKeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowIdempotencyKey
   */
  omit?: Prisma.WorkflowIdempotencyKeyOmit<ExtArgs> | null
  /**
   * The data needed to update a WorkflowIdempotencyKey.
   */
  data: Prisma.XOR<Prisma.WorkflowIdempotencyKeyUpdateInput, Prisma.WorkflowIdempotencyKeyUncheckedUpdateInput>
  /**
   * Choose, which WorkflowIdempotencyKey to update.
   */
  where: Prisma.WorkflowIdempotencyKeyWhereUniqueInput
}

/**
 * WorkflowIdempotencyKey updateMany
 */
export type WorkflowIdempotencyKeyUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update WorkflowIdempotencyKeys.
   */
  data: Prisma.XOR<Prisma.WorkflowIdempotencyKeyUpdateManyMutationInput, Prisma.WorkflowIdempotencyKeyUncheckedUpdateManyInput>
  /**
   * Filter which WorkflowIdempotencyKeys to update
   */
  where?: Prisma.WorkflowIdempotencyKeyWhereInput
  /**
   * Limit how many WorkflowIdempotencyKeys to update.
   */
  limit?: number
}

/**
 * WorkflowIdempotencyKey updateManyAndReturn
 */
export type WorkflowIdempotencyKeyUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowIdempotencyKey
   */
  select?: Prisma.WorkflowIdempotencyKeySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowIdempotencyKey
   */
  omit?: Prisma.WorkflowIdempotencyKeyOmit<ExtArgs> | null
  /**
   * The data used to update WorkflowIdempotencyKeys.
   */
  data: Prisma.XOR<Prisma.WorkflowIdempotencyKeyUpdateManyMutationInput, Prisma.WorkflowIdempotencyKeyUncheckedUpdateManyInput>
  /**
   * Filter which WorkflowIdempotencyKeys to update
   */
  where?: Prisma.WorkflowIdempotencyKeyWhereInput
  /**
   * Limit how many WorkflowIdempotencyKeys to update.
   */
  limit?: number
}

/**
 * WorkflowIdempotencyKey upsert
 */
export type WorkflowIdempotencyKeyUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowIdempotencyKey
   */
  select?: Prisma.WorkflowIdempotencyKeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowIdempotencyKey
   */
  omit?: Prisma.WorkflowIdempotencyKeyOmit<ExtArgs> | null
  /**
   * The filter to search for the WorkflowIdempotencyKey to update in case it exists.
   */
  where: Prisma.WorkflowIdempotencyKeyWhereUniqueInput
  /**
   * In case the WorkflowIdempotencyKey found by the `where` argument doesn't exist, create a new WorkflowIdempotencyKey with this data.
   */
  create: Prisma.XOR<Prisma.WorkflowIdempotencyKeyCreateInput, Prisma.WorkflowIdempotencyKeyUncheckedCreateInput>
  /**
   * In case the WorkflowIdempotencyKey was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.WorkflowIdempotencyKeyUpdateInput, Prisma.WorkflowIdempotencyKeyUncheckedUpdateInput>
}

/**
 * WorkflowIdempotencyKey delete
 */
export type WorkflowIdempotencyKeyDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowIdempotencyKey
   */
  select?: Prisma.WorkflowIdempotencyKeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowIdempotencyKey
   */
  omit?: Prisma.WorkflowIdempotencyKeyOmit<ExtArgs> | null
  /**
   * Filter which WorkflowIdempotencyKey to delete.
   */
  where: Prisma.WorkflowIdempotencyKeyWhereUniqueInput
}

/**
 * WorkflowIdempotencyKey deleteMany
 */
export type WorkflowIdempotencyKeyDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorkflowIdempotencyKeys to delete
   */
  where?: Prisma.WorkflowIdempotencyKeyWhereInput
  /**
   * Limit how many WorkflowIdempotencyKeys to delete.
   */
  limit?: number
}

/**
 * WorkflowIdempotencyKey without action
 */
export type WorkflowIdempotencyKeyDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowIdempotencyKey
   */
  select?: Prisma.WorkflowIdempotencyKeySelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowIdempotencyKey
   */
  omit?: Prisma.WorkflowIdempotencyKeyOmit<ExtArgs> | null
}
